// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: worker/v1/worker.proto
// Protobuf Java Version: 4.36.1

package com.worker.v1;

@com.google.protobuf.Generated
public interface ExecuteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:worker.v1.ExecuteRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string command = 1 [json_name = "command"];</code>
   * @return The command.
   */
  java.lang.String getCommand();
  /**
   * <code>string command = 1 [json_name = "command"];</code>
   * @return The bytes for command.
   */
  com.google.protobuf.ByteString
      getCommandBytes();

  /**
   * <pre>
   * relative to the workspace root
   * </pre>
   *
   * <code>string workdir = 2 [json_name = "workdir"];</code>
   * @return The workdir.
   */
  java.lang.String getWorkdir();
  /**
   * <pre>
   * relative to the workspace root
   * </pre>
   *
   * <code>string workdir = 2 [json_name = "workdir"];</code>
   * @return The bytes for workdir.
   */
  com.google.protobuf.ByteString
      getWorkdirBytes();

  /**
   * <code>map&lt;string, string&gt; env = 3 [json_name = "env"];</code>
   */
  int getEnvCount();
  /**
   * <code>map&lt;string, string&gt; env = 3 [json_name = "env"];</code>
   */
  boolean containsEnv(
      java.lang.String key);
  /**
   * Use {@link #getEnvMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getEnv();
  /**
   * <code>map&lt;string, string&gt; env = 3 [json_name = "env"];</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getEnvMap();
  /**
   * <code>map&lt;string, string&gt; env = 3 [json_name = "env"];</code>
   */

  /* nullable */
java.lang.String getEnvOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; env = 3 [json_name = "env"];</code>
   */

  java.lang.String getEnvOrThrow(
      java.lang.String key);
}
