// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: worker/v1/worker.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package worker.v1;

@kotlin.jvm.JvmName("-initializefileListRequest")
public inline fun fileListRequest(block: worker.v1.FileListRequestKt.Dsl.() -> kotlin.Unit): worker.v1.Worker.FileListRequest =
  worker.v1.FileListRequestKt.Dsl._create(worker.v1.Worker.FileListRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `worker.v1.FileListRequest`
 */
public object FileListRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: worker.v1.Worker.FileListRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: worker.v1.Worker.FileListRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): worker.v1.Worker.FileListRequest = _builder.build()

    /**
     * `string path = 1 [json_name = "path"];`
     */
    public var path: kotlin.String
      @kotlin.jvm.JvmName("getPath")
        get() = _builder.path
      @kotlin.jvm.JvmName("setPath")
        set(value) {
        _builder.path = value
      }
    /**
     * `string path = 1 [json_name = "path"];`
     */
    public fun clearPath() {
      _builder.clearPath()
    }
  }
}
public inline fun worker.v1.Worker.FileListRequest.copy(block: `worker.v1`.FileListRequestKt.Dsl.() -> kotlin.Unit): worker.v1.Worker.FileListRequest =
  `worker.v1`.FileListRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

