// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: worker/v1/worker.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package worker.v1;

@kotlin.jvm.JvmName("-initializefileWriteResponse")
public inline fun fileWriteResponse(block: worker.v1.FileWriteResponseKt.Dsl.() -> kotlin.Unit): worker.v1.Worker.FileWriteResponse =
  worker.v1.FileWriteResponseKt.Dsl._create(worker.v1.Worker.FileWriteResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `worker.v1.FileWriteResponse`
 */
public object FileWriteResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: worker.v1.Worker.FileWriteResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: worker.v1.Worker.FileWriteResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): worker.v1.Worker.FileWriteResponse = _builder.build()

    /**
     * `bool ok = 1 [json_name = "ok"];`
     */
    public var ok: kotlin.Boolean
      @kotlin.jvm.JvmName("getOk")
        get() = _builder.ok
      @kotlin.jvm.JvmName("setOk")
        set(value) {
        _builder.ok = value
      }
    /**
     * `bool ok = 1 [json_name = "ok"];`
     */
    public fun clearOk() {
      _builder.clearOk()
    }
  }
}
public inline fun worker.v1.Worker.FileWriteResponse.copy(block: `worker.v1`.FileWriteResponseKt.Dsl.() -> kotlin.Unit): worker.v1.Worker.FileWriteResponse =
  `worker.v1`.FileWriteResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

