// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: worker/v1/worker.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package worker.v1;

@kotlin.jvm.JvmName("-initializeinfoRequest")
public inline fun infoRequest(block: worker.v1.InfoRequestKt.Dsl.() -> kotlin.Unit): worker.v1.Worker.InfoRequest =
  worker.v1.InfoRequestKt.Dsl._create(worker.v1.Worker.InfoRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `worker.v1.InfoRequest`
 */
public object InfoRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: worker.v1.Worker.InfoRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: worker.v1.Worker.InfoRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): worker.v1.Worker.InfoRequest = _builder.build()
  }
}
public inline fun worker.v1.Worker.InfoRequest.copy(block: `worker.v1`.InfoRequestKt.Dsl.() -> kotlin.Unit): worker.v1.Worker.InfoRequest =
  `worker.v1`.InfoRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

