// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: worker/v1/worker.proto
// Protobuf Java Version: 4.36.1

package com.worker.v1;

@com.google.protobuf.Generated
public interface JobOutputRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:worker.v1.JobOutputRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string job_id = 1 [json_name = "jobId"];</code>
   * @return The jobId.
   */
  java.lang.String getJobId();
  /**
   * <code>string job_id = 1 [json_name = "jobId"];</code>
   * @return The bytes for jobId.
   */
  com.google.protobuf.ByteString
      getJobIdBytes();

  /**
   * <pre>
   * line index, negative counts from the end (-200 = last 200)
   * </pre>
   *
   * <code>int32 start = 2 [json_name = "start"];</code>
   * @return The start.
   */
  int getStart();

  /**
   * <pre>
   * exclusive; 0 = through the end of buffer
   * </pre>
   *
   * <code>int32 end = 3 [json_name = "end"];</code>
   * @return The end.
   */
  int getEnd();

  /**
   * <pre>
   * all | stdout | stderr (default all)
   * </pre>
   *
   * <code>string stream = 4 [json_name = "stream"];</code>
   * @return The stream.
   */
  java.lang.String getStream();
  /**
   * <pre>
   * all | stdout | stderr (default all)
   * </pre>
   *
   * <code>string stream = 4 [json_name = "stream"];</code>
   * @return The bytes for stream.
   */
  com.google.protobuf.ByteString
      getStreamBytes();
}
