// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: worker/v1/worker.proto
// Protobuf Java Version: 4.36.1

package com.worker.v1;

@com.google.protobuf.Generated
public interface JobWaitResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:worker.v1.JobWaitResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string state = 1 [json_name = "state"];</code>
   * @return The state.
   */
  java.lang.String getState();
  /**
   * <code>string state = 1 [json_name = "state"];</code>
   * @return The bytes for state.
   */
  com.google.protobuf.ByteString
      getStateBytes();

  /**
   * <code>int32 exit_code = 2 [json_name = "exitCode"];</code>
   * @return The exitCode.
   */
  int getExitCode();
}
