// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: worker/v1/worker.proto
// Protobuf Java Version: 4.36.1

package com.worker.v1;

/**
 * Protobuf type {@code worker.v1.JobWaitResponse}
 */
@com.google.protobuf.Generated
public  final class JobWaitResponse extends
    com.google.protobuf.GeneratedMessageLite<
        JobWaitResponse, JobWaitResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:worker.v1.JobWaitResponse)
    JobWaitResponseOrBuilder {
  private JobWaitResponse() {
    state_ = "";
  }
  public static final int STATE_FIELD_NUMBER = 1;
  private java.lang.String state_;
  /**
   * <code>string state = 1 [json_name = "state"];</code>
   * @return The state.
   */
  @java.lang.Override
  public java.lang.String getState() {
    return state_;
  }
  /**
   * <code>string state = 1 [json_name = "state"];</code>
   * @return The bytes for state.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStateBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(state_);
  }
  /**
   * <code>string state = 1 [json_name = "state"];</code>
   * @param value The state to set.
   */
  private void setState(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    state_ = value;
  }
  /**
   * <code>string state = 1 [json_name = "state"];</code>
   */
  private void clearState() {

    state_ = getDefaultInstance().getState();
  }
  /**
   * <code>string state = 1 [json_name = "state"];</code>
   * @param value The bytes for state to set.
   */
  private void setStateBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    state_ = value.toStringUtf8();

  }

  public static final int EXIT_CODE_FIELD_NUMBER = 2;
  private int exitCode_;
  /**
   * <code>int32 exit_code = 2 [json_name = "exitCode"];</code>
   * @return The exitCode.
   */
  @java.lang.Override
  public int getExitCode() {
    return exitCode_;
  }
  /**
   * <code>int32 exit_code = 2 [json_name = "exitCode"];</code>
   * @param value The exitCode to set.
   */
  private void setExitCode(int value) {
    
    exitCode_ = value;
  }
  /**
   * <code>int32 exit_code = 2 [json_name = "exitCode"];</code>
   */
  private void clearExitCode() {

    exitCode_ = 0;
  }

  public static com.worker.v1.JobWaitResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.worker.v1.JobWaitResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.worker.v1.JobWaitResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.worker.v1.JobWaitResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.worker.v1.JobWaitResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.worker.v1.JobWaitResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.worker.v1.JobWaitResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.worker.v1.JobWaitResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.worker.v1.JobWaitResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.worker.v1.JobWaitResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.worker.v1.JobWaitResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.worker.v1.JobWaitResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.worker.v1.JobWaitResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code worker.v1.JobWaitResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.worker.v1.JobWaitResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:worker.v1.JobWaitResponse)
      com.worker.v1.JobWaitResponseOrBuilder {
    // Construct using com.worker.v1.JobWaitResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string state = 1 [json_name = "state"];</code>
     * @return The state.
     */
    @java.lang.Override
    public java.lang.String getState() {
      return instance.getState();
    }
    /**
     * <code>string state = 1 [json_name = "state"];</code>
     * @return The bytes for state.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStateBytes() {
      return instance.getStateBytes();
    }
    /**
     * <code>string state = 1 [json_name = "state"];</code>
     * @param value The state to set.
     * @return This builder for chaining.
     */
    public Builder setState(
        java.lang.String value) {
      copyOnWrite();
      instance.setState(value);
      return this;
    }
    /**
     * <code>string state = 1 [json_name = "state"];</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      copyOnWrite();
      instance.clearState();
      return this;
    }
    /**
     * <code>string state = 1 [json_name = "state"];</code>
     * @param value The bytes for state to set.
     * @return This builder for chaining.
     */
    public Builder setStateBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setStateBytes(value);
      return this;
    }

    /**
     * <code>int32 exit_code = 2 [json_name = "exitCode"];</code>
     * @return The exitCode.
     */
    @java.lang.Override
    public int getExitCode() {
      return instance.getExitCode();
    }
    /**
     * <code>int32 exit_code = 2 [json_name = "exitCode"];</code>
     * @param value The exitCode to set.
     * @return This builder for chaining.
     */
    public Builder setExitCode(int value) {
      copyOnWrite();
      instance.setExitCode(value);
      return this;
    }
    /**
     * <code>int32 exit_code = 2 [json_name = "exitCode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearExitCode() {
      copyOnWrite();
      instance.clearExitCode();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:worker.v1.JobWaitResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.worker.v1.JobWaitResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "state_",
            "exitCode_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0004" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.worker.v1.JobWaitResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.worker.v1.JobWaitResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.worker.v1.JobWaitResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:worker.v1.JobWaitResponse)
  private static final com.worker.v1.JobWaitResponse DEFAULT_INSTANCE;
  static {
    JobWaitResponse defaultInstance = new JobWaitResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      JobWaitResponse.class, defaultInstance);
  }

  public static com.worker.v1.JobWaitResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<JobWaitResponse> PARSER;

  public static com.google.protobuf.Parser<JobWaitResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

