// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: worker/v1/worker.proto
//
package com.worker.v1

import com.connectrpc.Headers
import com.connectrpc.ResponseMessage

/**
 *  ---- exclusive enrollment ----
 *
 *  A worker is fail-closed: until it has a bearer token it executes nothing.
 *  Two ways to obtain one:
 *
 *    1. PreAuthorized — the launcher sets WORKER_TOKEN in the container/host
 *       env (per-sandbox unique). No claim happens; the enroll face never
 *       opens. This is the easyLab-managed sandbox path.
 *    2. Unclaimed — no WORKER_TOKEN: the worker mints a one-time code at boot
 *       and prints it to stdout. The first caller presenting that code claims
 *       the worker EXCLUSIVELY; the worker then issues a token and permanently
 *       closes the enroll face (a second claim → AlreadyExists). This is the
 *       externally-registered sandbox / host runner path (2B).
 *
 *  The one-time code is never baked into an image and is destroyed on claim.
 *  Restarting the worker returns it to Unclaimed with a fresh code.
 */
public interface WorkerEnrollClientInterface {
  /**
   *  Status reports whether the worker still needs claiming (used by a
   *  controller to detect a restarted/unclaimed worker).
   */
  public suspend fun status(request: EnrollStatusRequest, headers: Headers = emptyMap()): ResponseMessage<EnrollStatusResponse>

  /**
   *  Claim consumes the one-time code and installs the worker-issued bearer
   *  token. One winner per worker lifetime; subsequent calls → AlreadyExists.
   */
  public suspend fun claim(request: EnrollClaimRequest, headers: Headers = emptyMap()): ResponseMessage<EnrollClaimResponse>

  /**
   *  Unrelease revokes the current token and returns the worker to Unclaimed
   *  with a FRESH one-time code. The released worker can then be claimed again
   *  by any caller holding the new code. Requires the CURRENT bearer token
   *  (only the current owner may release); pre-authorized (managed) workers
   *  cannot be released.
   */
  public suspend fun unrelease(request: EnrollUnreleaseRequest, headers: Headers = emptyMap()): ResponseMessage<EnrollUnreleaseResponse>
}
