// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easylab.v1;

@kotlin.jvm.JvmName("-initializecreateMergeRequestResponse")
public inline fun createMergeRequestResponse(block: com.easylab.v1.CreateMergeRequestResponseKt.Dsl.() -> kotlin.Unit): com.easylab.v1.CreateMergeRequestResponse =
  com.easylab.v1.CreateMergeRequestResponseKt.Dsl._create(com.easylab.v1.CreateMergeRequestResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easylab.v1.CreateMergeRequestResponse`
 */
public object CreateMergeRequestResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easylab.v1.CreateMergeRequestResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easylab.v1.CreateMergeRequestResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easylab.v1.CreateMergeRequestResponse = _builder.build()

    /**
     * `bool ok = 1 [json_name = "ok"];`
     */
    public var ok: kotlin.Boolean
      @kotlin.jvm.JvmName("getOk")
        get() = _builder.ok
      @kotlin.jvm.JvmName("setOk")
        set(value) {
        _builder.ok = value
      }
    /**
     * `bool ok = 1 [json_name = "ok"];`
     */
    public fun clearOk() {
      _builder.clearOk()
    }

    /**
     * `string error = 2 [json_name = "error"];`
     */
    public var error: kotlin.String
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `string error = 2 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }

    /**
     * `.easylab.v1.MergeRequest merge_request = 3 [json_name = "mergeRequest"];`
     */
    public var mergeRequest: com.easylab.v1.MergeRequest
      @kotlin.jvm.JvmName("getMergeRequest")
        get() = _builder.mergeRequest
      @kotlin.jvm.JvmName("setMergeRequest")
        set(value) {
        _builder.mergeRequest = value
      }
    /**
     * `.easylab.v1.MergeRequest merge_request = 3 [json_name = "mergeRequest"];`
     */
    public fun clearMergeRequest() {
      _builder.clearMergeRequest()
    }
    /**
     * `.easylab.v1.MergeRequest merge_request = 3 [json_name = "mergeRequest"];`
     * @return Whether the mergeRequest field is set.
     */
    public fun hasMergeRequest(): kotlin.Boolean {
      return _builder.hasMergeRequest()
    }

    public val CreateMergeRequestResponseKt.Dsl.mergeRequestOrNull: com.easylab.v1.MergeRequest?
      get() = _builder.mergeRequestOrNull
  }
}
public inline fun com.easylab.v1.CreateMergeRequestResponse.copy(block: `com.easylab.v1`.CreateMergeRequestResponseKt.Dsl.() -> kotlin.Unit): com.easylab.v1.CreateMergeRequestResponse =
  `com.easylab.v1`.CreateMergeRequestResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.easylab.v1.CreateMergeRequestResponseOrBuilder.mergeRequestOrNull: com.easylab.v1.MergeRequest?
  get() = if (hasMergeRequest()) getMergeRequest() else null

