// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto
// Protobuf Java Version: 4.36.1

package com.easylab.v1;

@com.google.protobuf.Generated
public interface CreateMergeRequestRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:easylab.v1.CreateMergeRequestRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string org = 1 [json_name = "org"];</code>
   * @return The org.
   */
  java.lang.String getOrg();
  /**
   * <code>string org = 1 [json_name = "org"];</code>
   * @return The bytes for org.
   */
  com.google.protobuf.ByteString
      getOrgBytes();

  /**
   * <code>string repo = 2 [json_name = "repo"];</code>
   * @return The repo.
   */
  java.lang.String getRepo();
  /**
   * <code>string repo = 2 [json_name = "repo"];</code>
   * @return The bytes for repo.
   */
  com.google.protobuf.ByteString
      getRepoBytes();

  /**
   * <code>string title = 3 [json_name = "title"];</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 3 [json_name = "title"];</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string description = 4 [json_name = "description"];</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 4 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string source = 5 [json_name = "source"];</code>
   * @return The source.
   */
  java.lang.String getSource();
  /**
   * <code>string source = 5 [json_name = "source"];</code>
   * @return The bytes for source.
   */
  com.google.protobuf.ByteString
      getSourceBytes();

  /**
   * <code>string target = 6 [json_name = "target"];</code>
   * @return The target.
   */
  java.lang.String getTarget();
  /**
   * <code>string target = 6 [json_name = "target"];</code>
   * @return The bytes for target.
   */
  com.google.protobuf.ByteString
      getTargetBytes();
}
