// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package easylab.v1;

@kotlin.jvm.JvmName("-initializedeletePackageRequest")
public inline fun deletePackageRequest(block: easylab.v1.DeletePackageRequestKt.Dsl.() -> kotlin.Unit): easylab.v1.Easylab.DeletePackageRequest =
  easylab.v1.DeletePackageRequestKt.Dsl._create(easylab.v1.Easylab.DeletePackageRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easylab.v1.DeletePackageRequest`
 */
public object DeletePackageRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: easylab.v1.Easylab.DeletePackageRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: easylab.v1.Easylab.DeletePackageRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): easylab.v1.Easylab.DeletePackageRequest = _builder.build()

    /**
     * `string type = 1 [json_name = "type"];`
     */
    public var type: kotlin.String
      @kotlin.jvm.JvmName("getType")
        get() = _builder.type
      @kotlin.jvm.JvmName("setType")
        set(value) {
        _builder.type = value
      }
    /**
     * `string type = 1 [json_name = "type"];`
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * `string name = 2 [json_name = "name"];`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 2 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }
  }
}
public inline fun easylab.v1.Easylab.DeletePackageRequest.copy(block: `easylab.v1`.DeletePackageRequestKt.Dsl.() -> kotlin.Unit): easylab.v1.Easylab.DeletePackageRequest =
  `easylab.v1`.DeletePackageRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

