// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto
// Protobuf Java Version: 4.36.1

package com.easylab.v1;

/**
 * Protobuf type {@code easylab.v1.DiffFile}
 */
@com.google.protobuf.Generated
public  final class DiffFile extends
    com.google.protobuf.GeneratedMessageLite<
        DiffFile, DiffFile.Builder> implements
    // @@protoc_insertion_point(message_implements:easylab.v1.DiffFile)
    DiffFileOrBuilder {
  private DiffFile() {
    path_ = "";
    diff_ = "";
  }
  public static final int PATH_FIELD_NUMBER = 1;
  private java.lang.String path_;
  /**
   * <code>string path = 1 [json_name = "path"];</code>
   * @return The path.
   */
  @java.lang.Override
  public java.lang.String getPath() {
    return path_;
  }
  /**
   * <code>string path = 1 [json_name = "path"];</code>
   * @return The bytes for path.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPathBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(path_);
  }
  /**
   * <code>string path = 1 [json_name = "path"];</code>
   * @param value The path to set.
   */
  private void setPath(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    path_ = value;
  }
  /**
   * <code>string path = 1 [json_name = "path"];</code>
   */
  private void clearPath() {

    path_ = getDefaultInstance().getPath();
  }
  /**
   * <code>string path = 1 [json_name = "path"];</code>
   * @param value The bytes for path to set.
   */
  private void setPathBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    path_ = value.toStringUtf8();

  }

  public static final int DIFF_FIELD_NUMBER = 2;
  private java.lang.String diff_;
  /**
   * <code>string diff = 2 [json_name = "diff"];</code>
   * @return The diff.
   */
  @java.lang.Override
  public java.lang.String getDiff() {
    return diff_;
  }
  /**
   * <code>string diff = 2 [json_name = "diff"];</code>
   * @return The bytes for diff.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDiffBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(diff_);
  }
  /**
   * <code>string diff = 2 [json_name = "diff"];</code>
   * @param value The diff to set.
   */
  private void setDiff(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    diff_ = value;
  }
  /**
   * <code>string diff = 2 [json_name = "diff"];</code>
   */
  private void clearDiff() {

    diff_ = getDefaultInstance().getDiff();
  }
  /**
   * <code>string diff = 2 [json_name = "diff"];</code>
   * @param value The bytes for diff to set.
   */
  private void setDiffBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    diff_ = value.toStringUtf8();

  }

  public static final int ADDITIONS_FIELD_NUMBER = 3;
  private int additions_;
  /**
   * <code>int32 additions = 3 [json_name = "additions"];</code>
   * @return The additions.
   */
  @java.lang.Override
  public int getAdditions() {
    return additions_;
  }
  /**
   * <code>int32 additions = 3 [json_name = "additions"];</code>
   * @param value The additions to set.
   */
  private void setAdditions(int value) {
    
    additions_ = value;
  }
  /**
   * <code>int32 additions = 3 [json_name = "additions"];</code>
   */
  private void clearAdditions() {

    additions_ = 0;
  }

  public static final int DELETIONS_FIELD_NUMBER = 4;
  private int deletions_;
  /**
   * <code>int32 deletions = 4 [json_name = "deletions"];</code>
   * @return The deletions.
   */
  @java.lang.Override
  public int getDeletions() {
    return deletions_;
  }
  /**
   * <code>int32 deletions = 4 [json_name = "deletions"];</code>
   * @param value The deletions to set.
   */
  private void setDeletions(int value) {
    
    deletions_ = value;
  }
  /**
   * <code>int32 deletions = 4 [json_name = "deletions"];</code>
   */
  private void clearDeletions() {

    deletions_ = 0;
  }

  public static com.easylab.v1.DiffFile parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.DiffFile parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.DiffFile parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.DiffFile parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.DiffFile parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.DiffFile parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.DiffFile parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easylab.v1.DiffFile parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.easylab.v1.DiffFile parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.easylab.v1.DiffFile parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.easylab.v1.DiffFile parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easylab.v1.DiffFile parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.easylab.v1.DiffFile prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code easylab.v1.DiffFile}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.easylab.v1.DiffFile, Builder> implements
      // @@protoc_insertion_point(builder_implements:easylab.v1.DiffFile)
      com.easylab.v1.DiffFileOrBuilder {
    // Construct using com.easylab.v1.DiffFile.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string path = 1 [json_name = "path"];</code>
     * @return The path.
     */
    @java.lang.Override
    public java.lang.String getPath() {
      return instance.getPath();
    }
    /**
     * <code>string path = 1 [json_name = "path"];</code>
     * @return The bytes for path.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPathBytes() {
      return instance.getPathBytes();
    }
    /**
     * <code>string path = 1 [json_name = "path"];</code>
     * @param value The path to set.
     * @return This builder for chaining.
     */
    public Builder setPath(
        java.lang.String value) {
      copyOnWrite();
      instance.setPath(value);
      return this;
    }
    /**
     * <code>string path = 1 [json_name = "path"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPath() {
      copyOnWrite();
      instance.clearPath();
      return this;
    }
    /**
     * <code>string path = 1 [json_name = "path"];</code>
     * @param value The bytes for path to set.
     * @return This builder for chaining.
     */
    public Builder setPathBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPathBytes(value);
      return this;
    }

    /**
     * <code>string diff = 2 [json_name = "diff"];</code>
     * @return The diff.
     */
    @java.lang.Override
    public java.lang.String getDiff() {
      return instance.getDiff();
    }
    /**
     * <code>string diff = 2 [json_name = "diff"];</code>
     * @return The bytes for diff.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDiffBytes() {
      return instance.getDiffBytes();
    }
    /**
     * <code>string diff = 2 [json_name = "diff"];</code>
     * @param value The diff to set.
     * @return This builder for chaining.
     */
    public Builder setDiff(
        java.lang.String value) {
      copyOnWrite();
      instance.setDiff(value);
      return this;
    }
    /**
     * <code>string diff = 2 [json_name = "diff"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDiff() {
      copyOnWrite();
      instance.clearDiff();
      return this;
    }
    /**
     * <code>string diff = 2 [json_name = "diff"];</code>
     * @param value The bytes for diff to set.
     * @return This builder for chaining.
     */
    public Builder setDiffBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDiffBytes(value);
      return this;
    }

    /**
     * <code>int32 additions = 3 [json_name = "additions"];</code>
     * @return The additions.
     */
    @java.lang.Override
    public int getAdditions() {
      return instance.getAdditions();
    }
    /**
     * <code>int32 additions = 3 [json_name = "additions"];</code>
     * @param value The additions to set.
     * @return This builder for chaining.
     */
    public Builder setAdditions(int value) {
      copyOnWrite();
      instance.setAdditions(value);
      return this;
    }
    /**
     * <code>int32 additions = 3 [json_name = "additions"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAdditions() {
      copyOnWrite();
      instance.clearAdditions();
      return this;
    }

    /**
     * <code>int32 deletions = 4 [json_name = "deletions"];</code>
     * @return The deletions.
     */
    @java.lang.Override
    public int getDeletions() {
      return instance.getDeletions();
    }
    /**
     * <code>int32 deletions = 4 [json_name = "deletions"];</code>
     * @param value The deletions to set.
     * @return This builder for chaining.
     */
    public Builder setDeletions(int value) {
      copyOnWrite();
      instance.setDeletions(value);
      return this;
    }
    /**
     * <code>int32 deletions = 4 [json_name = "deletions"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDeletions() {
      copyOnWrite();
      instance.clearDeletions();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:easylab.v1.DiffFile)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.easylab.v1.DiffFile();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "path_",
            "diff_",
            "additions_",
            "deletions_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0004\u0004\u0004";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.easylab.v1.DiffFile> parser = PARSER;
        if (parser == null) {
          synchronized (com.easylab.v1.DiffFile.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.easylab.v1.DiffFile>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:easylab.v1.DiffFile)
  private static final com.easylab.v1.DiffFile DEFAULT_INSTANCE;
  static {
    DiffFile defaultInstance = new DiffFile();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      DiffFile.class, defaultInstance);
  }

  public static com.easylab.v1.DiffFile getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DiffFile> PARSER;

  public static com.google.protobuf.Parser<DiffFile> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

