// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package easylab.v1;

@kotlin.jvm.JvmName("-initializediffFile")
public inline fun diffFile(block: easylab.v1.DiffFileKt.Dsl.() -> kotlin.Unit): easylab.v1.Easylab.DiffFile =
  easylab.v1.DiffFileKt.Dsl._create(easylab.v1.Easylab.DiffFile.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easylab.v1.DiffFile`
 */
public object DiffFileKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: easylab.v1.Easylab.DiffFile.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: easylab.v1.Easylab.DiffFile.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): easylab.v1.Easylab.DiffFile = _builder.build()

    /**
     * `string path = 1 [json_name = "path"];`
     */
    public var path: kotlin.String
      @kotlin.jvm.JvmName("getPath")
        get() = _builder.path
      @kotlin.jvm.JvmName("setPath")
        set(value) {
        _builder.path = value
      }
    /**
     * `string path = 1 [json_name = "path"];`
     */
    public fun clearPath() {
      _builder.clearPath()
    }

    /**
     * `string diff = 2 [json_name = "diff"];`
     */
    public var diff: kotlin.String
      @kotlin.jvm.JvmName("getDiff")
        get() = _builder.diff
      @kotlin.jvm.JvmName("setDiff")
        set(value) {
        _builder.diff = value
      }
    /**
     * `string diff = 2 [json_name = "diff"];`
     */
    public fun clearDiff() {
      _builder.clearDiff()
    }

    /**
     * `int32 additions = 3 [json_name = "additions"];`
     */
    public var additions: kotlin.Int
      @kotlin.jvm.JvmName("getAdditions")
        get() = _builder.additions
      @kotlin.jvm.JvmName("setAdditions")
        set(value) {
        _builder.additions = value
      }
    /**
     * `int32 additions = 3 [json_name = "additions"];`
     */
    public fun clearAdditions() {
      _builder.clearAdditions()
    }

    /**
     * `int32 deletions = 4 [json_name = "deletions"];`
     */
    public var deletions: kotlin.Int
      @kotlin.jvm.JvmName("getDeletions")
        get() = _builder.deletions
      @kotlin.jvm.JvmName("setDeletions")
        set(value) {
        _builder.deletions = value
      }
    /**
     * `int32 deletions = 4 [json_name = "deletions"];`
     */
    public fun clearDeletions() {
      _builder.clearDeletions()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun easylab.v1.Easylab.DiffFile.copy(block: `easylab.v1`.DiffFileKt.Dsl.() -> kotlin.Unit): easylab.v1.Easylab.DiffFile =
  `easylab.v1`.DiffFileKt.Dsl._create(this.toBuilder()).apply { block() }._build()

