// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto
// Protobuf Java Version: 4.36.1

package com.easylab.v1;

@com.google.protobuf.Generated
public interface EnsureSandboxImageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:easylab.v1.EnsureSandboxImageResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string derived_image = 1 [json_name = "derivedImage"];</code>
   * @return The derivedImage.
   */
  java.lang.String getDerivedImage();
  /**
   * <code>string derived_image = 1 [json_name = "derivedImage"];</code>
   * @return The bytes for derivedImage.
   */
  com.google.protobuf.ByteString
      getDerivedImageBytes();

  /**
   * <pre>
   * false = cache hit
   * </pre>
   *
   * <code>bool built = 2 [json_name = "built"];</code>
   * @return The built.
   */
  boolean getBuilt();
}
