// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto
// Protobuf Java Version: 4.36.1

package com.easylab.v1;

/**
 * Protobuf type {@code easylab.v1.ExecuteRequest}
 */
@com.google.protobuf.Generated
public  final class ExecuteRequest extends
    com.google.protobuf.GeneratedMessageLite<
        ExecuteRequest, ExecuteRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:easylab.v1.ExecuteRequest)
    ExecuteRequestOrBuilder {
  private ExecuteRequest() {
    sandbox_ = "";
  }
  private int bitField0_;
  public static final int SANDBOX_FIELD_NUMBER = 1;
  private java.lang.String sandbox_;
  /**
   * <code>string sandbox = 1 [json_name = "sandbox"];</code>
   * @return The sandbox.
   */
  @java.lang.Override
  public java.lang.String getSandbox() {
    return sandbox_;
  }
  /**
   * <code>string sandbox = 1 [json_name = "sandbox"];</code>
   * @return The bytes for sandbox.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSandboxBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(sandbox_);
  }
  /**
   * <code>string sandbox = 1 [json_name = "sandbox"];</code>
   * @param value The sandbox to set.
   */
  private void setSandbox(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    sandbox_ = value;
  }
  /**
   * <code>string sandbox = 1 [json_name = "sandbox"];</code>
   */
  private void clearSandbox() {

    sandbox_ = getDefaultInstance().getSandbox();
  }
  /**
   * <code>string sandbox = 1 [json_name = "sandbox"];</code>
   * @param value The bytes for sandbox to set.
   */
  private void setSandboxBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    sandbox_ = value.toStringUtf8();

  }

  public static final int REQ_FIELD_NUMBER = 2;
  private com.worker.v1.ExecuteRequest req_;
  /**
   * <code>.worker.v1.ExecuteRequest req = 2 [json_name = "req"];</code>
   */
  @java.lang.Override
  public boolean hasReq() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.worker.v1.ExecuteRequest req = 2 [json_name = "req"];</code>
   */
  @java.lang.Override
  public com.worker.v1.ExecuteRequest getReq() {
    return req_ == null ? com.worker.v1.ExecuteRequest.getDefaultInstance() : req_;
  }
  /**
   * <code>.worker.v1.ExecuteRequest req = 2 [json_name = "req"];</code>
   */
  private void setReq(com.worker.v1.ExecuteRequest value) {
    java.util.Objects.requireNonNull(value);
    req_ = value;
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.worker.v1.ExecuteRequest req = 2 [json_name = "req"];</code>
   */
  @java.lang.SuppressWarnings("ReferenceEquality")
  private void mergeReq(com.worker.v1.ExecuteRequest value) {
    java.util.Objects.requireNonNull(value);
    if (req_ != null &&
        req_ != com.worker.v1.ExecuteRequest.getDefaultInstance()) {
      req_ =
        com.worker.v1.ExecuteRequest.newBuilder(req_).mergeFrom(value).buildPartial();
    } else {
      req_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.worker.v1.ExecuteRequest req = 2 [json_name = "req"];</code>
   */
  private void clearReq() {
    req_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static com.easylab.v1.ExecuteRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.ExecuteRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.ExecuteRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.ExecuteRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.ExecuteRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.ExecuteRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.ExecuteRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easylab.v1.ExecuteRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.easylab.v1.ExecuteRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.easylab.v1.ExecuteRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.easylab.v1.ExecuteRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easylab.v1.ExecuteRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.easylab.v1.ExecuteRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code easylab.v1.ExecuteRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.easylab.v1.ExecuteRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:easylab.v1.ExecuteRequest)
      com.easylab.v1.ExecuteRequestOrBuilder {
    // Construct using com.easylab.v1.ExecuteRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string sandbox = 1 [json_name = "sandbox"];</code>
     * @return The sandbox.
     */
    @java.lang.Override
    public java.lang.String getSandbox() {
      return instance.getSandbox();
    }
    /**
     * <code>string sandbox = 1 [json_name = "sandbox"];</code>
     * @return The bytes for sandbox.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSandboxBytes() {
      return instance.getSandboxBytes();
    }
    /**
     * <code>string sandbox = 1 [json_name = "sandbox"];</code>
     * @param value The sandbox to set.
     * @return This builder for chaining.
     */
    public Builder setSandbox(
        java.lang.String value) {
      copyOnWrite();
      instance.setSandbox(value);
      return this;
    }
    /**
     * <code>string sandbox = 1 [json_name = "sandbox"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSandbox() {
      copyOnWrite();
      instance.clearSandbox();
      return this;
    }
    /**
     * <code>string sandbox = 1 [json_name = "sandbox"];</code>
     * @param value The bytes for sandbox to set.
     * @return This builder for chaining.
     */
    public Builder setSandboxBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSandboxBytes(value);
      return this;
    }

    /**
     * <code>.worker.v1.ExecuteRequest req = 2 [json_name = "req"];</code>
     */
    @java.lang.Override
    public boolean hasReq() {
      return instance.hasReq();
    }
    /**
     * <code>.worker.v1.ExecuteRequest req = 2 [json_name = "req"];</code>
     */
    @java.lang.Override
    public com.worker.v1.ExecuteRequest getReq() {
      return instance.getReq();
    }
    /**
     * <code>.worker.v1.ExecuteRequest req = 2 [json_name = "req"];</code>
     */
    public Builder setReq(com.worker.v1.ExecuteRequest value) {
      copyOnWrite();
      instance.setReq(value);
      return this;
      }
    /**
     * <code>.worker.v1.ExecuteRequest req = 2 [json_name = "req"];</code>
     */
    public Builder setReq(
        com.worker.v1.ExecuteRequest.Builder builderForValue) {
      copyOnWrite();
      instance.setReq(builderForValue.build());
      return this;
    }
    /**
     * <code>.worker.v1.ExecuteRequest req = 2 [json_name = "req"];</code>
     */
    public Builder mergeReq(com.worker.v1.ExecuteRequest value) {
      copyOnWrite();
      instance.mergeReq(value);
      return this;
    }
    /**
     * <code>.worker.v1.ExecuteRequest req = 2 [json_name = "req"];</code>
     */
    public Builder clearReq() {  copyOnWrite();
      instance.clearReq();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:easylab.v1.ExecuteRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.easylab.v1.ExecuteRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "sandbox_",
            "req_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u1009" +
              "\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.easylab.v1.ExecuteRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.easylab.v1.ExecuteRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.easylab.v1.ExecuteRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:easylab.v1.ExecuteRequest)
  private static final com.easylab.v1.ExecuteRequest DEFAULT_INSTANCE;
  static {
    ExecuteRequest defaultInstance = new ExecuteRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ExecuteRequest.class, defaultInstance);
  }

  public static com.easylab.v1.ExecuteRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ExecuteRequest> PARSER;

  public static com.google.protobuf.Parser<ExecuteRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

