// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package easylab.v1;

@kotlin.jvm.JvmName("-initializefileEntry")
public inline fun fileEntry(block: easylab.v1.FileEntryKt.Dsl.() -> kotlin.Unit): easylab.v1.Easylab.FileEntry =
  easylab.v1.FileEntryKt.Dsl._create(easylab.v1.Easylab.FileEntry.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easylab.v1.FileEntry`
 */
public object FileEntryKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: easylab.v1.Easylab.FileEntry.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: easylab.v1.Easylab.FileEntry.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): easylab.v1.Easylab.FileEntry = _builder.build()

    /**
     * `string name = 1 [json_name = "name"];`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 1 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `string path = 2 [json_name = "path"];`
     */
    public var path: kotlin.String
      @kotlin.jvm.JvmName("getPath")
        get() = _builder.path
      @kotlin.jvm.JvmName("setPath")
        set(value) {
        _builder.path = value
      }
    /**
     * `string path = 2 [json_name = "path"];`
     */
    public fun clearPath() {
      _builder.clearPath()
    }

    /**
     * ```
     * file | dir | symlink | ...
     * ```
     *
     * `string kind = 3 [json_name = "kind"];`
     */
    public var kind: kotlin.String
      @kotlin.jvm.JvmName("getKind")
        get() = _builder.kind
      @kotlin.jvm.JvmName("setKind")
        set(value) {
        _builder.kind = value
      }
    /**
     * ```
     * file | dir | symlink | ...
     * ```
     *
     * `string kind = 3 [json_name = "kind"];`
     */
    public fun clearKind() {
      _builder.clearKind()
    }

    /**
     * `int32 size = 4 [json_name = "size"];`
     */
    public var size: kotlin.Int
      @kotlin.jvm.JvmName("getSize")
        get() = _builder.size
      @kotlin.jvm.JvmName("setSize")
        set(value) {
        _builder.size = value
      }
    /**
     * `int32 size = 4 [json_name = "size"];`
     */
    public fun clearSize() {
      _builder.clearSize()
    }
  }
}
public inline fun easylab.v1.Easylab.FileEntry.copy(block: `easylab.v1`.FileEntryKt.Dsl.() -> kotlin.Unit): easylab.v1.Easylab.FileEntry =
  `easylab.v1`.FileEntryKt.Dsl._create(this.toBuilder()).apply { block() }._build()

