// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto
// Protobuf Java Version: 4.36.1

package com.easylab.v1;

/**
 * Protobuf type {@code easylab.v1.JobInstance}
 */
@com.google.protobuf.Generated
public  final class JobInstance extends
    com.google.protobuf.GeneratedMessageLite<
        JobInstance, JobInstance.Builder> implements
    // @@protoc_insertion_point(message_implements:easylab.v1.JobInstance)
    JobInstanceOrBuilder {
  private JobInstance() {
    id_ = "";
    defId_ = "";
    status_ = "";
    result_ = "";
  }
  public static final int ID_FIELD_NUMBER = 1;
  private java.lang.String id_;
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    return id_;
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(id_);
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @param value The id to set.
   */
  private void setId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    id_ = value;
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   */
  private void clearId() {

    id_ = getDefaultInstance().getId();
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @param value The bytes for id to set.
   */
  private void setIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    id_ = value.toStringUtf8();

  }

  public static final int DEF_ID_FIELD_NUMBER = 2;
  private java.lang.String defId_;
  /**
   * <code>string def_id = 2 [json_name = "defId"];</code>
   * @return The defId.
   */
  @java.lang.Override
  public java.lang.String getDefId() {
    return defId_;
  }
  /**
   * <code>string def_id = 2 [json_name = "defId"];</code>
   * @return The bytes for defId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDefIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(defId_);
  }
  /**
   * <code>string def_id = 2 [json_name = "defId"];</code>
   * @param value The defId to set.
   */
  private void setDefId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    defId_ = value;
  }
  /**
   * <code>string def_id = 2 [json_name = "defId"];</code>
   */
  private void clearDefId() {

    defId_ = getDefaultInstance().getDefId();
  }
  /**
   * <code>string def_id = 2 [json_name = "defId"];</code>
   * @param value The bytes for defId to set.
   */
  private void setDefIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    defId_ = value.toStringUtf8();

  }

  public static final int STATUS_FIELD_NUMBER = 3;
  private java.lang.String status_;
  /**
   * <pre>
   * pending | running | success | failure | cancelled
   * </pre>
   *
   * <code>string status = 3 [json_name = "status"];</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    return status_;
  }
  /**
   * <pre>
   * pending | running | success | failure | cancelled
   * </pre>
   *
   * <code>string status = 3 [json_name = "status"];</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(status_);
  }
  /**
   * <pre>
   * pending | running | success | failure | cancelled
   * </pre>
   *
   * <code>string status = 3 [json_name = "status"];</code>
   * @param value The status to set.
   */
  private void setStatus(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    status_ = value;
  }
  /**
   * <pre>
   * pending | running | success | failure | cancelled
   * </pre>
   *
   * <code>string status = 3 [json_name = "status"];</code>
   */
  private void clearStatus() {

    status_ = getDefaultInstance().getStatus();
  }
  /**
   * <pre>
   * pending | running | success | failure | cancelled
   * </pre>
   *
   * <code>string status = 3 [json_name = "status"];</code>
   * @param value The bytes for status to set.
   */
  private void setStatusBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    status_ = value.toStringUtf8();

  }

  public static final int RESULT_FIELD_NUMBER = 4;
  private java.lang.String result_;
  /**
   * <code>string result = 4 [json_name = "result"];</code>
   * @return The result.
   */
  @java.lang.Override
  public java.lang.String getResult() {
    return result_;
  }
  /**
   * <code>string result = 4 [json_name = "result"];</code>
   * @return The bytes for result.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResultBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(result_);
  }
  /**
   * <code>string result = 4 [json_name = "result"];</code>
   * @param value The result to set.
   */
  private void setResult(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    result_ = value;
  }
  /**
   * <code>string result = 4 [json_name = "result"];</code>
   */
  private void clearResult() {

    result_ = getDefaultInstance().getResult();
  }
  /**
   * <code>string result = 4 [json_name = "result"];</code>
   * @param value The bytes for result to set.
   */
  private void setResultBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    result_ = value.toStringUtf8();

  }

  public static com.easylab.v1.JobInstance parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.JobInstance parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.JobInstance parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.JobInstance parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.JobInstance parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.JobInstance parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.JobInstance parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easylab.v1.JobInstance parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.easylab.v1.JobInstance parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.easylab.v1.JobInstance parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.easylab.v1.JobInstance parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easylab.v1.JobInstance parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.easylab.v1.JobInstance prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code easylab.v1.JobInstance}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.easylab.v1.JobInstance, Builder> implements
      // @@protoc_insertion_point(builder_implements:easylab.v1.JobInstance)
      com.easylab.v1.JobInstanceOrBuilder {
    // Construct using com.easylab.v1.JobInstance.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      return instance.getId();
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return instance.getIdBytes();
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdBytes(value);
      return this;
    }

    /**
     * <code>string def_id = 2 [json_name = "defId"];</code>
     * @return The defId.
     */
    @java.lang.Override
    public java.lang.String getDefId() {
      return instance.getDefId();
    }
    /**
     * <code>string def_id = 2 [json_name = "defId"];</code>
     * @return The bytes for defId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDefIdBytes() {
      return instance.getDefIdBytes();
    }
    /**
     * <code>string def_id = 2 [json_name = "defId"];</code>
     * @param value The defId to set.
     * @return This builder for chaining.
     */
    public Builder setDefId(
        java.lang.String value) {
      copyOnWrite();
      instance.setDefId(value);
      return this;
    }
    /**
     * <code>string def_id = 2 [json_name = "defId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDefId() {
      copyOnWrite();
      instance.clearDefId();
      return this;
    }
    /**
     * <code>string def_id = 2 [json_name = "defId"];</code>
     * @param value The bytes for defId to set.
     * @return This builder for chaining.
     */
    public Builder setDefIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDefIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * pending | running | success | failure | cancelled
     * </pre>
     *
     * <code>string status = 3 [json_name = "status"];</code>
     * @return The status.
     */
    @java.lang.Override
    public java.lang.String getStatus() {
      return instance.getStatus();
    }
    /**
     * <pre>
     * pending | running | success | failure | cancelled
     * </pre>
     *
     * <code>string status = 3 [json_name = "status"];</code>
     * @return The bytes for status.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStatusBytes() {
      return instance.getStatusBytes();
    }
    /**
     * <pre>
     * pending | running | success | failure | cancelled
     * </pre>
     *
     * <code>string status = 3 [json_name = "status"];</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      copyOnWrite();
      instance.setStatus(value);
      return this;
    }
    /**
     * <pre>
     * pending | running | success | failure | cancelled
     * </pre>
     *
     * <code>string status = 3 [json_name = "status"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      copyOnWrite();
      instance.clearStatus();
      return this;
    }
    /**
     * <pre>
     * pending | running | success | failure | cancelled
     * </pre>
     *
     * <code>string status = 3 [json_name = "status"];</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setStatusBytes(value);
      return this;
    }

    /**
     * <code>string result = 4 [json_name = "result"];</code>
     * @return The result.
     */
    @java.lang.Override
    public java.lang.String getResult() {
      return instance.getResult();
    }
    /**
     * <code>string result = 4 [json_name = "result"];</code>
     * @return The bytes for result.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResultBytes() {
      return instance.getResultBytes();
    }
    /**
     * <code>string result = 4 [json_name = "result"];</code>
     * @param value The result to set.
     * @return This builder for chaining.
     */
    public Builder setResult(
        java.lang.String value) {
      copyOnWrite();
      instance.setResult(value);
      return this;
    }
    /**
     * <code>string result = 4 [json_name = "result"];</code>
     * @return This builder for chaining.
     */
    public Builder clearResult() {
      copyOnWrite();
      instance.clearResult();
      return this;
    }
    /**
     * <code>string result = 4 [json_name = "result"];</code>
     * @param value The bytes for result to set.
     * @return This builder for chaining.
     */
    public Builder setResultBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setResultBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:easylab.v1.JobInstance)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.easylab.v1.JobInstance();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "id_",
            "defId_",
            "status_",
            "result_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.easylab.v1.JobInstance> parser = PARSER;
        if (parser == null) {
          synchronized (com.easylab.v1.JobInstance.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.easylab.v1.JobInstance>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:easylab.v1.JobInstance)
  private static final com.easylab.v1.JobInstance DEFAULT_INSTANCE;
  static {
    JobInstance defaultInstance = new JobInstance();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      JobInstance.class, defaultInstance);
  }

  public static com.easylab.v1.JobInstance getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<JobInstance> PARSER;

  public static com.google.protobuf.Parser<JobInstance> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

