// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto
// Protobuf Java Version: 4.36.1

package com.easylab.v1;

@com.google.protobuf.Generated
public interface LaunchSandboxRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:easylab.v1.LaunchSandboxRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string base_image = 2 [json_name = "baseImage"];</code>
   * @return The baseImage.
   */
  java.lang.String getBaseImage();
  /**
   * <code>string base_image = 2 [json_name = "baseImage"];</code>
   * @return The bytes for baseImage.
   */
  com.google.protobuf.ByteString
      getBaseImageBytes();

  /**
   * <pre>
   * '' = standalone (independent sandbox, never synced)
   * </pre>
   *
   * <code>string org = 3 [json_name = "org"];</code>
   * @return The org.
   */
  java.lang.String getOrg();
  /**
   * <pre>
   * '' = standalone (independent sandbox, never synced)
   * </pre>
   *
   * <code>string org = 3 [json_name = "org"];</code>
   * @return The bytes for org.
   */
  com.google.protobuf.ByteString
      getOrgBytes();

  /**
   * <code>string repo = 4 [json_name = "repo"];</code>
   * @return The repo.
   */
  java.lang.String getRepo();
  /**
   * <code>string repo = 4 [json_name = "repo"];</code>
   * @return The bytes for repo.
   */
  com.google.protobuf.ByteString
      getRepoBytes();

  /**
   * <code>string branch = 5 [json_name = "branch"];</code>
   * @return The branch.
   */
  java.lang.String getBranch();
  /**
   * <code>string branch = 5 [json_name = "branch"];</code>
   * @return The bytes for branch.
   */
  com.google.protobuf.ByteString
      getBranchBytes();

  /**
   * <pre>
   * default /workspace
   * </pre>
   *
   * <code>string workspace = 6 [json_name = "workspace"];</code>
   * @return The workspace.
   */
  java.lang.String getWorkspace();
  /**
   * <pre>
   * default /workspace
   * </pre>
   *
   * <code>string workspace = 6 [json_name = "workspace"];</code>
   * @return The bytes for workspace.
   */
  com.google.protobuf.ByteString
      getWorkspaceBytes();

  /**
   * <code>map&lt;string, string&gt; env = 7 [json_name = "env"];</code>
   */
  int getEnvCount();
  /**
   * <code>map&lt;string, string&gt; env = 7 [json_name = "env"];</code>
   */
  boolean containsEnv(
      java.lang.String key);
  /**
   * Use {@link #getEnvMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getEnv();
  /**
   * <code>map&lt;string, string&gt; env = 7 [json_name = "env"];</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getEnvMap();
  /**
   * <code>map&lt;string, string&gt; env = 7 [json_name = "env"];</code>
   */

  /* nullable */
java.lang.String getEnvOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; env = 7 [json_name = "env"];</code>
   */

  java.lang.String getEnvOrThrow(
      java.lang.String key);

  /**
   * <code>string cpus = 8 [json_name = "cpus"];</code>
   * @return The cpus.
   */
  java.lang.String getCpus();
  /**
   * <code>string cpus = 8 [json_name = "cpus"];</code>
   * @return The bytes for cpus.
   */
  com.google.protobuf.ByteString
      getCpusBytes();

  /**
   * <code>uint64 memory_bytes = 9 [json_name = "memoryBytes"];</code>
   * @return The memoryBytes.
   */
  long getMemoryBytes();

  /**
   * <pre>
   * Execution runtime/profile: "" or "linux" (default; base image + injected
   * worker), "windows"/"macos" (a VM-backed worker image served by easylab).
   * </pre>
   *
   * <code>string runtime = 10 [json_name = "runtime"];</code>
   * @return The runtime.
   */
  java.lang.String getRuntime();
  /**
   * <pre>
   * Execution runtime/profile: "" or "linux" (default; base image + injected
   * worker), "windows"/"macos" (a VM-backed worker image served by easylab).
   * </pre>
   *
   * <code>string runtime = 10 [json_name = "runtime"];</code>
   * @return The bytes for runtime.
   */
  com.google.protobuf.ByteString
      getRuntimeBytes();
}
