// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easylab.v1;

@kotlin.jvm.JvmName("-initializelistUsersResponse")
public inline fun listUsersResponse(block: com.easylab.v1.ListUsersResponseKt.Dsl.() -> kotlin.Unit): com.easylab.v1.ListUsersResponse =
  com.easylab.v1.ListUsersResponseKt.Dsl._create(com.easylab.v1.ListUsersResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easylab.v1.ListUsersResponse`
 */
public object ListUsersResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easylab.v1.ListUsersResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easylab.v1.ListUsersResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easylab.v1.ListUsersResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class UsersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .easylab.v1.User users = 1 [json_name = "users"];`
     */
     public val users: com.google.protobuf.kotlin.DslList<com.easylab.v1.User, UsersProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.usersList
      )
    /**
     * `repeated .easylab.v1.User users = 1 [json_name = "users"];`
     * @param value The users to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addUsers")
    public fun com.google.protobuf.kotlin.DslList<com.easylab.v1.User, UsersProxy>.add(value: com.easylab.v1.User) {
      _builder.addUsers(value)
    }
    /**
     * `repeated .easylab.v1.User users = 1 [json_name = "users"];`
     * @param value The users to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignUsers")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.easylab.v1.User, UsersProxy>.plusAssign(value: com.easylab.v1.User) {
      add(value)
    }
    /**
     * `repeated .easylab.v1.User users = 1 [json_name = "users"];`
     * @param values The users to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllUsers")
    public fun com.google.protobuf.kotlin.DslList<com.easylab.v1.User, UsersProxy>.addAll(values: kotlin.collections.Iterable<com.easylab.v1.User>) {
      _builder.addAllUsers(values)
    }
    /**
     * `repeated .easylab.v1.User users = 1 [json_name = "users"];`
     * @param values The users to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllUsers")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.easylab.v1.User, UsersProxy>.plusAssign(values: kotlin.collections.Iterable<com.easylab.v1.User>) {
      addAll(values)
    }
    /**
     * `repeated .easylab.v1.User users = 1 [json_name = "users"];`
     * @param index The index to set the value at.
     * @param value The users to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setUsers")
    public operator fun com.google.protobuf.kotlin.DslList<com.easylab.v1.User, UsersProxy>.set(index: kotlin.Int, value: com.easylab.v1.User) {
      _builder.setUsers(index, value)
    }
    /**
     * `repeated .easylab.v1.User users = 1 [json_name = "users"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearUsers")
    public fun com.google.protobuf.kotlin.DslList<com.easylab.v1.User, UsersProxy>.clear() {
      _builder.clearUsers()
    }
  }
}
public inline fun com.easylab.v1.ListUsersResponse.copy(block: `com.easylab.v1`.ListUsersResponseKt.Dsl.() -> kotlin.Unit): com.easylab.v1.ListUsersResponse =
  `com.easylab.v1`.ListUsersResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

