// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package easylab.v1;

@kotlin.jvm.JvmName("-initializelistUsersRequest")
public inline fun listUsersRequest(block: easylab.v1.ListUsersRequestKt.Dsl.() -> kotlin.Unit): easylab.v1.Easylab.ListUsersRequest =
  easylab.v1.ListUsersRequestKt.Dsl._create(easylab.v1.Easylab.ListUsersRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easylab.v1.ListUsersRequest`
 */
public object ListUsersRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: easylab.v1.Easylab.ListUsersRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: easylab.v1.Easylab.ListUsersRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): easylab.v1.Easylab.ListUsersRequest = _builder.build()
  }
}
public inline fun easylab.v1.Easylab.ListUsersRequest.copy(block: `easylab.v1`.ListUsersRequestKt.Dsl.() -> kotlin.Unit): easylab.v1.Easylab.ListUsersRequest =
  `easylab.v1`.ListUsersRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

