// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package easylab.v1;

@kotlin.jvm.JvmName("-initializelistReviewsResponse")
public inline fun listReviewsResponse(block: easylab.v1.ListReviewsResponseKt.Dsl.() -> kotlin.Unit): easylab.v1.Easylab.ListReviewsResponse =
  easylab.v1.ListReviewsResponseKt.Dsl._create(easylab.v1.Easylab.ListReviewsResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easylab.v1.ListReviewsResponse`
 */
public object ListReviewsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: easylab.v1.Easylab.ListReviewsResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: easylab.v1.Easylab.ListReviewsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): easylab.v1.Easylab.ListReviewsResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ReviewsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .easylab.v1.MergeReview reviews = 1 [json_name = "reviews"];`
     */
     public val reviews: com.google.protobuf.kotlin.DslList<easylab.v1.Easylab.MergeReview, ReviewsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.reviewsList
      )
    /**
     * `repeated .easylab.v1.MergeReview reviews = 1 [json_name = "reviews"];`
     * @param value The reviews to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addReviews")
    public fun com.google.protobuf.kotlin.DslList<easylab.v1.Easylab.MergeReview, ReviewsProxy>.add(value: easylab.v1.Easylab.MergeReview) {
      _builder.addReviews(value)
    }
    /**
     * `repeated .easylab.v1.MergeReview reviews = 1 [json_name = "reviews"];`
     * @param value The reviews to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignReviews")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<easylab.v1.Easylab.MergeReview, ReviewsProxy>.plusAssign(value: easylab.v1.Easylab.MergeReview) {
      add(value)
    }
    /**
     * `repeated .easylab.v1.MergeReview reviews = 1 [json_name = "reviews"];`
     * @param values The reviews to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllReviews")
    public fun com.google.protobuf.kotlin.DslList<easylab.v1.Easylab.MergeReview, ReviewsProxy>.addAll(values: kotlin.collections.Iterable<easylab.v1.Easylab.MergeReview>) {
      _builder.addAllReviews(values)
    }
    /**
     * `repeated .easylab.v1.MergeReview reviews = 1 [json_name = "reviews"];`
     * @param values The reviews to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllReviews")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<easylab.v1.Easylab.MergeReview, ReviewsProxy>.plusAssign(values: kotlin.collections.Iterable<easylab.v1.Easylab.MergeReview>) {
      addAll(values)
    }
    /**
     * `repeated .easylab.v1.MergeReview reviews = 1 [json_name = "reviews"];`
     * @param index The index to set the value at.
     * @param value The reviews to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setReviews")
    public operator fun com.google.protobuf.kotlin.DslList<easylab.v1.Easylab.MergeReview, ReviewsProxy>.set(index: kotlin.Int, value: easylab.v1.Easylab.MergeReview) {
      _builder.setReviews(index, value)
    }
    /**
     * `repeated .easylab.v1.MergeReview reviews = 1 [json_name = "reviews"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearReviews")
    public fun com.google.protobuf.kotlin.DslList<easylab.v1.Easylab.MergeReview, ReviewsProxy>.clear() {
      _builder.clearReviews()
    }
  }
}
public inline fun easylab.v1.Easylab.ListReviewsResponse.copy(block: `easylab.v1`.ListReviewsResponseKt.Dsl.() -> kotlin.Unit): easylab.v1.Easylab.ListReviewsResponse =
  `easylab.v1`.ListReviewsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

