// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto
// Protobuf Java Version: 4.36.1

package com.easylab.v1;

/**
 * Protobuf type {@code easylab.v1.ListReleasesResponse}
 */
@com.google.protobuf.Generated
public  final class ListReleasesResponse extends
    com.google.protobuf.GeneratedMessageLite<
        ListReleasesResponse, ListReleasesResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:easylab.v1.ListReleasesResponse)
    ListReleasesResponseOrBuilder {
  private ListReleasesResponse() {
    releases_ = emptyProtobufList();
  }
  public static final int RELEASES_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<com.easylab.v1.ReleaseView> releases_;
  /**
   * <code>repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];</code>
   */
  @java.lang.Override
  public java.util.List<com.easylab.v1.ReleaseView> getReleasesList() {
    return releases_;
  }
  /**
   * <code>repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];</code>
   */
  public java.util.List<? extends com.easylab.v1.ReleaseViewOrBuilder> 
      getReleasesOrBuilderList() {
    return releases_;
  }
  /**
   * <code>repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];</code>
   */
  @java.lang.Override
  public int getReleasesCount() {
    return releases_.size();
  }
  /**
   * <code>repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];</code>
   */
  @java.lang.Override
  public com.easylab.v1.ReleaseView getReleases(int index) {
    return releases_.get(index);
  }
  /**
   * <code>repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];</code>
   */
  public com.easylab.v1.ReleaseViewOrBuilder getReleasesOrBuilder(
      int index) {
    return releases_.get(index);
  }
  private void ensureReleasesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.easylab.v1.ReleaseView> tmp = releases_;
    if (!tmp.isModifiable()) {
      releases_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];</code>
   */
  private void setReleases(
      int index, com.easylab.v1.ReleaseView value) {
    java.util.Objects.requireNonNull(value);
    ensureReleasesIsMutable();
    releases_.set(index, value);
  }
  /**
   * <code>repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];</code>
   */
  private void addReleases(com.easylab.v1.ReleaseView value) {
    java.util.Objects.requireNonNull(value);
    ensureReleasesIsMutable();
    releases_.add(value);
  }
  /**
   * <code>repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];</code>
   */
  private void addReleases(
      int index, com.easylab.v1.ReleaseView value) {
    java.util.Objects.requireNonNull(value);
    ensureReleasesIsMutable();
    releases_.add(index, value);
  }
  /**
   * <code>repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];</code>
   */
  private void addAllReleases(
      java.lang.Iterable<? extends com.easylab.v1.ReleaseView> values) {
    ensureReleasesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, releases_);
  }
  /**
   * <code>repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];</code>
   */
  private void clearReleases() {
    releases_ = emptyProtobufList();
  }
  /**
   * <code>repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];</code>
   */
  private void removeReleases(int index) {
    ensureReleasesIsMutable();
    releases_.remove(index);
  }

  public static com.easylab.v1.ListReleasesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.ListReleasesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.ListReleasesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.ListReleasesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.ListReleasesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.ListReleasesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.ListReleasesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easylab.v1.ListReleasesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.easylab.v1.ListReleasesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.easylab.v1.ListReleasesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.easylab.v1.ListReleasesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easylab.v1.ListReleasesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.easylab.v1.ListReleasesResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code easylab.v1.ListReleasesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.easylab.v1.ListReleasesResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:easylab.v1.ListReleasesResponse)
      com.easylab.v1.ListReleasesResponseOrBuilder {
    // Construct using com.easylab.v1.ListReleasesResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];</code>
     */
    @java.lang.Override
    public java.util.List<com.easylab.v1.ReleaseView> getReleasesList() {
      return java.util.Collections.unmodifiableList(
          instance.getReleasesList());
    }
    /**
     * <code>repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];</code>
     */
    @java.lang.Override
    public int getReleasesCount() {
      return instance.getReleasesCount();
    }/**
     * <code>repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];</code>
     */
    @java.lang.Override
    public com.easylab.v1.ReleaseView getReleases(int index) {
      return instance.getReleases(index);
    }
    /**
     * <code>repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];</code>
     */
    public Builder setReleases(
        int index, com.easylab.v1.ReleaseView value) {
      copyOnWrite();
      instance.setReleases(index, value);
      return this;
    }
    /**
     * <code>repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];</code>
     */
    public Builder setReleases(
        int index, com.easylab.v1.ReleaseView.Builder builderForValue) {
      copyOnWrite();
      instance.setReleases(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];</code>
     */
    public Builder addReleases(com.easylab.v1.ReleaseView value) {
      copyOnWrite();
      instance.addReleases(value);
      return this;
    }
    /**
     * <code>repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];</code>
     */
    public Builder addReleases(
        int index, com.easylab.v1.ReleaseView value) {
      copyOnWrite();
      instance.addReleases(index, value);
      return this;
    }
    /**
     * <code>repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];</code>
     */
    public Builder addReleases(
        com.easylab.v1.ReleaseView.Builder builderForValue) {
      copyOnWrite();
      instance.addReleases(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];</code>
     */
    public Builder addReleases(
        int index, com.easylab.v1.ReleaseView.Builder builderForValue) {
      copyOnWrite();
      instance.addReleases(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];</code>
     */
    public Builder addAllReleases(
        java.lang.Iterable<? extends com.easylab.v1.ReleaseView> values) {
      copyOnWrite();
      instance.addAllReleases(values);
      return this;
    }
    /**
     * <code>repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];</code>
     */
    public Builder clearReleases() {
      copyOnWrite();
      instance.clearReleases();
      return this;
    }
    /**
     * <code>repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];</code>
     */
    public Builder removeReleases(int index) {
      copyOnWrite();
      instance.removeReleases(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:easylab.v1.ListReleasesResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.easylab.v1.ListReleasesResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "releases_",
            com.easylab.v1.ReleaseView.class,
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.easylab.v1.ListReleasesResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.easylab.v1.ListReleasesResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.easylab.v1.ListReleasesResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:easylab.v1.ListReleasesResponse)
  private static final com.easylab.v1.ListReleasesResponse DEFAULT_INSTANCE;
  static {
    ListReleasesResponse defaultInstance = new ListReleasesResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ListReleasesResponse.class, defaultInstance);
  }

  public static com.easylab.v1.ListReleasesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ListReleasesResponse> PARSER;

  public static com.google.protobuf.Parser<ListReleasesResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

