// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto
// Protobuf Java Version: 4.36.1

package com.easylab.v1;

@com.google.protobuf.Generated
public interface ListJobsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:easylab.v1.ListJobsRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string sandbox = 1 [json_name = "sandbox"];</code>
   * @return The sandbox.
   */
  java.lang.String getSandbox();
  /**
   * <code>string sandbox = 1 [json_name = "sandbox"];</code>
   * @return The bytes for sandbox.
   */
  com.google.protobuf.ByteString
      getSandboxBytes();

  /**
   * <code>int32 limit = 2 [json_name = "limit"];</code>
   * @return The limit.
   */
  int getLimit();
}
