// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easylab.v1;

@kotlin.jvm.JvmName("-initializelistPackageTypesResponse")
public inline fun listPackageTypesResponse(block: com.easylab.v1.ListPackageTypesResponseKt.Dsl.() -> kotlin.Unit): com.easylab.v1.ListPackageTypesResponse =
  com.easylab.v1.ListPackageTypesResponseKt.Dsl._create(com.easylab.v1.ListPackageTypesResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easylab.v1.ListPackageTypesResponse`
 */
public object ListPackageTypesResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easylab.v1.ListPackageTypesResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easylab.v1.ListPackageTypesResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easylab.v1.ListPackageTypesResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class PackagesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .easylab.v1.PackageTypeEntry packages = 1 [json_name = "packages"];`
     */
     public val packages: com.google.protobuf.kotlin.DslList<com.easylab.v1.PackageTypeEntry, PackagesProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.packagesList
      )
    /**
     * `repeated .easylab.v1.PackageTypeEntry packages = 1 [json_name = "packages"];`
     * @param value The packages to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addPackages")
    public fun com.google.protobuf.kotlin.DslList<com.easylab.v1.PackageTypeEntry, PackagesProxy>.add(value: com.easylab.v1.PackageTypeEntry) {
      _builder.addPackages(value)
    }
    /**
     * `repeated .easylab.v1.PackageTypeEntry packages = 1 [json_name = "packages"];`
     * @param value The packages to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignPackages")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.easylab.v1.PackageTypeEntry, PackagesProxy>.plusAssign(value: com.easylab.v1.PackageTypeEntry) {
      add(value)
    }
    /**
     * `repeated .easylab.v1.PackageTypeEntry packages = 1 [json_name = "packages"];`
     * @param values The packages to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllPackages")
    public fun com.google.protobuf.kotlin.DslList<com.easylab.v1.PackageTypeEntry, PackagesProxy>.addAll(values: kotlin.collections.Iterable<com.easylab.v1.PackageTypeEntry>) {
      _builder.addAllPackages(values)
    }
    /**
     * `repeated .easylab.v1.PackageTypeEntry packages = 1 [json_name = "packages"];`
     * @param values The packages to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllPackages")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.easylab.v1.PackageTypeEntry, PackagesProxy>.plusAssign(values: kotlin.collections.Iterable<com.easylab.v1.PackageTypeEntry>) {
      addAll(values)
    }
    /**
     * `repeated .easylab.v1.PackageTypeEntry packages = 1 [json_name = "packages"];`
     * @param index The index to set the value at.
     * @param value The packages to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setPackages")
    public operator fun com.google.protobuf.kotlin.DslList<com.easylab.v1.PackageTypeEntry, PackagesProxy>.set(index: kotlin.Int, value: com.easylab.v1.PackageTypeEntry) {
      _builder.setPackages(index, value)
    }
    /**
     * `repeated .easylab.v1.PackageTypeEntry packages = 1 [json_name = "packages"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearPackages")
    public fun com.google.protobuf.kotlin.DslList<com.easylab.v1.PackageTypeEntry, PackagesProxy>.clear() {
      _builder.clearPackages()
    }
  }
}
public inline fun com.easylab.v1.ListPackageTypesResponse.copy(block: `com.easylab.v1`.ListPackageTypesResponseKt.Dsl.() -> kotlin.Unit): com.easylab.v1.ListPackageTypesResponse =
  `com.easylab.v1`.ListPackageTypesResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

