// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto
// Protobuf Java Version: 4.36.1

package com.easylab.v1;

/**
 * Protobuf type {@code easylab.v1.ListRunsRequest}
 */
@com.google.protobuf.Generated
public  final class ListRunsRequest extends
    com.google.protobuf.GeneratedMessageLite<
        ListRunsRequest, ListRunsRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:easylab.v1.ListRunsRequest)
    ListRunsRequestOrBuilder {
  private ListRunsRequest() {
    workflowId_ = "";
  }
  public static final int WORKFLOW_ID_FIELD_NUMBER = 1;
  private java.lang.String workflowId_;
  /**
   * <code>string workflow_id = 1 [json_name = "workflowId"];</code>
   * @return The workflowId.
   */
  @java.lang.Override
  public java.lang.String getWorkflowId() {
    return workflowId_;
  }
  /**
   * <code>string workflow_id = 1 [json_name = "workflowId"];</code>
   * @return The bytes for workflowId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWorkflowIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(workflowId_);
  }
  /**
   * <code>string workflow_id = 1 [json_name = "workflowId"];</code>
   * @param value The workflowId to set.
   */
  private void setWorkflowId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    workflowId_ = value;
  }
  /**
   * <code>string workflow_id = 1 [json_name = "workflowId"];</code>
   */
  private void clearWorkflowId() {

    workflowId_ = getDefaultInstance().getWorkflowId();
  }
  /**
   * <code>string workflow_id = 1 [json_name = "workflowId"];</code>
   * @param value The bytes for workflowId to set.
   */
  private void setWorkflowIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    workflowId_ = value.toStringUtf8();

  }

  public static com.easylab.v1.ListRunsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.ListRunsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.ListRunsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.ListRunsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.ListRunsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.ListRunsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.ListRunsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easylab.v1.ListRunsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.easylab.v1.ListRunsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.easylab.v1.ListRunsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.easylab.v1.ListRunsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easylab.v1.ListRunsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.easylab.v1.ListRunsRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code easylab.v1.ListRunsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.easylab.v1.ListRunsRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:easylab.v1.ListRunsRequest)
      com.easylab.v1.ListRunsRequestOrBuilder {
    // Construct using com.easylab.v1.ListRunsRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string workflow_id = 1 [json_name = "workflowId"];</code>
     * @return The workflowId.
     */
    @java.lang.Override
    public java.lang.String getWorkflowId() {
      return instance.getWorkflowId();
    }
    /**
     * <code>string workflow_id = 1 [json_name = "workflowId"];</code>
     * @return The bytes for workflowId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWorkflowIdBytes() {
      return instance.getWorkflowIdBytes();
    }
    /**
     * <code>string workflow_id = 1 [json_name = "workflowId"];</code>
     * @param value The workflowId to set.
     * @return This builder for chaining.
     */
    public Builder setWorkflowId(
        java.lang.String value) {
      copyOnWrite();
      instance.setWorkflowId(value);
      return this;
    }
    /**
     * <code>string workflow_id = 1 [json_name = "workflowId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearWorkflowId() {
      copyOnWrite();
      instance.clearWorkflowId();
      return this;
    }
    /**
     * <code>string workflow_id = 1 [json_name = "workflowId"];</code>
     * @param value The bytes for workflowId to set.
     * @return This builder for chaining.
     */
    public Builder setWorkflowIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setWorkflowIdBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:easylab.v1.ListRunsRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.easylab.v1.ListRunsRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "workflowId_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.easylab.v1.ListRunsRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.easylab.v1.ListRunsRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.easylab.v1.ListRunsRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:easylab.v1.ListRunsRequest)
  private static final com.easylab.v1.ListRunsRequest DEFAULT_INSTANCE;
  static {
    ListRunsRequest defaultInstance = new ListRunsRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ListRunsRequest.class, defaultInstance);
  }

  public static com.easylab.v1.ListRunsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ListRunsRequest> PARSER;

  public static com.google.protobuf.Parser<ListRunsRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

