// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto
// Protobuf Java Version: 4.36.1

package com.easylab.v1;

/**
 * Protobuf type {@code easylab.v1.ListUsersResponse}
 */
@com.google.protobuf.Generated
public  final class ListUsersResponse extends
    com.google.protobuf.GeneratedMessageLite<
        ListUsersResponse, ListUsersResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:easylab.v1.ListUsersResponse)
    ListUsersResponseOrBuilder {
  private ListUsersResponse() {
    users_ = emptyProtobufList();
  }
  public static final int USERS_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<com.easylab.v1.User> users_;
  /**
   * <code>repeated .easylab.v1.User users = 1 [json_name = "users"];</code>
   */
  @java.lang.Override
  public java.util.List<com.easylab.v1.User> getUsersList() {
    return users_;
  }
  /**
   * <code>repeated .easylab.v1.User users = 1 [json_name = "users"];</code>
   */
  public java.util.List<? extends com.easylab.v1.UserOrBuilder> 
      getUsersOrBuilderList() {
    return users_;
  }
  /**
   * <code>repeated .easylab.v1.User users = 1 [json_name = "users"];</code>
   */
  @java.lang.Override
  public int getUsersCount() {
    return users_.size();
  }
  /**
   * <code>repeated .easylab.v1.User users = 1 [json_name = "users"];</code>
   */
  @java.lang.Override
  public com.easylab.v1.User getUsers(int index) {
    return users_.get(index);
  }
  /**
   * <code>repeated .easylab.v1.User users = 1 [json_name = "users"];</code>
   */
  public com.easylab.v1.UserOrBuilder getUsersOrBuilder(
      int index) {
    return users_.get(index);
  }
  private void ensureUsersIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.easylab.v1.User> tmp = users_;
    if (!tmp.isModifiable()) {
      users_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .easylab.v1.User users = 1 [json_name = "users"];</code>
   */
  private void setUsers(
      int index, com.easylab.v1.User value) {
    java.util.Objects.requireNonNull(value);
    ensureUsersIsMutable();
    users_.set(index, value);
  }
  /**
   * <code>repeated .easylab.v1.User users = 1 [json_name = "users"];</code>
   */
  private void addUsers(com.easylab.v1.User value) {
    java.util.Objects.requireNonNull(value);
    ensureUsersIsMutable();
    users_.add(value);
  }
  /**
   * <code>repeated .easylab.v1.User users = 1 [json_name = "users"];</code>
   */
  private void addUsers(
      int index, com.easylab.v1.User value) {
    java.util.Objects.requireNonNull(value);
    ensureUsersIsMutable();
    users_.add(index, value);
  }
  /**
   * <code>repeated .easylab.v1.User users = 1 [json_name = "users"];</code>
   */
  private void addAllUsers(
      java.lang.Iterable<? extends com.easylab.v1.User> values) {
    ensureUsersIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, users_);
  }
  /**
   * <code>repeated .easylab.v1.User users = 1 [json_name = "users"];</code>
   */
  private void clearUsers() {
    users_ = emptyProtobufList();
  }
  /**
   * <code>repeated .easylab.v1.User users = 1 [json_name = "users"];</code>
   */
  private void removeUsers(int index) {
    ensureUsersIsMutable();
    users_.remove(index);
  }

  public static com.easylab.v1.ListUsersResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.ListUsersResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.ListUsersResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.ListUsersResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.ListUsersResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.ListUsersResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.ListUsersResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easylab.v1.ListUsersResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.easylab.v1.ListUsersResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.easylab.v1.ListUsersResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.easylab.v1.ListUsersResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easylab.v1.ListUsersResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.easylab.v1.ListUsersResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code easylab.v1.ListUsersResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.easylab.v1.ListUsersResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:easylab.v1.ListUsersResponse)
      com.easylab.v1.ListUsersResponseOrBuilder {
    // Construct using com.easylab.v1.ListUsersResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated .easylab.v1.User users = 1 [json_name = "users"];</code>
     */
    @java.lang.Override
    public java.util.List<com.easylab.v1.User> getUsersList() {
      return java.util.Collections.unmodifiableList(
          instance.getUsersList());
    }
    /**
     * <code>repeated .easylab.v1.User users = 1 [json_name = "users"];</code>
     */
    @java.lang.Override
    public int getUsersCount() {
      return instance.getUsersCount();
    }/**
     * <code>repeated .easylab.v1.User users = 1 [json_name = "users"];</code>
     */
    @java.lang.Override
    public com.easylab.v1.User getUsers(int index) {
      return instance.getUsers(index);
    }
    /**
     * <code>repeated .easylab.v1.User users = 1 [json_name = "users"];</code>
     */
    public Builder setUsers(
        int index, com.easylab.v1.User value) {
      copyOnWrite();
      instance.setUsers(index, value);
      return this;
    }
    /**
     * <code>repeated .easylab.v1.User users = 1 [json_name = "users"];</code>
     */
    public Builder setUsers(
        int index, com.easylab.v1.User.Builder builderForValue) {
      copyOnWrite();
      instance.setUsers(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .easylab.v1.User users = 1 [json_name = "users"];</code>
     */
    public Builder addUsers(com.easylab.v1.User value) {
      copyOnWrite();
      instance.addUsers(value);
      return this;
    }
    /**
     * <code>repeated .easylab.v1.User users = 1 [json_name = "users"];</code>
     */
    public Builder addUsers(
        int index, com.easylab.v1.User value) {
      copyOnWrite();
      instance.addUsers(index, value);
      return this;
    }
    /**
     * <code>repeated .easylab.v1.User users = 1 [json_name = "users"];</code>
     */
    public Builder addUsers(
        com.easylab.v1.User.Builder builderForValue) {
      copyOnWrite();
      instance.addUsers(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .easylab.v1.User users = 1 [json_name = "users"];</code>
     */
    public Builder addUsers(
        int index, com.easylab.v1.User.Builder builderForValue) {
      copyOnWrite();
      instance.addUsers(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .easylab.v1.User users = 1 [json_name = "users"];</code>
     */
    public Builder addAllUsers(
        java.lang.Iterable<? extends com.easylab.v1.User> values) {
      copyOnWrite();
      instance.addAllUsers(values);
      return this;
    }
    /**
     * <code>repeated .easylab.v1.User users = 1 [json_name = "users"];</code>
     */
    public Builder clearUsers() {
      copyOnWrite();
      instance.clearUsers();
      return this;
    }
    /**
     * <code>repeated .easylab.v1.User users = 1 [json_name = "users"];</code>
     */
    public Builder removeUsers(int index) {
      copyOnWrite();
      instance.removeUsers(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:easylab.v1.ListUsersResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.easylab.v1.ListUsersResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "users_",
            com.easylab.v1.User.class,
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0001\u0000\u0001\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.easylab.v1.ListUsersResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.easylab.v1.ListUsersResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.easylab.v1.ListUsersResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:easylab.v1.ListUsersResponse)
  private static final com.easylab.v1.ListUsersResponse DEFAULT_INSTANCE;
  static {
    ListUsersResponse defaultInstance = new ListUsersResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ListUsersResponse.class, defaultInstance);
  }

  public static com.easylab.v1.ListUsersResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ListUsersResponse> PARSER;

  public static com.google.protobuf.Parser<ListUsersResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

