// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easylab.v1;

@kotlin.jvm.JvmName("-initializelistReleasesResponse")
public inline fun listReleasesResponse(block: com.easylab.v1.ListReleasesResponseKt.Dsl.() -> kotlin.Unit): com.easylab.v1.ListReleasesResponse =
  com.easylab.v1.ListReleasesResponseKt.Dsl._create(com.easylab.v1.ListReleasesResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easylab.v1.ListReleasesResponse`
 */
public object ListReleasesResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easylab.v1.ListReleasesResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easylab.v1.ListReleasesResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easylab.v1.ListReleasesResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ReleasesProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];`
     */
     public val releases: com.google.protobuf.kotlin.DslList<com.easylab.v1.ReleaseView, ReleasesProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.releasesList
      )
    /**
     * `repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];`
     * @param value The releases to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addReleases")
    public fun com.google.protobuf.kotlin.DslList<com.easylab.v1.ReleaseView, ReleasesProxy>.add(value: com.easylab.v1.ReleaseView) {
      _builder.addReleases(value)
    }
    /**
     * `repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];`
     * @param value The releases to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignReleases")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.easylab.v1.ReleaseView, ReleasesProxy>.plusAssign(value: com.easylab.v1.ReleaseView) {
      add(value)
    }
    /**
     * `repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];`
     * @param values The releases to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllReleases")
    public fun com.google.protobuf.kotlin.DslList<com.easylab.v1.ReleaseView, ReleasesProxy>.addAll(values: kotlin.collections.Iterable<com.easylab.v1.ReleaseView>) {
      _builder.addAllReleases(values)
    }
    /**
     * `repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];`
     * @param values The releases to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllReleases")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.easylab.v1.ReleaseView, ReleasesProxy>.plusAssign(values: kotlin.collections.Iterable<com.easylab.v1.ReleaseView>) {
      addAll(values)
    }
    /**
     * `repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];`
     * @param index The index to set the value at.
     * @param value The releases to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setReleases")
    public operator fun com.google.protobuf.kotlin.DslList<com.easylab.v1.ReleaseView, ReleasesProxy>.set(index: kotlin.Int, value: com.easylab.v1.ReleaseView) {
      _builder.setReleases(index, value)
    }
    /**
     * `repeated .easylab.v1.ReleaseView releases = 1 [json_name = "releases"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearReleases")
    public fun com.google.protobuf.kotlin.DslList<com.easylab.v1.ReleaseView, ReleasesProxy>.clear() {
      _builder.clearReleases()
    }
  }
}
public inline fun com.easylab.v1.ListReleasesResponse.copy(block: `com.easylab.v1`.ListReleasesResponseKt.Dsl.() -> kotlin.Unit): com.easylab.v1.ListReleasesResponse =
  `com.easylab.v1`.ListReleasesResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

