// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: easylab/v1/easylab.proto
//
package easylab.v1

import com.connectrpc.Headers
import com.connectrpc.MethodSpec
import com.connectrpc.ProtocolClientInterface
import com.connectrpc.ResponseMessage
import com.connectrpc.StreamType

/**
 *  OpsService covers the dev/deploy surface (services, sandboxes, builds).
 */
public class OpsServiceClient(
  private val client: ProtocolClientInterface,
) : OpsServiceClientInterface {
  override suspend fun opsStatus(request: Easylab.OpsStatusRequest, headers: Headers): ResponseMessage<Easylab.OpsStatusResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/OpsStatus",
      easylab.v1.Easylab.OpsStatusRequest::class,
      easylab.v1.Easylab.OpsStatusResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun listNamespaces(request: Easylab.ListNamespacesRequest, headers: Headers): ResponseMessage<Easylab.ListNamespacesResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/ListNamespaces",
      easylab.v1.Easylab.ListNamespacesRequest::class,
      easylab.v1.Easylab.ListNamespacesResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun listServices(request: Easylab.ListServicesRequest, headers: Headers): ResponseMessage<Easylab.ListServicesResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/ListServices",
      easylab.v1.Easylab.ListServicesRequest::class,
      easylab.v1.Easylab.ListServicesResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun getService(request: Easylab.GetServiceRequest, headers: Headers): ResponseMessage<Easylab.GetServiceResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/GetService",
      easylab.v1.Easylab.GetServiceRequest::class,
      easylab.v1.Easylab.GetServiceResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun launchService(request: Easylab.LaunchServiceRequest, headers: Headers): ResponseMessage<Easylab.LaunchServiceResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/LaunchService",
      easylab.v1.Easylab.LaunchServiceRequest::class,
      easylab.v1.Easylab.LaunchServiceResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun deleteService(request: Easylab.DeleteServiceRequest, headers: Headers): ResponseMessage<Easylab.DeleteServiceResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/DeleteService",
      easylab.v1.Easylab.DeleteServiceRequest::class,
      easylab.v1.Easylab.DeleteServiceResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun scaleService(request: Easylab.ScaleServiceRequest, headers: Headers): ResponseMessage<Easylab.ScaleServiceResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/ScaleService",
      easylab.v1.Easylab.ScaleServiceRequest::class,
      easylab.v1.Easylab.ScaleServiceResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun sandboxExec(request: Easylab.SandboxExecRequest, headers: Headers): ResponseMessage<Easylab.SandboxExecResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/SandboxExec",
      easylab.v1.Easylab.SandboxExecRequest::class,
      easylab.v1.Easylab.SandboxExecResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun sandboxRead(request: Easylab.SandboxReadRequest, headers: Headers): ResponseMessage<Easylab.SandboxReadResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/SandboxRead",
      easylab.v1.Easylab.SandboxReadRequest::class,
      easylab.v1.Easylab.SandboxReadResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun sandboxWrite(request: Easylab.SandboxWriteRequest, headers: Headers): ResponseMessage<Easylab.SandboxWriteResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/SandboxWrite",
      easylab.v1.Easylab.SandboxWriteRequest::class,
      easylab.v1.Easylab.SandboxWriteResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun sandboxJobKill(request: Easylab.SandboxJobKillRequest, headers: Headers): ResponseMessage<Easylab.SandboxJobKillResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/SandboxJobKill",
      easylab.v1.Easylab.SandboxJobKillRequest::class,
      easylab.v1.Easylab.SandboxJobKillResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun sync(request: Easylab.SyncRequest, headers: Headers): ResponseMessage<Easylab.SyncResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/Sync",
      easylab.v1.Easylab.SyncRequest::class,
      easylab.v1.Easylab.SyncResponse::class,
      StreamType.UNARY,
    ),
  )

}
