// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: easylab/v1/easylab.proto
//
package com.easylab.v1

import com.connectrpc.Headers
import com.connectrpc.MethodSpec
import com.connectrpc.ProtocolClientInterface
import com.connectrpc.ResponseMessage
import com.connectrpc.ServerOnlyStreamInterface
import com.connectrpc.StreamType

/**
 *  OpsService covers the dev/deploy surface (services, sandboxes, builds).
 */
public class OpsServiceClient(
  private val client: ProtocolClientInterface,
) : OpsServiceClientInterface {
  override suspend fun opsStatus(request: OpsStatusRequest, headers: Headers): ResponseMessage<OpsStatusResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/OpsStatus",
      com.easylab.v1.OpsStatusRequest::class,
      com.easylab.v1.OpsStatusResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun listNamespaces(request: ListNamespacesRequest, headers: Headers): ResponseMessage<ListNamespacesResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/ListNamespaces",
      com.easylab.v1.ListNamespacesRequest::class,
      com.easylab.v1.ListNamespacesResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun listServices(request: ListServicesRequest, headers: Headers): ResponseMessage<ListServicesResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/ListServices",
      com.easylab.v1.ListServicesRequest::class,
      com.easylab.v1.ListServicesResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun getService(request: GetServiceRequest, headers: Headers): ResponseMessage<GetServiceResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/GetService",
      com.easylab.v1.GetServiceRequest::class,
      com.easylab.v1.GetServiceResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun launchService(request: LaunchServiceRequest, headers: Headers): ResponseMessage<LaunchServiceResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/LaunchService",
      com.easylab.v1.LaunchServiceRequest::class,
      com.easylab.v1.LaunchServiceResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun deleteService(request: DeleteServiceRequest, headers: Headers): ResponseMessage<DeleteServiceResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/DeleteService",
      com.easylab.v1.DeleteServiceRequest::class,
      com.easylab.v1.DeleteServiceResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun scaleService(request: ScaleServiceRequest, headers: Headers): ResponseMessage<ScaleServiceResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/ScaleService",
      com.easylab.v1.ScaleServiceRequest::class,
      com.easylab.v1.ScaleServiceResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun sandboxExec(request: SandboxExecRequest, headers: Headers): ResponseMessage<SandboxExecResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/SandboxExec",
      com.easylab.v1.SandboxExecRequest::class,
      com.easylab.v1.SandboxExecResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun sandboxRead(request: SandboxReadRequest, headers: Headers): ResponseMessage<SandboxReadResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/SandboxRead",
      com.easylab.v1.SandboxReadRequest::class,
      com.easylab.v1.SandboxReadResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun sandboxWrite(request: SandboxWriteRequest, headers: Headers): ResponseMessage<SandboxWriteResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/SandboxWrite",
      com.easylab.v1.SandboxWriteRequest::class,
      com.easylab.v1.SandboxWriteResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun sandboxJobKill(request: SandboxJobKillRequest, headers: Headers): ResponseMessage<SandboxJobKillResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/SandboxJobKill",
      com.easylab.v1.SandboxJobKillRequest::class,
      com.easylab.v1.SandboxJobKillResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun listTasks(request: ListTasksRequest, headers: Headers): ResponseMessage<ListTasksResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/ListTasks",
      com.easylab.v1.ListTasksRequest::class,
      com.easylab.v1.ListTasksResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun getTask(request: GetTaskRequest, headers: Headers): ResponseMessage<GetTaskResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/GetTask",
      com.easylab.v1.GetTaskRequest::class,
      com.easylab.v1.GetTaskResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun build(request: BuildRequest, headers: Headers): ResponseMessage<BuildResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/Build",
      com.easylab.v1.BuildRequest::class,
      com.easylab.v1.BuildResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun run(request: RunRequest, headers: Headers): ResponseMessage<RunResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/Run",
      com.easylab.v1.RunRequest::class,
      com.easylab.v1.RunResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun taskLog(headers: Headers): ServerOnlyStreamInterface<TaskLogRequest, TaskLogResponse> = client.serverStream(
    headers,
    MethodSpec(
    "easylab.v1.OpsService/TaskLog",
      com.easylab.v1.TaskLogRequest::class,
      com.easylab.v1.TaskLogResponse::class,
      StreamType.SERVER,
    ),
  )


  override suspend fun sync(request: SyncRequest, headers: Headers): ResponseMessage<SyncResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.OpsService/Sync",
      com.easylab.v1.SyncRequest::class,
      com.easylab.v1.SyncResponse::class,
      StreamType.UNARY,
    ),
  )

}
