// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easylab.v1;

@kotlin.jvm.JvmName("-initializepackageVersionsRequest")
public inline fun packageVersionsRequest(block: com.easylab.v1.PackageVersionsRequestKt.Dsl.() -> kotlin.Unit): com.easylab.v1.PackageVersionsRequest =
  com.easylab.v1.PackageVersionsRequestKt.Dsl._create(com.easylab.v1.PackageVersionsRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easylab.v1.PackageVersionsRequest`
 */
public object PackageVersionsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easylab.v1.PackageVersionsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easylab.v1.PackageVersionsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easylab.v1.PackageVersionsRequest = _builder.build()

    /**
     * `string type = 1 [json_name = "type"];`
     */
    public var type: kotlin.String
      @kotlin.jvm.JvmName("getType")
        get() = _builder.type
      @kotlin.jvm.JvmName("setType")
        set(value) {
        _builder.type = value
      }
    /**
     * `string type = 1 [json_name = "type"];`
     */
    public fun clearType() {
      _builder.clearType()
    }

    /**
     * `string name = 2 [json_name = "name"];`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 2 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }
  }
}
public inline fun com.easylab.v1.PackageVersionsRequest.copy(block: `com.easylab.v1`.PackageVersionsRequestKt.Dsl.() -> kotlin.Unit): com.easylab.v1.PackageVersionsRequest =
  `com.easylab.v1`.PackageVersionsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

