// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easylab.v1;

@kotlin.jvm.JvmName("-initializeportSpec")
public inline fun portSpec(block: com.easylab.v1.PortSpecKt.Dsl.() -> kotlin.Unit): com.easylab.v1.PortSpec =
  com.easylab.v1.PortSpecKt.Dsl._create(com.easylab.v1.PortSpec.newBuilder()).apply { block() }._build()
/**
 * ```
 * PortSpec maps a container port to a published service port.
 * ```
 *
 * Protobuf type `easylab.v1.PortSpec`
 */
public object PortSpecKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easylab.v1.PortSpec.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easylab.v1.PortSpec.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easylab.v1.PortSpec = _builder.build()

    /**
     * `int32 container = 1 [json_name = "container"];`
     */
    public var container: kotlin.Int
      @kotlin.jvm.JvmName("getContainer")
        get() = _builder.container
      @kotlin.jvm.JvmName("setContainer")
        set(value) {
        _builder.container = value
      }
    /**
     * `int32 container = 1 [json_name = "container"];`
     */
    public fun clearContainer() {
      _builder.clearContainer()
    }

    /**
     * `int32 service = 2 [json_name = "service"];`
     */
    public var service: kotlin.Int
      @kotlin.jvm.JvmName("getService")
        get() = _builder.service
      @kotlin.jvm.JvmName("setService")
        set(value) {
        _builder.service = value
      }
    /**
     * `int32 service = 2 [json_name = "service"];`
     */
    public fun clearService() {
      _builder.clearService()
    }
  }
}
public inline fun com.easylab.v1.PortSpec.copy(block: `com.easylab.v1`.PortSpecKt.Dsl.() -> kotlin.Unit): com.easylab.v1.PortSpec =
  `com.easylab.v1`.PortSpecKt.Dsl._create(this.toBuilder()).apply { block() }._build()

