// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto
// Protobuf Java Version: 4.36.1

package com.easylab.v1;

/**
 * Protobuf type {@code easylab.v1.Produce}
 */
@com.google.protobuf.Generated
public  final class Produce extends
    com.google.protobuf.GeneratedMessageLite<
        Produce, Produce.Builder> implements
    // @@protoc_insertion_point(message_implements:easylab.v1.Produce)
    ProduceOrBuilder {
  private Produce() {
    action_ = "";
    context_ = "";
    dockerfile_ = "";
    tag_ = "";
    path_ = "";
    destination_ = "";
    ref_ = "";
    protocol_ = "";
    name_ = "";
    version_ = "";
    file_ = "";
    containerfile_ = "";
  }
  public static final int ACTION_FIELD_NUMBER = 1;
  private java.lang.String action_;
  /**
   * <pre>
   * oci-build | artifact-upload | publish-protocol
   * </pre>
   *
   * <code>string action = 1 [json_name = "action"];</code>
   * @return The action.
   */
  @java.lang.Override
  public java.lang.String getAction() {
    return action_;
  }
  /**
   * <pre>
   * oci-build | artifact-upload | publish-protocol
   * </pre>
   *
   * <code>string action = 1 [json_name = "action"];</code>
   * @return The bytes for action.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(action_);
  }
  /**
   * <pre>
   * oci-build | artifact-upload | publish-protocol
   * </pre>
   *
   * <code>string action = 1 [json_name = "action"];</code>
   * @param value The action to set.
   */
  private void setAction(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    action_ = value;
  }
  /**
   * <pre>
   * oci-build | artifact-upload | publish-protocol
   * </pre>
   *
   * <code>string action = 1 [json_name = "action"];</code>
   */
  private void clearAction() {

    action_ = getDefaultInstance().getAction();
  }
  /**
   * <pre>
   * oci-build | artifact-upload | publish-protocol
   * </pre>
   *
   * <code>string action = 1 [json_name = "action"];</code>
   * @param value The bytes for action to set.
   */
  private void setActionBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    action_ = value.toStringUtf8();

  }

  public static final int CONTEXT_FIELD_NUMBER = 2;
  private java.lang.String context_;
  /**
   * <pre>
   * oci-build: build context (default workspace root)
   * </pre>
   *
   * <code>string context = 2 [json_name = "context"];</code>
   * @return The context.
   */
  @java.lang.Override
  public java.lang.String getContext() {
    return context_;
  }
  /**
   * <pre>
   * oci-build: build context (default workspace root)
   * </pre>
   *
   * <code>string context = 2 [json_name = "context"];</code>
   * @return The bytes for context.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContextBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(context_);
  }
  /**
   * <pre>
   * oci-build: build context (default workspace root)
   * </pre>
   *
   * <code>string context = 2 [json_name = "context"];</code>
   * @param value The context to set.
   */
  private void setContext(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    context_ = value;
  }
  /**
   * <pre>
   * oci-build: build context (default workspace root)
   * </pre>
   *
   * <code>string context = 2 [json_name = "context"];</code>
   */
  private void clearContext() {

    context_ = getDefaultInstance().getContext();
  }
  /**
   * <pre>
   * oci-build: build context (default workspace root)
   * </pre>
   *
   * <code>string context = 2 [json_name = "context"];</code>
   * @param value The bytes for context to set.
   */
  private void setContextBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    context_ = value.toStringUtf8();

  }

  public static final int DOCKERFILE_FIELD_NUMBER = 3;
  private java.lang.String dockerfile_;
  /**
   * <pre>
   * oci-build: Dockerfile path (default root/Dockerfile)
   * </pre>
   *
   * <code>string dockerfile = 3 [json_name = "dockerfile"];</code>
   * @return The dockerfile.
   */
  @java.lang.Override
  public java.lang.String getDockerfile() {
    return dockerfile_;
  }
  /**
   * <pre>
   * oci-build: Dockerfile path (default root/Dockerfile)
   * </pre>
   *
   * <code>string dockerfile = 3 [json_name = "dockerfile"];</code>
   * @return The bytes for dockerfile.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDockerfileBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(dockerfile_);
  }
  /**
   * <pre>
   * oci-build: Dockerfile path (default root/Dockerfile)
   * </pre>
   *
   * <code>string dockerfile = 3 [json_name = "dockerfile"];</code>
   * @param value The dockerfile to set.
   */
  private void setDockerfile(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    dockerfile_ = value;
  }
  /**
   * <pre>
   * oci-build: Dockerfile path (default root/Dockerfile)
   * </pre>
   *
   * <code>string dockerfile = 3 [json_name = "dockerfile"];</code>
   */
  private void clearDockerfile() {

    dockerfile_ = getDefaultInstance().getDockerfile();
  }
  /**
   * <pre>
   * oci-build: Dockerfile path (default root/Dockerfile)
   * </pre>
   *
   * <code>string dockerfile = 3 [json_name = "dockerfile"];</code>
   * @param value The bytes for dockerfile to set.
   */
  private void setDockerfileBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    dockerfile_ = value.toStringUtf8();

  }

  public static final int TAG_FIELD_NUMBER = 4;
  private java.lang.String tag_;
  /**
   * <pre>
   * oci-build: image tag
   * </pre>
   *
   * <code>string tag = 4 [json_name = "tag"];</code>
   * @return The tag.
   */
  @java.lang.Override
  public java.lang.String getTag() {
    return tag_;
  }
  /**
   * <pre>
   * oci-build: image tag
   * </pre>
   *
   * <code>string tag = 4 [json_name = "tag"];</code>
   * @return The bytes for tag.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTagBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(tag_);
  }
  /**
   * <pre>
   * oci-build: image tag
   * </pre>
   *
   * <code>string tag = 4 [json_name = "tag"];</code>
   * @param value The tag to set.
   */
  private void setTag(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    tag_ = value;
  }
  /**
   * <pre>
   * oci-build: image tag
   * </pre>
   *
   * <code>string tag = 4 [json_name = "tag"];</code>
   */
  private void clearTag() {

    tag_ = getDefaultInstance().getTag();
  }
  /**
   * <pre>
   * oci-build: image tag
   * </pre>
   *
   * <code>string tag = 4 [json_name = "tag"];</code>
   * @param value The bytes for tag to set.
   */
  private void setTagBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    tag_ = value.toStringUtf8();

  }

  public static final int PATH_FIELD_NUMBER = 5;
  private java.lang.String path_;
  /**
   * <pre>
   * artifact-upload: glob path(s) relative to workspace
   * </pre>
   *
   * <code>string path = 5 [json_name = "path"];</code>
   * @return The path.
   */
  @java.lang.Override
  public java.lang.String getPath() {
    return path_;
  }
  /**
   * <pre>
   * artifact-upload: glob path(s) relative to workspace
   * </pre>
   *
   * <code>string path = 5 [json_name = "path"];</code>
   * @return The bytes for path.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPathBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(path_);
  }
  /**
   * <pre>
   * artifact-upload: glob path(s) relative to workspace
   * </pre>
   *
   * <code>string path = 5 [json_name = "path"];</code>
   * @param value The path to set.
   */
  private void setPath(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    path_ = value;
  }
  /**
   * <pre>
   * artifact-upload: glob path(s) relative to workspace
   * </pre>
   *
   * <code>string path = 5 [json_name = "path"];</code>
   */
  private void clearPath() {

    path_ = getDefaultInstance().getPath();
  }
  /**
   * <pre>
   * artifact-upload: glob path(s) relative to workspace
   * </pre>
   *
   * <code>string path = 5 [json_name = "path"];</code>
   * @param value The bytes for path to set.
   */
  private void setPathBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    path_ = value.toStringUtf8();

  }

  public static final int DESTINATION_FIELD_NUMBER = 6;
  private java.lang.String destination_;
  /**
   * <pre>
   * artifact-upload: workspace | release | registry
   * </pre>
   *
   * <code>string destination = 6 [json_name = "destination"];</code>
   * @return The destination.
   */
  @java.lang.Override
  public java.lang.String getDestination() {
    return destination_;
  }
  /**
   * <pre>
   * artifact-upload: workspace | release | registry
   * </pre>
   *
   * <code>string destination = 6 [json_name = "destination"];</code>
   * @return The bytes for destination.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDestinationBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(destination_);
  }
  /**
   * <pre>
   * artifact-upload: workspace | release | registry
   * </pre>
   *
   * <code>string destination = 6 [json_name = "destination"];</code>
   * @param value The destination to set.
   */
  private void setDestination(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    destination_ = value;
  }
  /**
   * <pre>
   * artifact-upload: workspace | release | registry
   * </pre>
   *
   * <code>string destination = 6 [json_name = "destination"];</code>
   */
  private void clearDestination() {

    destination_ = getDefaultInstance().getDestination();
  }
  /**
   * <pre>
   * artifact-upload: workspace | release | registry
   * </pre>
   *
   * <code>string destination = 6 [json_name = "destination"];</code>
   * @param value The bytes for destination to set.
   */
  private void setDestinationBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    destination_ = value.toStringUtf8();

  }

  public static final int REF_FIELD_NUMBER = 7;
  private java.lang.String ref_;
  /**
   * <pre>
   * artifact-upload: release tag/ref
   * </pre>
   *
   * <code>string ref = 7 [json_name = "ref"];</code>
   * @return The ref.
   */
  @java.lang.Override
  public java.lang.String getRef() {
    return ref_;
  }
  /**
   * <pre>
   * artifact-upload: release tag/ref
   * </pre>
   *
   * <code>string ref = 7 [json_name = "ref"];</code>
   * @return The bytes for ref.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRefBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(ref_);
  }
  /**
   * <pre>
   * artifact-upload: release tag/ref
   * </pre>
   *
   * <code>string ref = 7 [json_name = "ref"];</code>
   * @param value The ref to set.
   */
  private void setRef(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    ref_ = value;
  }
  /**
   * <pre>
   * artifact-upload: release tag/ref
   * </pre>
   *
   * <code>string ref = 7 [json_name = "ref"];</code>
   */
  private void clearRef() {

    ref_ = getDefaultInstance().getRef();
  }
  /**
   * <pre>
   * artifact-upload: release tag/ref
   * </pre>
   *
   * <code>string ref = 7 [json_name = "ref"];</code>
   * @param value The bytes for ref to set.
   */
  private void setRefBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ref_ = value.toStringUtf8();

  }

  public static final int PROTOCOL_FIELD_NUMBER = 8;
  private java.lang.String protocol_;
  /**
   * <pre>
   * publish-protocol: npm/pypi/cargo/...
   * </pre>
   *
   * <code>string protocol = 8 [json_name = "protocol"];</code>
   * @return The protocol.
   */
  @java.lang.Override
  public java.lang.String getProtocol() {
    return protocol_;
  }
  /**
   * <pre>
   * publish-protocol: npm/pypi/cargo/...
   * </pre>
   *
   * <code>string protocol = 8 [json_name = "protocol"];</code>
   * @return The bytes for protocol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProtocolBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(protocol_);
  }
  /**
   * <pre>
   * publish-protocol: npm/pypi/cargo/...
   * </pre>
   *
   * <code>string protocol = 8 [json_name = "protocol"];</code>
   * @param value The protocol to set.
   */
  private void setProtocol(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    protocol_ = value;
  }
  /**
   * <pre>
   * publish-protocol: npm/pypi/cargo/...
   * </pre>
   *
   * <code>string protocol = 8 [json_name = "protocol"];</code>
   */
  private void clearProtocol() {

    protocol_ = getDefaultInstance().getProtocol();
  }
  /**
   * <pre>
   * publish-protocol: npm/pypi/cargo/...
   * </pre>
   *
   * <code>string protocol = 8 [json_name = "protocol"];</code>
   * @param value The bytes for protocol to set.
   */
  private void setProtocolBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    protocol_ = value.toStringUtf8();

  }

  public static final int NAME_FIELD_NUMBER = 9;
  private java.lang.String name_;
  /**
   * <code>string name = 9 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <code>string name = 9 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <code>string name = 9 [json_name = "name"];</code>
   * @param value The name to set.
   */
  private void setName(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    name_ = value;
  }
  /**
   * <code>string name = 9 [json_name = "name"];</code>
   */
  private void clearName() {

    name_ = getDefaultInstance().getName();
  }
  /**
   * <code>string name = 9 [json_name = "name"];</code>
   * @param value The bytes for name to set.
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    name_ = value.toStringUtf8();

  }

  public static final int VERSION_FIELD_NUMBER = 10;
  private java.lang.String version_;
  /**
   * <code>string version = 10 [json_name = "version"];</code>
   * @return The version.
   */
  @java.lang.Override
  public java.lang.String getVersion() {
    return version_;
  }
  /**
   * <code>string version = 10 [json_name = "version"];</code>
   * @return The bytes for version.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(version_);
  }
  /**
   * <code>string version = 10 [json_name = "version"];</code>
   * @param value The version to set.
   */
  private void setVersion(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    version_ = value;
  }
  /**
   * <code>string version = 10 [json_name = "version"];</code>
   */
  private void clearVersion() {

    version_ = getDefaultInstance().getVersion();
  }
  /**
   * <code>string version = 10 [json_name = "version"];</code>
   * @param value The bytes for version to set.
   */
  private void setVersionBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    version_ = value.toStringUtf8();

  }

  public static final int FILE_FIELD_NUMBER = 11;
  private java.lang.String file_;
  /**
   * <code>string file = 11 [json_name = "file"];</code>
   * @return The file.
   */
  @java.lang.Override
  public java.lang.String getFile() {
    return file_;
  }
  /**
   * <code>string file = 11 [json_name = "file"];</code>
   * @return The bytes for file.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFileBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(file_);
  }
  /**
   * <code>string file = 11 [json_name = "file"];</code>
   * @param value The file to set.
   */
  private void setFile(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    file_ = value;
  }
  /**
   * <code>string file = 11 [json_name = "file"];</code>
   */
  private void clearFile() {

    file_ = getDefaultInstance().getFile();
  }
  /**
   * <code>string file = 11 [json_name = "file"];</code>
   * @param value The bytes for file to set.
   */
  private void setFileBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    file_ = value.toStringUtf8();

  }

  public static final int CONTAINERFILE_FIELD_NUMBER = 12;
  private java.lang.String containerfile_;
  /**
   * <pre>
   * oci-build: inline Dockerfile/Containerfile body
   * </pre>
   *
   * <code>string containerfile = 12 [json_name = "containerfile"];</code>
   * @return The containerfile.
   */
  @java.lang.Override
  public java.lang.String getContainerfile() {
    return containerfile_;
  }
  /**
   * <pre>
   * oci-build: inline Dockerfile/Containerfile body
   * </pre>
   *
   * <code>string containerfile = 12 [json_name = "containerfile"];</code>
   * @return The bytes for containerfile.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContainerfileBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(containerfile_);
  }
  /**
   * <pre>
   * oci-build: inline Dockerfile/Containerfile body
   * </pre>
   *
   * <code>string containerfile = 12 [json_name = "containerfile"];</code>
   * @param value The containerfile to set.
   */
  private void setContainerfile(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    containerfile_ = value;
  }
  /**
   * <pre>
   * oci-build: inline Dockerfile/Containerfile body
   * </pre>
   *
   * <code>string containerfile = 12 [json_name = "containerfile"];</code>
   */
  private void clearContainerfile() {

    containerfile_ = getDefaultInstance().getContainerfile();
  }
  /**
   * <pre>
   * oci-build: inline Dockerfile/Containerfile body
   * </pre>
   *
   * <code>string containerfile = 12 [json_name = "containerfile"];</code>
   * @param value The bytes for containerfile to set.
   */
  private void setContainerfileBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    containerfile_ = value.toStringUtf8();

  }

  public static com.easylab.v1.Produce parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.Produce parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.Produce parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.Produce parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.Produce parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.Produce parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.Produce parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easylab.v1.Produce parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.easylab.v1.Produce parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.easylab.v1.Produce parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.easylab.v1.Produce parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easylab.v1.Produce parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.easylab.v1.Produce prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code easylab.v1.Produce}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.easylab.v1.Produce, Builder> implements
      // @@protoc_insertion_point(builder_implements:easylab.v1.Produce)
      com.easylab.v1.ProduceOrBuilder {
    // Construct using com.easylab.v1.Produce.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * oci-build | artifact-upload | publish-protocol
     * </pre>
     *
     * <code>string action = 1 [json_name = "action"];</code>
     * @return The action.
     */
    @java.lang.Override
    public java.lang.String getAction() {
      return instance.getAction();
    }
    /**
     * <pre>
     * oci-build | artifact-upload | publish-protocol
     * </pre>
     *
     * <code>string action = 1 [json_name = "action"];</code>
     * @return The bytes for action.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getActionBytes() {
      return instance.getActionBytes();
    }
    /**
     * <pre>
     * oci-build | artifact-upload | publish-protocol
     * </pre>
     *
     * <code>string action = 1 [json_name = "action"];</code>
     * @param value The action to set.
     * @return This builder for chaining.
     */
    public Builder setAction(
        java.lang.String value) {
      copyOnWrite();
      instance.setAction(value);
      return this;
    }
    /**
     * <pre>
     * oci-build | artifact-upload | publish-protocol
     * </pre>
     *
     * <code>string action = 1 [json_name = "action"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAction() {
      copyOnWrite();
      instance.clearAction();
      return this;
    }
    /**
     * <pre>
     * oci-build | artifact-upload | publish-protocol
     * </pre>
     *
     * <code>string action = 1 [json_name = "action"];</code>
     * @param value The bytes for action to set.
     * @return This builder for chaining.
     */
    public Builder setActionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setActionBytes(value);
      return this;
    }

    /**
     * <pre>
     * oci-build: build context (default workspace root)
     * </pre>
     *
     * <code>string context = 2 [json_name = "context"];</code>
     * @return The context.
     */
    @java.lang.Override
    public java.lang.String getContext() {
      return instance.getContext();
    }
    /**
     * <pre>
     * oci-build: build context (default workspace root)
     * </pre>
     *
     * <code>string context = 2 [json_name = "context"];</code>
     * @return The bytes for context.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContextBytes() {
      return instance.getContextBytes();
    }
    /**
     * <pre>
     * oci-build: build context (default workspace root)
     * </pre>
     *
     * <code>string context = 2 [json_name = "context"];</code>
     * @param value The context to set.
     * @return This builder for chaining.
     */
    public Builder setContext(
        java.lang.String value) {
      copyOnWrite();
      instance.setContext(value);
      return this;
    }
    /**
     * <pre>
     * oci-build: build context (default workspace root)
     * </pre>
     *
     * <code>string context = 2 [json_name = "context"];</code>
     * @return This builder for chaining.
     */
    public Builder clearContext() {
      copyOnWrite();
      instance.clearContext();
      return this;
    }
    /**
     * <pre>
     * oci-build: build context (default workspace root)
     * </pre>
     *
     * <code>string context = 2 [json_name = "context"];</code>
     * @param value The bytes for context to set.
     * @return This builder for chaining.
     */
    public Builder setContextBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setContextBytes(value);
      return this;
    }

    /**
     * <pre>
     * oci-build: Dockerfile path (default root/Dockerfile)
     * </pre>
     *
     * <code>string dockerfile = 3 [json_name = "dockerfile"];</code>
     * @return The dockerfile.
     */
    @java.lang.Override
    public java.lang.String getDockerfile() {
      return instance.getDockerfile();
    }
    /**
     * <pre>
     * oci-build: Dockerfile path (default root/Dockerfile)
     * </pre>
     *
     * <code>string dockerfile = 3 [json_name = "dockerfile"];</code>
     * @return The bytes for dockerfile.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDockerfileBytes() {
      return instance.getDockerfileBytes();
    }
    /**
     * <pre>
     * oci-build: Dockerfile path (default root/Dockerfile)
     * </pre>
     *
     * <code>string dockerfile = 3 [json_name = "dockerfile"];</code>
     * @param value The dockerfile to set.
     * @return This builder for chaining.
     */
    public Builder setDockerfile(
        java.lang.String value) {
      copyOnWrite();
      instance.setDockerfile(value);
      return this;
    }
    /**
     * <pre>
     * oci-build: Dockerfile path (default root/Dockerfile)
     * </pre>
     *
     * <code>string dockerfile = 3 [json_name = "dockerfile"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDockerfile() {
      copyOnWrite();
      instance.clearDockerfile();
      return this;
    }
    /**
     * <pre>
     * oci-build: Dockerfile path (default root/Dockerfile)
     * </pre>
     *
     * <code>string dockerfile = 3 [json_name = "dockerfile"];</code>
     * @param value The bytes for dockerfile to set.
     * @return This builder for chaining.
     */
    public Builder setDockerfileBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDockerfileBytes(value);
      return this;
    }

    /**
     * <pre>
     * oci-build: image tag
     * </pre>
     *
     * <code>string tag = 4 [json_name = "tag"];</code>
     * @return The tag.
     */
    @java.lang.Override
    public java.lang.String getTag() {
      return instance.getTag();
    }
    /**
     * <pre>
     * oci-build: image tag
     * </pre>
     *
     * <code>string tag = 4 [json_name = "tag"];</code>
     * @return The bytes for tag.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTagBytes() {
      return instance.getTagBytes();
    }
    /**
     * <pre>
     * oci-build: image tag
     * </pre>
     *
     * <code>string tag = 4 [json_name = "tag"];</code>
     * @param value The tag to set.
     * @return This builder for chaining.
     */
    public Builder setTag(
        java.lang.String value) {
      copyOnWrite();
      instance.setTag(value);
      return this;
    }
    /**
     * <pre>
     * oci-build: image tag
     * </pre>
     *
     * <code>string tag = 4 [json_name = "tag"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTag() {
      copyOnWrite();
      instance.clearTag();
      return this;
    }
    /**
     * <pre>
     * oci-build: image tag
     * </pre>
     *
     * <code>string tag = 4 [json_name = "tag"];</code>
     * @param value The bytes for tag to set.
     * @return This builder for chaining.
     */
    public Builder setTagBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTagBytes(value);
      return this;
    }

    /**
     * <pre>
     * artifact-upload: glob path(s) relative to workspace
     * </pre>
     *
     * <code>string path = 5 [json_name = "path"];</code>
     * @return The path.
     */
    @java.lang.Override
    public java.lang.String getPath() {
      return instance.getPath();
    }
    /**
     * <pre>
     * artifact-upload: glob path(s) relative to workspace
     * </pre>
     *
     * <code>string path = 5 [json_name = "path"];</code>
     * @return The bytes for path.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPathBytes() {
      return instance.getPathBytes();
    }
    /**
     * <pre>
     * artifact-upload: glob path(s) relative to workspace
     * </pre>
     *
     * <code>string path = 5 [json_name = "path"];</code>
     * @param value The path to set.
     * @return This builder for chaining.
     */
    public Builder setPath(
        java.lang.String value) {
      copyOnWrite();
      instance.setPath(value);
      return this;
    }
    /**
     * <pre>
     * artifact-upload: glob path(s) relative to workspace
     * </pre>
     *
     * <code>string path = 5 [json_name = "path"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPath() {
      copyOnWrite();
      instance.clearPath();
      return this;
    }
    /**
     * <pre>
     * artifact-upload: glob path(s) relative to workspace
     * </pre>
     *
     * <code>string path = 5 [json_name = "path"];</code>
     * @param value The bytes for path to set.
     * @return This builder for chaining.
     */
    public Builder setPathBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPathBytes(value);
      return this;
    }

    /**
     * <pre>
     * artifact-upload: workspace | release | registry
     * </pre>
     *
     * <code>string destination = 6 [json_name = "destination"];</code>
     * @return The destination.
     */
    @java.lang.Override
    public java.lang.String getDestination() {
      return instance.getDestination();
    }
    /**
     * <pre>
     * artifact-upload: workspace | release | registry
     * </pre>
     *
     * <code>string destination = 6 [json_name = "destination"];</code>
     * @return The bytes for destination.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDestinationBytes() {
      return instance.getDestinationBytes();
    }
    /**
     * <pre>
     * artifact-upload: workspace | release | registry
     * </pre>
     *
     * <code>string destination = 6 [json_name = "destination"];</code>
     * @param value The destination to set.
     * @return This builder for chaining.
     */
    public Builder setDestination(
        java.lang.String value) {
      copyOnWrite();
      instance.setDestination(value);
      return this;
    }
    /**
     * <pre>
     * artifact-upload: workspace | release | registry
     * </pre>
     *
     * <code>string destination = 6 [json_name = "destination"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDestination() {
      copyOnWrite();
      instance.clearDestination();
      return this;
    }
    /**
     * <pre>
     * artifact-upload: workspace | release | registry
     * </pre>
     *
     * <code>string destination = 6 [json_name = "destination"];</code>
     * @param value The bytes for destination to set.
     * @return This builder for chaining.
     */
    public Builder setDestinationBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDestinationBytes(value);
      return this;
    }

    /**
     * <pre>
     * artifact-upload: release tag/ref
     * </pre>
     *
     * <code>string ref = 7 [json_name = "ref"];</code>
     * @return The ref.
     */
    @java.lang.Override
    public java.lang.String getRef() {
      return instance.getRef();
    }
    /**
     * <pre>
     * artifact-upload: release tag/ref
     * </pre>
     *
     * <code>string ref = 7 [json_name = "ref"];</code>
     * @return The bytes for ref.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRefBytes() {
      return instance.getRefBytes();
    }
    /**
     * <pre>
     * artifact-upload: release tag/ref
     * </pre>
     *
     * <code>string ref = 7 [json_name = "ref"];</code>
     * @param value The ref to set.
     * @return This builder for chaining.
     */
    public Builder setRef(
        java.lang.String value) {
      copyOnWrite();
      instance.setRef(value);
      return this;
    }
    /**
     * <pre>
     * artifact-upload: release tag/ref
     * </pre>
     *
     * <code>string ref = 7 [json_name = "ref"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRef() {
      copyOnWrite();
      instance.clearRef();
      return this;
    }
    /**
     * <pre>
     * artifact-upload: release tag/ref
     * </pre>
     *
     * <code>string ref = 7 [json_name = "ref"];</code>
     * @param value The bytes for ref to set.
     * @return This builder for chaining.
     */
    public Builder setRefBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRefBytes(value);
      return this;
    }

    /**
     * <pre>
     * publish-protocol: npm/pypi/cargo/...
     * </pre>
     *
     * <code>string protocol = 8 [json_name = "protocol"];</code>
     * @return The protocol.
     */
    @java.lang.Override
    public java.lang.String getProtocol() {
      return instance.getProtocol();
    }
    /**
     * <pre>
     * publish-protocol: npm/pypi/cargo/...
     * </pre>
     *
     * <code>string protocol = 8 [json_name = "protocol"];</code>
     * @return The bytes for protocol.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProtocolBytes() {
      return instance.getProtocolBytes();
    }
    /**
     * <pre>
     * publish-protocol: npm/pypi/cargo/...
     * </pre>
     *
     * <code>string protocol = 8 [json_name = "protocol"];</code>
     * @param value The protocol to set.
     * @return This builder for chaining.
     */
    public Builder setProtocol(
        java.lang.String value) {
      copyOnWrite();
      instance.setProtocol(value);
      return this;
    }
    /**
     * <pre>
     * publish-protocol: npm/pypi/cargo/...
     * </pre>
     *
     * <code>string protocol = 8 [json_name = "protocol"];</code>
     * @return This builder for chaining.
     */
    public Builder clearProtocol() {
      copyOnWrite();
      instance.clearProtocol();
      return this;
    }
    /**
     * <pre>
     * publish-protocol: npm/pypi/cargo/...
     * </pre>
     *
     * <code>string protocol = 8 [json_name = "protocol"];</code>
     * @param value The bytes for protocol to set.
     * @return This builder for chaining.
     */
    public Builder setProtocolBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setProtocolBytes(value);
      return this;
    }

    /**
     * <code>string name = 9 [json_name = "name"];</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <code>string name = 9 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <code>string name = 9 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <code>string name = 9 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <code>string name = 9 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <code>string version = 10 [json_name = "version"];</code>
     * @return The version.
     */
    @java.lang.Override
    public java.lang.String getVersion() {
      return instance.getVersion();
    }
    /**
     * <code>string version = 10 [json_name = "version"];</code>
     * @return The bytes for version.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVersionBytes() {
      return instance.getVersionBytes();
    }
    /**
     * <code>string version = 10 [json_name = "version"];</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        java.lang.String value) {
      copyOnWrite();
      instance.setVersion(value);
      return this;
    }
    /**
     * <code>string version = 10 [json_name = "version"];</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      copyOnWrite();
      instance.clearVersion();
      return this;
    }
    /**
     * <code>string version = 10 [json_name = "version"];</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setVersionBytes(value);
      return this;
    }

    /**
     * <code>string file = 11 [json_name = "file"];</code>
     * @return The file.
     */
    @java.lang.Override
    public java.lang.String getFile() {
      return instance.getFile();
    }
    /**
     * <code>string file = 11 [json_name = "file"];</code>
     * @return The bytes for file.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileBytes() {
      return instance.getFileBytes();
    }
    /**
     * <code>string file = 11 [json_name = "file"];</code>
     * @param value The file to set.
     * @return This builder for chaining.
     */
    public Builder setFile(
        java.lang.String value) {
      copyOnWrite();
      instance.setFile(value);
      return this;
    }
    /**
     * <code>string file = 11 [json_name = "file"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFile() {
      copyOnWrite();
      instance.clearFile();
      return this;
    }
    /**
     * <code>string file = 11 [json_name = "file"];</code>
     * @param value The bytes for file to set.
     * @return This builder for chaining.
     */
    public Builder setFileBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFileBytes(value);
      return this;
    }

    /**
     * <pre>
     * oci-build: inline Dockerfile/Containerfile body
     * </pre>
     *
     * <code>string containerfile = 12 [json_name = "containerfile"];</code>
     * @return The containerfile.
     */
    @java.lang.Override
    public java.lang.String getContainerfile() {
      return instance.getContainerfile();
    }
    /**
     * <pre>
     * oci-build: inline Dockerfile/Containerfile body
     * </pre>
     *
     * <code>string containerfile = 12 [json_name = "containerfile"];</code>
     * @return The bytes for containerfile.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContainerfileBytes() {
      return instance.getContainerfileBytes();
    }
    /**
     * <pre>
     * oci-build: inline Dockerfile/Containerfile body
     * </pre>
     *
     * <code>string containerfile = 12 [json_name = "containerfile"];</code>
     * @param value The containerfile to set.
     * @return This builder for chaining.
     */
    public Builder setContainerfile(
        java.lang.String value) {
      copyOnWrite();
      instance.setContainerfile(value);
      return this;
    }
    /**
     * <pre>
     * oci-build: inline Dockerfile/Containerfile body
     * </pre>
     *
     * <code>string containerfile = 12 [json_name = "containerfile"];</code>
     * @return This builder for chaining.
     */
    public Builder clearContainerfile() {
      copyOnWrite();
      instance.clearContainerfile();
      return this;
    }
    /**
     * <pre>
     * oci-build: inline Dockerfile/Containerfile body
     * </pre>
     *
     * <code>string containerfile = 12 [json_name = "containerfile"];</code>
     * @param value The bytes for containerfile to set.
     * @return This builder for chaining.
     */
    public Builder setContainerfileBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setContainerfileBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:easylab.v1.Produce)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.easylab.v1.Produce();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "action_",
            "context_",
            "dockerfile_",
            "tag_",
            "path_",
            "destination_",
            "ref_",
            "protocol_",
            "name_",
            "version_",
            "file_",
            "containerfile_",
          };
          java.lang.String info =
              "\u0000\f\u0000\u0000\u0001\f\f\u0000\u0000\u0000\u0001\u0208\u0002\u0208\u0003\u0208" +
              "\u0004\u0208\u0005\u0208\u0006\u0208\u0007\u0208\b\u0208\t\u0208\n\u0208\u000b\u0208" +
              "\f\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.easylab.v1.Produce> parser = PARSER;
        if (parser == null) {
          synchronized (com.easylab.v1.Produce.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.easylab.v1.Produce>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:easylab.v1.Produce)
  private static final com.easylab.v1.Produce DEFAULT_INSTANCE;
  static {
    Produce defaultInstance = new Produce();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Produce.class, defaultInstance);
  }

  public static com.easylab.v1.Produce getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Produce> PARSER;

  public static com.google.protobuf.Parser<Produce> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

