// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto
// Protobuf Java Version: 4.36.1

package com.easylab.v1;

@com.google.protobuf.Generated
public interface ProduceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:easylab.v1.Produce)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * oci-build | artifact-upload | publish-protocol
   * </pre>
   *
   * <code>string action = 1 [json_name = "action"];</code>
   * @return The action.
   */
  java.lang.String getAction();
  /**
   * <pre>
   * oci-build | artifact-upload | publish-protocol
   * </pre>
   *
   * <code>string action = 1 [json_name = "action"];</code>
   * @return The bytes for action.
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <pre>
   * oci-build: build context (default workspace root)
   * </pre>
   *
   * <code>string context = 2 [json_name = "context"];</code>
   * @return The context.
   */
  java.lang.String getContext();
  /**
   * <pre>
   * oci-build: build context (default workspace root)
   * </pre>
   *
   * <code>string context = 2 [json_name = "context"];</code>
   * @return The bytes for context.
   */
  com.google.protobuf.ByteString
      getContextBytes();

  /**
   * <pre>
   * oci-build: Dockerfile path (default root/Dockerfile)
   * </pre>
   *
   * <code>string dockerfile = 3 [json_name = "dockerfile"];</code>
   * @return The dockerfile.
   */
  java.lang.String getDockerfile();
  /**
   * <pre>
   * oci-build: Dockerfile path (default root/Dockerfile)
   * </pre>
   *
   * <code>string dockerfile = 3 [json_name = "dockerfile"];</code>
   * @return The bytes for dockerfile.
   */
  com.google.protobuf.ByteString
      getDockerfileBytes();

  /**
   * <pre>
   * oci-build: image tag
   * </pre>
   *
   * <code>string tag = 4 [json_name = "tag"];</code>
   * @return The tag.
   */
  java.lang.String getTag();
  /**
   * <pre>
   * oci-build: image tag
   * </pre>
   *
   * <code>string tag = 4 [json_name = "tag"];</code>
   * @return The bytes for tag.
   */
  com.google.protobuf.ByteString
      getTagBytes();

  /**
   * <pre>
   * artifact-upload: glob path(s) relative to workspace
   * </pre>
   *
   * <code>string path = 5 [json_name = "path"];</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <pre>
   * artifact-upload: glob path(s) relative to workspace
   * </pre>
   *
   * <code>string path = 5 [json_name = "path"];</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <pre>
   * artifact-upload: workspace | release | registry
   * </pre>
   *
   * <code>string destination = 6 [json_name = "destination"];</code>
   * @return The destination.
   */
  java.lang.String getDestination();
  /**
   * <pre>
   * artifact-upload: workspace | release | registry
   * </pre>
   *
   * <code>string destination = 6 [json_name = "destination"];</code>
   * @return The bytes for destination.
   */
  com.google.protobuf.ByteString
      getDestinationBytes();

  /**
   * <pre>
   * artifact-upload: release tag/ref
   * </pre>
   *
   * <code>string ref = 7 [json_name = "ref"];</code>
   * @return The ref.
   */
  java.lang.String getRef();
  /**
   * <pre>
   * artifact-upload: release tag/ref
   * </pre>
   *
   * <code>string ref = 7 [json_name = "ref"];</code>
   * @return The bytes for ref.
   */
  com.google.protobuf.ByteString
      getRefBytes();

  /**
   * <pre>
   * publish-protocol: npm/pypi/cargo/...
   * </pre>
   *
   * <code>string protocol = 8 [json_name = "protocol"];</code>
   * @return The protocol.
   */
  java.lang.String getProtocol();
  /**
   * <pre>
   * publish-protocol: npm/pypi/cargo/...
   * </pre>
   *
   * <code>string protocol = 8 [json_name = "protocol"];</code>
   * @return The bytes for protocol.
   */
  com.google.protobuf.ByteString
      getProtocolBytes();

  /**
   * <code>string name = 9 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 9 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string version = 10 [json_name = "version"];</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 10 [json_name = "version"];</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string file = 11 [json_name = "file"];</code>
   * @return The file.
   */
  java.lang.String getFile();
  /**
   * <code>string file = 11 [json_name = "file"];</code>
   * @return The bytes for file.
   */
  com.google.protobuf.ByteString
      getFileBytes();

  /**
   * <pre>
   * oci-build: inline Dockerfile/Containerfile body
   * </pre>
   *
   * <code>string containerfile = 12 [json_name = "containerfile"];</code>
   * @return The containerfile.
   */
  java.lang.String getContainerfile();
  /**
   * <pre>
   * oci-build: inline Dockerfile/Containerfile body
   * </pre>
   *
   * <code>string containerfile = 12 [json_name = "containerfile"];</code>
   * @return The bytes for containerfile.
   */
  com.google.protobuf.ByteString
      getContainerfileBytes();
}
