// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto
// Protobuf Java Version: 4.36.1

package com.easylab.v1;

@com.google.protobuf.Generated
public interface RebaseManyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:easylab.v1.RebaseManyRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string org = 1 [json_name = "org"];</code>
   * @return The org.
   */
  java.lang.String getOrg();
  /**
   * <code>string org = 1 [json_name = "org"];</code>
   * @return The bytes for org.
   */
  com.google.protobuf.ByteString
      getOrgBytes();

  /**
   * <code>string repo = 2 [json_name = "repo"];</code>
   * @return The repo.
   */
  java.lang.String getRepo();
  /**
   * <code>string repo = 2 [json_name = "repo"];</code>
   * @return The bytes for repo.
   */
  com.google.protobuf.ByteString
      getRepoBytes();

  /**
   * <code>repeated string revs = 3 [json_name = "revs"];</code>
   * @return A list containing the revs.
   */
  java.util.List<java.lang.String>
      getRevsList();
  /**
   * <code>repeated string revs = 3 [json_name = "revs"];</code>
   * @return The count of revs.
   */
  int getRevsCount();
  /**
   * <code>repeated string revs = 3 [json_name = "revs"];</code>
   * @param index The index of the element to return.
   * @return The revs at the given index.
   */
  java.lang.String getRevs(int index);
  /**
   * <code>repeated string revs = 3 [json_name = "revs"];</code>
   * @param index The index of the element to return.
   * @return The revs at the given index.
   */
  com.google.protobuf.ByteString
      getRevsBytes(int index);

  /**
   * <code>string onto = 4 [json_name = "onto"];</code>
   * @return The onto.
   */
  java.lang.String getOnto();
  /**
   * <code>string onto = 4 [json_name = "onto"];</code>
   * @return The bytes for onto.
   */
  com.google.protobuf.ByteString
      getOntoBytes();
}
