// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easylab.v1;

@kotlin.jvm.JvmName("-initializeregisterRunnerRequest")
public inline fun registerRunnerRequest(block: com.easylab.v1.RegisterRunnerRequestKt.Dsl.() -> kotlin.Unit): com.easylab.v1.RegisterRunnerRequest =
  com.easylab.v1.RegisterRunnerRequestKt.Dsl._create(com.easylab.v1.RegisterRunnerRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easylab.v1.RegisterRunnerRequest`
 */
public object RegisterRunnerRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easylab.v1.RegisterRunnerRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easylab.v1.RegisterRunnerRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easylab.v1.RegisterRunnerRequest = _builder.build()

    /**
     * `.easylab.v1.Runner runner = 1 [json_name = "runner"];`
     */
    public var runner: com.easylab.v1.Runner
      @kotlin.jvm.JvmName("getRunner")
        get() = _builder.runner
      @kotlin.jvm.JvmName("setRunner")
        set(value) {
        _builder.runner = value
      }
    /**
     * `.easylab.v1.Runner runner = 1 [json_name = "runner"];`
     */
    public fun clearRunner() {
      _builder.clearRunner()
    }
    /**
     * `.easylab.v1.Runner runner = 1 [json_name = "runner"];`
     * @return Whether the runner field is set.
     */
    public fun hasRunner(): kotlin.Boolean {
      return _builder.hasRunner()
    }

    public val RegisterRunnerRequestKt.Dsl.runnerOrNull: com.easylab.v1.Runner?
      get() = _builder.runnerOrNull
  }
}
public inline fun com.easylab.v1.RegisterRunnerRequest.copy(block: `com.easylab.v1`.RegisterRunnerRequestKt.Dsl.() -> kotlin.Unit): com.easylab.v1.RegisterRunnerRequest =
  `com.easylab.v1`.RegisterRunnerRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.easylab.v1.RegisterRunnerRequestOrBuilder.runnerOrNull: com.easylab.v1.Runner?
  get() = if (hasRunner()) getRunner() else null

