// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easylab.v1;

@kotlin.jvm.JvmName("-initializeregisterRunnerResponse")
public inline fun registerRunnerResponse(block: com.easylab.v1.RegisterRunnerResponseKt.Dsl.() -> kotlin.Unit): com.easylab.v1.RegisterRunnerResponse =
  com.easylab.v1.RegisterRunnerResponseKt.Dsl._create(com.easylab.v1.RegisterRunnerResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easylab.v1.RegisterRunnerResponse`
 */
public object RegisterRunnerResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easylab.v1.RegisterRunnerResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easylab.v1.RegisterRunnerResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easylab.v1.RegisterRunnerResponse = _builder.build()

    /**
     * `bool ok = 1 [json_name = "ok"];`
     */
    public var ok: kotlin.Boolean
      @kotlin.jvm.JvmName("getOk")
        get() = _builder.ok
      @kotlin.jvm.JvmName("setOk")
        set(value) {
        _builder.ok = value
      }
    /**
     * `bool ok = 1 [json_name = "ok"];`
     */
    public fun clearOk() {
      _builder.clearOk()
    }
  }
}
public inline fun com.easylab.v1.RegisterRunnerResponse.copy(block: `com.easylab.v1`.RegisterRunnerResponseKt.Dsl.() -> kotlin.Unit): com.easylab.v1.RegisterRunnerResponse =
  `com.easylab.v1`.RegisterRunnerResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

