// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package easylab.v1;

@kotlin.jvm.JvmName("-initializeregisterExternalSandboxResponse")
public inline fun registerExternalSandboxResponse(block: easylab.v1.RegisterExternalSandboxResponseKt.Dsl.() -> kotlin.Unit): easylab.v1.Easylab.RegisterExternalSandboxResponse =
  easylab.v1.RegisterExternalSandboxResponseKt.Dsl._create(easylab.v1.Easylab.RegisterExternalSandboxResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easylab.v1.RegisterExternalSandboxResponse`
 */
public object RegisterExternalSandboxResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: easylab.v1.Easylab.RegisterExternalSandboxResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: easylab.v1.Easylab.RegisterExternalSandboxResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): easylab.v1.Easylab.RegisterExternalSandboxResponse = _builder.build()

    /**
     * `bool ok = 1 [json_name = "ok"];`
     */
    public var ok: kotlin.Boolean
      @kotlin.jvm.JvmName("getOk")
        get() = _builder.ok
      @kotlin.jvm.JvmName("setOk")
        set(value) {
        _builder.ok = value
      }
    /**
     * `bool ok = 1 [json_name = "ok"];`
     */
    public fun clearOk() {
      _builder.clearOk()
    }

    /**
     * ```
     * the active bearer token (issued or echoed)
     * ```
     *
     * `string token = 2 [json_name = "token"];`
     */
    public var token: kotlin.String
      @kotlin.jvm.JvmName("getToken")
        get() = _builder.token
      @kotlin.jvm.JvmName("setToken")
        set(value) {
        _builder.token = value
      }
    /**
     * ```
     * the active bearer token (issued or echoed)
     * ```
     *
     * `string token = 2 [json_name = "token"];`
     */
    public fun clearToken() {
      _builder.clearToken()
    }

    /**
     * `string error = 3 [json_name = "error"];`
     */
    public var error: kotlin.String
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `string error = 3 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }
  }
}
public inline fun easylab.v1.Easylab.RegisterExternalSandboxResponse.copy(block: `easylab.v1`.RegisterExternalSandboxResponseKt.Dsl.() -> kotlin.Unit): easylab.v1.Easylab.RegisterExternalSandboxResponse =
  `easylab.v1`.RegisterExternalSandboxResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

