// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto
// Protobuf Java Version: 4.36.1

package com.easylab.v1;

@com.google.protobuf.Generated
public interface ReleaseExternalSandboxResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:easylab.v1.ReleaseExternalSandboxResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bool ok = 1 [json_name = "ok"];</code>
   * @return The ok.
   */
  boolean getOk();

  /**
   * <pre>
   * fresh one-time code for re-claiming ("" if not releasable)
   * </pre>
   *
   * <code>string code = 2 [json_name = "code"];</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <pre>
   * fresh one-time code for re-claiming ("" if not releasable)
   * </pre>
   *
   * <code>string code = 2 [json_name = "code"];</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string error = 3 [json_name = "error"];</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <code>string error = 3 [json_name = "error"];</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();
}
