// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto
// Protobuf Java Version: 4.36.1

package com.easylab.v1;

/**
 * Protobuf type {@code easylab.v1.RemoveRepoMemberRequest}
 */
@com.google.protobuf.Generated
public  final class RemoveRepoMemberRequest extends
    com.google.protobuf.GeneratedMessageLite<
        RemoveRepoMemberRequest, RemoveRepoMemberRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:easylab.v1.RemoveRepoMemberRequest)
    RemoveRepoMemberRequestOrBuilder {
  private RemoveRepoMemberRequest() {
    org_ = "";
    repo_ = "";
    username_ = "";
  }
  public static final int ORG_FIELD_NUMBER = 1;
  private java.lang.String org_;
  /**
   * <code>string org = 1 [json_name = "org"];</code>
   * @return The org.
   */
  @java.lang.Override
  public java.lang.String getOrg() {
    return org_;
  }
  /**
   * <code>string org = 1 [json_name = "org"];</code>
   * @return The bytes for org.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOrgBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(org_);
  }
  /**
   * <code>string org = 1 [json_name = "org"];</code>
   * @param value The org to set.
   */
  private void setOrg(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    org_ = value;
  }
  /**
   * <code>string org = 1 [json_name = "org"];</code>
   */
  private void clearOrg() {

    org_ = getDefaultInstance().getOrg();
  }
  /**
   * <code>string org = 1 [json_name = "org"];</code>
   * @param value The bytes for org to set.
   */
  private void setOrgBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    org_ = value.toStringUtf8();

  }

  public static final int REPO_FIELD_NUMBER = 2;
  private java.lang.String repo_;
  /**
   * <code>string repo = 2 [json_name = "repo"];</code>
   * @return The repo.
   */
  @java.lang.Override
  public java.lang.String getRepo() {
    return repo_;
  }
  /**
   * <code>string repo = 2 [json_name = "repo"];</code>
   * @return The bytes for repo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRepoBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(repo_);
  }
  /**
   * <code>string repo = 2 [json_name = "repo"];</code>
   * @param value The repo to set.
   */
  private void setRepo(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    repo_ = value;
  }
  /**
   * <code>string repo = 2 [json_name = "repo"];</code>
   */
  private void clearRepo() {

    repo_ = getDefaultInstance().getRepo();
  }
  /**
   * <code>string repo = 2 [json_name = "repo"];</code>
   * @param value The bytes for repo to set.
   */
  private void setRepoBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    repo_ = value.toStringUtf8();

  }

  public static final int USERNAME_FIELD_NUMBER = 3;
  private java.lang.String username_;
  /**
   * <code>string username = 3 [json_name = "username"];</code>
   * @return The username.
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    return username_;
  }
  /**
   * <code>string username = 3 [json_name = "username"];</code>
   * @return The bytes for username.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(username_);
  }
  /**
   * <code>string username = 3 [json_name = "username"];</code>
   * @param value The username to set.
   */
  private void setUsername(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    username_ = value;
  }
  /**
   * <code>string username = 3 [json_name = "username"];</code>
   */
  private void clearUsername() {

    username_ = getDefaultInstance().getUsername();
  }
  /**
   * <code>string username = 3 [json_name = "username"];</code>
   * @param value The bytes for username to set.
   */
  private void setUsernameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    username_ = value.toStringUtf8();

  }

  public static com.easylab.v1.RemoveRepoMemberRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.RemoveRepoMemberRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.RemoveRepoMemberRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.RemoveRepoMemberRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.RemoveRepoMemberRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.RemoveRepoMemberRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.RemoveRepoMemberRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easylab.v1.RemoveRepoMemberRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.easylab.v1.RemoveRepoMemberRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.easylab.v1.RemoveRepoMemberRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.easylab.v1.RemoveRepoMemberRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easylab.v1.RemoveRepoMemberRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.easylab.v1.RemoveRepoMemberRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code easylab.v1.RemoveRepoMemberRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.easylab.v1.RemoveRepoMemberRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:easylab.v1.RemoveRepoMemberRequest)
      com.easylab.v1.RemoveRepoMemberRequestOrBuilder {
    // Construct using com.easylab.v1.RemoveRepoMemberRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string org = 1 [json_name = "org"];</code>
     * @return The org.
     */
    @java.lang.Override
    public java.lang.String getOrg() {
      return instance.getOrg();
    }
    /**
     * <code>string org = 1 [json_name = "org"];</code>
     * @return The bytes for org.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOrgBytes() {
      return instance.getOrgBytes();
    }
    /**
     * <code>string org = 1 [json_name = "org"];</code>
     * @param value The org to set.
     * @return This builder for chaining.
     */
    public Builder setOrg(
        java.lang.String value) {
      copyOnWrite();
      instance.setOrg(value);
      return this;
    }
    /**
     * <code>string org = 1 [json_name = "org"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOrg() {
      copyOnWrite();
      instance.clearOrg();
      return this;
    }
    /**
     * <code>string org = 1 [json_name = "org"];</code>
     * @param value The bytes for org to set.
     * @return This builder for chaining.
     */
    public Builder setOrgBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setOrgBytes(value);
      return this;
    }

    /**
     * <code>string repo = 2 [json_name = "repo"];</code>
     * @return The repo.
     */
    @java.lang.Override
    public java.lang.String getRepo() {
      return instance.getRepo();
    }
    /**
     * <code>string repo = 2 [json_name = "repo"];</code>
     * @return The bytes for repo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRepoBytes() {
      return instance.getRepoBytes();
    }
    /**
     * <code>string repo = 2 [json_name = "repo"];</code>
     * @param value The repo to set.
     * @return This builder for chaining.
     */
    public Builder setRepo(
        java.lang.String value) {
      copyOnWrite();
      instance.setRepo(value);
      return this;
    }
    /**
     * <code>string repo = 2 [json_name = "repo"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRepo() {
      copyOnWrite();
      instance.clearRepo();
      return this;
    }
    /**
     * <code>string repo = 2 [json_name = "repo"];</code>
     * @param value The bytes for repo to set.
     * @return This builder for chaining.
     */
    public Builder setRepoBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRepoBytes(value);
      return this;
    }

    /**
     * <code>string username = 3 [json_name = "username"];</code>
     * @return The username.
     */
    @java.lang.Override
    public java.lang.String getUsername() {
      return instance.getUsername();
    }
    /**
     * <code>string username = 3 [json_name = "username"];</code>
     * @return The bytes for username.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      return instance.getUsernameBytes();
    }
    /**
     * <code>string username = 3 [json_name = "username"];</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        java.lang.String value) {
      copyOnWrite();
      instance.setUsername(value);
      return this;
    }
    /**
     * <code>string username = 3 [json_name = "username"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      copyOnWrite();
      instance.clearUsername();
      return this;
    }
    /**
     * <code>string username = 3 [json_name = "username"];</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUsernameBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:easylab.v1.RemoveRepoMemberRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.easylab.v1.RemoveRepoMemberRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "org_",
            "repo_",
            "username_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.easylab.v1.RemoveRepoMemberRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.easylab.v1.RemoveRepoMemberRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.easylab.v1.RemoveRepoMemberRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:easylab.v1.RemoveRepoMemberRequest)
  private static final com.easylab.v1.RemoveRepoMemberRequest DEFAULT_INSTANCE;
  static {
    RemoveRepoMemberRequest defaultInstance = new RemoveRepoMemberRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      RemoveRepoMemberRequest.class, defaultInstance);
  }

  public static com.easylab.v1.RemoveRepoMemberRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RemoveRepoMemberRequest> PARSER;

  public static com.google.protobuf.Parser<RemoveRepoMemberRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

