// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easylab.v1;

@kotlin.jvm.JvmName("-initializerevertRequest")
public inline fun revertRequest(block: com.easylab.v1.RevertRequestKt.Dsl.() -> kotlin.Unit): com.easylab.v1.RevertRequest =
  com.easylab.v1.RevertRequestKt.Dsl._create(com.easylab.v1.RevertRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easylab.v1.RevertRequest`
 */
public object RevertRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easylab.v1.RevertRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easylab.v1.RevertRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easylab.v1.RevertRequest = _builder.build()

    /**
     * `string org = 1 [json_name = "org"];`
     */
    public var org: kotlin.String
      @kotlin.jvm.JvmName("getOrg")
        get() = _builder.org
      @kotlin.jvm.JvmName("setOrg")
        set(value) {
        _builder.org = value
      }
    /**
     * `string org = 1 [json_name = "org"];`
     */
    public fun clearOrg() {
      _builder.clearOrg()
    }

    /**
     * `string repo = 2 [json_name = "repo"];`
     */
    public var repo: kotlin.String
      @kotlin.jvm.JvmName("getRepo")
        get() = _builder.repo
      @kotlin.jvm.JvmName("setRepo")
        set(value) {
        _builder.repo = value
      }
    /**
     * `string repo = 2 [json_name = "repo"];`
     */
    public fun clearRepo() {
      _builder.clearRepo()
    }

    /**
     * `string rev = 3 [json_name = "rev"];`
     */
    public var rev: kotlin.String
      @kotlin.jvm.JvmName("getRev")
        get() = _builder.rev
      @kotlin.jvm.JvmName("setRev")
        set(value) {
        _builder.rev = value
      }
    /**
     * `string rev = 3 [json_name = "rev"];`
     */
    public fun clearRev() {
      _builder.clearRev()
    }

    /**
     * `string target = 4 [json_name = "target"];`
     */
    public var target: kotlin.String
      @kotlin.jvm.JvmName("getTarget")
        get() = _builder.target
      @kotlin.jvm.JvmName("setTarget")
        set(value) {
        _builder.target = value
      }
    /**
     * `string target = 4 [json_name = "target"];`
     */
    public fun clearTarget() {
      _builder.clearTarget()
    }
  }
}
public inline fun com.easylab.v1.RevertRequest.copy(block: `com.easylab.v1`.RevertRequestKt.Dsl.() -> kotlin.Unit): com.easylab.v1.RevertRequest =
  `com.easylab.v1`.RevertRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

