// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easylab.v1;

@kotlin.jvm.JvmName("-initializerevisionFile")
public inline fun revisionFile(block: com.easylab.v1.RevisionFileKt.Dsl.() -> kotlin.Unit): com.easylab.v1.RevisionFile =
  com.easylab.v1.RevisionFileKt.Dsl._create(com.easylab.v1.RevisionFile.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easylab.v1.RevisionFile`
 */
public object RevisionFileKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easylab.v1.RevisionFile.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easylab.v1.RevisionFile.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easylab.v1.RevisionFile = _builder.build()

    /**
     * `string path = 1 [json_name = "path"];`
     */
    public var path: kotlin.String
      @kotlin.jvm.JvmName("getPath")
        get() = _builder.path
      @kotlin.jvm.JvmName("setPath")
        set(value) {
        _builder.path = value
      }
    /**
     * `string path = 1 [json_name = "path"];`
     */
    public fun clearPath() {
      _builder.clearPath()
    }

    /**
     * `string mode = 2 [json_name = "mode"];`
     */
    public var mode: kotlin.String
      @kotlin.jvm.JvmName("getMode")
        get() = _builder.mode
      @kotlin.jvm.JvmName("setMode")
        set(value) {
        _builder.mode = value
      }
    /**
     * `string mode = 2 [json_name = "mode"];`
     */
    public fun clearMode() {
      _builder.clearMode()
    }

    /**
     * `string sha = 3 [json_name = "sha"];`
     */
    public var sha: kotlin.String
      @kotlin.jvm.JvmName("getSha")
        get() = _builder.sha
      @kotlin.jvm.JvmName("setSha")
        set(value) {
        _builder.sha = value
      }
    /**
     * `string sha = 3 [json_name = "sha"];`
     */
    public fun clearSha() {
      _builder.clearSha()
    }
  }
}
public inline fun com.easylab.v1.RevisionFile.copy(block: `com.easylab.v1`.RevisionFileKt.Dsl.() -> kotlin.Unit): com.easylab.v1.RevisionFile =
  `com.easylab.v1`.RevisionFileKt.Dsl._create(this.toBuilder()).apply { block() }._build()

