// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto
// Protobuf Java Version: 4.36.1

package com.easylab.v1;

/**
 * Protobuf type {@code easylab.v1.Run}
 */
@com.google.protobuf.Generated
public  final class Run extends
    com.google.protobuf.GeneratedMessageLite<
        Run, Run.Builder> implements
    // @@protoc_insertion_point(message_implements:easylab.v1.Run)
    RunOrBuilder {
  private Run() {
    id_ = "";
    workflowId_ = "";
    status_ = "";
    jobs_ = emptyProtobufList();
    startedAt_ = "";
    finishedAt_ = "";
  }
  public static final int ID_FIELD_NUMBER = 1;
  private java.lang.String id_;
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    return id_;
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(id_);
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @param value The id to set.
   */
  private void setId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    id_ = value;
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   */
  private void clearId() {

    id_ = getDefaultInstance().getId();
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @param value The bytes for id to set.
   */
  private void setIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    id_ = value.toStringUtf8();

  }

  public static final int WORKFLOW_ID_FIELD_NUMBER = 2;
  private java.lang.String workflowId_;
  /**
   * <code>string workflow_id = 2 [json_name = "workflowId"];</code>
   * @return The workflowId.
   */
  @java.lang.Override
  public java.lang.String getWorkflowId() {
    return workflowId_;
  }
  /**
   * <code>string workflow_id = 2 [json_name = "workflowId"];</code>
   * @return The bytes for workflowId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWorkflowIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(workflowId_);
  }
  /**
   * <code>string workflow_id = 2 [json_name = "workflowId"];</code>
   * @param value The workflowId to set.
   */
  private void setWorkflowId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    workflowId_ = value;
  }
  /**
   * <code>string workflow_id = 2 [json_name = "workflowId"];</code>
   */
  private void clearWorkflowId() {

    workflowId_ = getDefaultInstance().getWorkflowId();
  }
  /**
   * <code>string workflow_id = 2 [json_name = "workflowId"];</code>
   * @param value The bytes for workflowId to set.
   */
  private void setWorkflowIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    workflowId_ = value.toStringUtf8();

  }

  public static final int STATUS_FIELD_NUMBER = 3;
  private java.lang.String status_;
  /**
   * <pre>
   * pending | running | success | failure
   * </pre>
   *
   * <code>string status = 3 [json_name = "status"];</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    return status_;
  }
  /**
   * <pre>
   * pending | running | success | failure
   * </pre>
   *
   * <code>string status = 3 [json_name = "status"];</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(status_);
  }
  /**
   * <pre>
   * pending | running | success | failure
   * </pre>
   *
   * <code>string status = 3 [json_name = "status"];</code>
   * @param value The status to set.
   */
  private void setStatus(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    status_ = value;
  }
  /**
   * <pre>
   * pending | running | success | failure
   * </pre>
   *
   * <code>string status = 3 [json_name = "status"];</code>
   */
  private void clearStatus() {

    status_ = getDefaultInstance().getStatus();
  }
  /**
   * <pre>
   * pending | running | success | failure
   * </pre>
   *
   * <code>string status = 3 [json_name = "status"];</code>
   * @param value The bytes for status to set.
   */
  private void setStatusBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    status_ = value.toStringUtf8();

  }

  public static final int JOBS_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.ProtobufList<com.easylab.v1.JobInstance> jobs_;
  /**
   * <code>repeated .easylab.v1.JobInstance jobs = 4 [json_name = "jobs"];</code>
   */
  @java.lang.Override
  public java.util.List<com.easylab.v1.JobInstance> getJobsList() {
    return jobs_;
  }
  /**
   * <code>repeated .easylab.v1.JobInstance jobs = 4 [json_name = "jobs"];</code>
   */
  public java.util.List<? extends com.easylab.v1.JobInstanceOrBuilder> 
      getJobsOrBuilderList() {
    return jobs_;
  }
  /**
   * <code>repeated .easylab.v1.JobInstance jobs = 4 [json_name = "jobs"];</code>
   */
  @java.lang.Override
  public int getJobsCount() {
    return jobs_.size();
  }
  /**
   * <code>repeated .easylab.v1.JobInstance jobs = 4 [json_name = "jobs"];</code>
   */
  @java.lang.Override
  public com.easylab.v1.JobInstance getJobs(int index) {
    return jobs_.get(index);
  }
  /**
   * <code>repeated .easylab.v1.JobInstance jobs = 4 [json_name = "jobs"];</code>
   */
  public com.easylab.v1.JobInstanceOrBuilder getJobsOrBuilder(
      int index) {
    return jobs_.get(index);
  }
  private void ensureJobsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.easylab.v1.JobInstance> tmp = jobs_;
    if (!tmp.isModifiable()) {
      jobs_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .easylab.v1.JobInstance jobs = 4 [json_name = "jobs"];</code>
   */
  private void setJobs(
      int index, com.easylab.v1.JobInstance value) {
    java.util.Objects.requireNonNull(value);
    ensureJobsIsMutable();
    jobs_.set(index, value);
  }
  /**
   * <code>repeated .easylab.v1.JobInstance jobs = 4 [json_name = "jobs"];</code>
   */
  private void addJobs(com.easylab.v1.JobInstance value) {
    java.util.Objects.requireNonNull(value);
    ensureJobsIsMutable();
    jobs_.add(value);
  }
  /**
   * <code>repeated .easylab.v1.JobInstance jobs = 4 [json_name = "jobs"];</code>
   */
  private void addJobs(
      int index, com.easylab.v1.JobInstance value) {
    java.util.Objects.requireNonNull(value);
    ensureJobsIsMutable();
    jobs_.add(index, value);
  }
  /**
   * <code>repeated .easylab.v1.JobInstance jobs = 4 [json_name = "jobs"];</code>
   */
  private void addAllJobs(
      java.lang.Iterable<? extends com.easylab.v1.JobInstance> values) {
    ensureJobsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, jobs_);
  }
  /**
   * <code>repeated .easylab.v1.JobInstance jobs = 4 [json_name = "jobs"];</code>
   */
  private void clearJobs() {
    jobs_ = emptyProtobufList();
  }
  /**
   * <code>repeated .easylab.v1.JobInstance jobs = 4 [json_name = "jobs"];</code>
   */
  private void removeJobs(int index) {
    ensureJobsIsMutable();
    jobs_.remove(index);
  }

  public static final int STARTED_AT_FIELD_NUMBER = 5;
  private java.lang.String startedAt_;
  /**
   * <code>string started_at = 5 [json_name = "startedAt"];</code>
   * @return The startedAt.
   */
  @java.lang.Override
  public java.lang.String getStartedAt() {
    return startedAt_;
  }
  /**
   * <code>string started_at = 5 [json_name = "startedAt"];</code>
   * @return The bytes for startedAt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStartedAtBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(startedAt_);
  }
  /**
   * <code>string started_at = 5 [json_name = "startedAt"];</code>
   * @param value The startedAt to set.
   */
  private void setStartedAt(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    startedAt_ = value;
  }
  /**
   * <code>string started_at = 5 [json_name = "startedAt"];</code>
   */
  private void clearStartedAt() {

    startedAt_ = getDefaultInstance().getStartedAt();
  }
  /**
   * <code>string started_at = 5 [json_name = "startedAt"];</code>
   * @param value The bytes for startedAt to set.
   */
  private void setStartedAtBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    startedAt_ = value.toStringUtf8();

  }

  public static final int FINISHED_AT_FIELD_NUMBER = 6;
  private java.lang.String finishedAt_;
  /**
   * <code>string finished_at = 6 [json_name = "finishedAt"];</code>
   * @return The finishedAt.
   */
  @java.lang.Override
  public java.lang.String getFinishedAt() {
    return finishedAt_;
  }
  /**
   * <code>string finished_at = 6 [json_name = "finishedAt"];</code>
   * @return The bytes for finishedAt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFinishedAtBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(finishedAt_);
  }
  /**
   * <code>string finished_at = 6 [json_name = "finishedAt"];</code>
   * @param value The finishedAt to set.
   */
  private void setFinishedAt(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    finishedAt_ = value;
  }
  /**
   * <code>string finished_at = 6 [json_name = "finishedAt"];</code>
   */
  private void clearFinishedAt() {

    finishedAt_ = getDefaultInstance().getFinishedAt();
  }
  /**
   * <code>string finished_at = 6 [json_name = "finishedAt"];</code>
   * @param value The bytes for finishedAt to set.
   */
  private void setFinishedAtBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    finishedAt_ = value.toStringUtf8();

  }

  public static com.easylab.v1.Run parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.Run parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.Run parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.Run parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.Run parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.Run parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.Run parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easylab.v1.Run parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.easylab.v1.Run parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.easylab.v1.Run parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.easylab.v1.Run parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easylab.v1.Run parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.easylab.v1.Run prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code easylab.v1.Run}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.easylab.v1.Run, Builder> implements
      // @@protoc_insertion_point(builder_implements:easylab.v1.Run)
      com.easylab.v1.RunOrBuilder {
    // Construct using com.easylab.v1.Run.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      return instance.getId();
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return instance.getIdBytes();
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdBytes(value);
      return this;
    }

    /**
     * <code>string workflow_id = 2 [json_name = "workflowId"];</code>
     * @return The workflowId.
     */
    @java.lang.Override
    public java.lang.String getWorkflowId() {
      return instance.getWorkflowId();
    }
    /**
     * <code>string workflow_id = 2 [json_name = "workflowId"];</code>
     * @return The bytes for workflowId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWorkflowIdBytes() {
      return instance.getWorkflowIdBytes();
    }
    /**
     * <code>string workflow_id = 2 [json_name = "workflowId"];</code>
     * @param value The workflowId to set.
     * @return This builder for chaining.
     */
    public Builder setWorkflowId(
        java.lang.String value) {
      copyOnWrite();
      instance.setWorkflowId(value);
      return this;
    }
    /**
     * <code>string workflow_id = 2 [json_name = "workflowId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearWorkflowId() {
      copyOnWrite();
      instance.clearWorkflowId();
      return this;
    }
    /**
     * <code>string workflow_id = 2 [json_name = "workflowId"];</code>
     * @param value The bytes for workflowId to set.
     * @return This builder for chaining.
     */
    public Builder setWorkflowIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setWorkflowIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * pending | running | success | failure
     * </pre>
     *
     * <code>string status = 3 [json_name = "status"];</code>
     * @return The status.
     */
    @java.lang.Override
    public java.lang.String getStatus() {
      return instance.getStatus();
    }
    /**
     * <pre>
     * pending | running | success | failure
     * </pre>
     *
     * <code>string status = 3 [json_name = "status"];</code>
     * @return The bytes for status.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStatusBytes() {
      return instance.getStatusBytes();
    }
    /**
     * <pre>
     * pending | running | success | failure
     * </pre>
     *
     * <code>string status = 3 [json_name = "status"];</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      copyOnWrite();
      instance.setStatus(value);
      return this;
    }
    /**
     * <pre>
     * pending | running | success | failure
     * </pre>
     *
     * <code>string status = 3 [json_name = "status"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      copyOnWrite();
      instance.clearStatus();
      return this;
    }
    /**
     * <pre>
     * pending | running | success | failure
     * </pre>
     *
     * <code>string status = 3 [json_name = "status"];</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setStatusBytes(value);
      return this;
    }

    /**
     * <code>repeated .easylab.v1.JobInstance jobs = 4 [json_name = "jobs"];</code>
     */
    @java.lang.Override
    public java.util.List<com.easylab.v1.JobInstance> getJobsList() {
      return java.util.Collections.unmodifiableList(
          instance.getJobsList());
    }
    /**
     * <code>repeated .easylab.v1.JobInstance jobs = 4 [json_name = "jobs"];</code>
     */
    @java.lang.Override
    public int getJobsCount() {
      return instance.getJobsCount();
    }/**
     * <code>repeated .easylab.v1.JobInstance jobs = 4 [json_name = "jobs"];</code>
     */
    @java.lang.Override
    public com.easylab.v1.JobInstance getJobs(int index) {
      return instance.getJobs(index);
    }
    /**
     * <code>repeated .easylab.v1.JobInstance jobs = 4 [json_name = "jobs"];</code>
     */
    public Builder setJobs(
        int index, com.easylab.v1.JobInstance value) {
      copyOnWrite();
      instance.setJobs(index, value);
      return this;
    }
    /**
     * <code>repeated .easylab.v1.JobInstance jobs = 4 [json_name = "jobs"];</code>
     */
    public Builder setJobs(
        int index, com.easylab.v1.JobInstance.Builder builderForValue) {
      copyOnWrite();
      instance.setJobs(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .easylab.v1.JobInstance jobs = 4 [json_name = "jobs"];</code>
     */
    public Builder addJobs(com.easylab.v1.JobInstance value) {
      copyOnWrite();
      instance.addJobs(value);
      return this;
    }
    /**
     * <code>repeated .easylab.v1.JobInstance jobs = 4 [json_name = "jobs"];</code>
     */
    public Builder addJobs(
        int index, com.easylab.v1.JobInstance value) {
      copyOnWrite();
      instance.addJobs(index, value);
      return this;
    }
    /**
     * <code>repeated .easylab.v1.JobInstance jobs = 4 [json_name = "jobs"];</code>
     */
    public Builder addJobs(
        com.easylab.v1.JobInstance.Builder builderForValue) {
      copyOnWrite();
      instance.addJobs(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .easylab.v1.JobInstance jobs = 4 [json_name = "jobs"];</code>
     */
    public Builder addJobs(
        int index, com.easylab.v1.JobInstance.Builder builderForValue) {
      copyOnWrite();
      instance.addJobs(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .easylab.v1.JobInstance jobs = 4 [json_name = "jobs"];</code>
     */
    public Builder addAllJobs(
        java.lang.Iterable<? extends com.easylab.v1.JobInstance> values) {
      copyOnWrite();
      instance.addAllJobs(values);
      return this;
    }
    /**
     * <code>repeated .easylab.v1.JobInstance jobs = 4 [json_name = "jobs"];</code>
     */
    public Builder clearJobs() {
      copyOnWrite();
      instance.clearJobs();
      return this;
    }
    /**
     * <code>repeated .easylab.v1.JobInstance jobs = 4 [json_name = "jobs"];</code>
     */
    public Builder removeJobs(int index) {
      copyOnWrite();
      instance.removeJobs(index);
      return this;
    }

    /**
     * <code>string started_at = 5 [json_name = "startedAt"];</code>
     * @return The startedAt.
     */
    @java.lang.Override
    public java.lang.String getStartedAt() {
      return instance.getStartedAt();
    }
    /**
     * <code>string started_at = 5 [json_name = "startedAt"];</code>
     * @return The bytes for startedAt.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStartedAtBytes() {
      return instance.getStartedAtBytes();
    }
    /**
     * <code>string started_at = 5 [json_name = "startedAt"];</code>
     * @param value The startedAt to set.
     * @return This builder for chaining.
     */
    public Builder setStartedAt(
        java.lang.String value) {
      copyOnWrite();
      instance.setStartedAt(value);
      return this;
    }
    /**
     * <code>string started_at = 5 [json_name = "startedAt"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStartedAt() {
      copyOnWrite();
      instance.clearStartedAt();
      return this;
    }
    /**
     * <code>string started_at = 5 [json_name = "startedAt"];</code>
     * @param value The bytes for startedAt to set.
     * @return This builder for chaining.
     */
    public Builder setStartedAtBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setStartedAtBytes(value);
      return this;
    }

    /**
     * <code>string finished_at = 6 [json_name = "finishedAt"];</code>
     * @return The finishedAt.
     */
    @java.lang.Override
    public java.lang.String getFinishedAt() {
      return instance.getFinishedAt();
    }
    /**
     * <code>string finished_at = 6 [json_name = "finishedAt"];</code>
     * @return The bytes for finishedAt.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFinishedAtBytes() {
      return instance.getFinishedAtBytes();
    }
    /**
     * <code>string finished_at = 6 [json_name = "finishedAt"];</code>
     * @param value The finishedAt to set.
     * @return This builder for chaining.
     */
    public Builder setFinishedAt(
        java.lang.String value) {
      copyOnWrite();
      instance.setFinishedAt(value);
      return this;
    }
    /**
     * <code>string finished_at = 6 [json_name = "finishedAt"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFinishedAt() {
      copyOnWrite();
      instance.clearFinishedAt();
      return this;
    }
    /**
     * <code>string finished_at = 6 [json_name = "finishedAt"];</code>
     * @param value The bytes for finishedAt to set.
     * @return This builder for chaining.
     */
    public Builder setFinishedAtBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFinishedAtBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:easylab.v1.Run)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.easylab.v1.Run();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "id_",
            "workflowId_",
            "status_",
            "jobs_",
            com.easylab.v1.JobInstance.class,
            "startedAt_",
            "finishedAt_",
          };
          java.lang.String info =
              "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0001\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u001b\u0005\u0208\u0006\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.easylab.v1.Run> parser = PARSER;
        if (parser == null) {
          synchronized (com.easylab.v1.Run.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.easylab.v1.Run>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:easylab.v1.Run)
  private static final com.easylab.v1.Run DEFAULT_INSTANCE;
  static {
    Run defaultInstance = new Run();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Run.class, defaultInstance);
  }

  public static com.easylab.v1.Run getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Run> PARSER;

  public static com.google.protobuf.Parser<Run> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

