// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package easylab.v1;

@kotlin.jvm.JvmName("-initializerunJobLogRequest")
public inline fun runJobLogRequest(block: easylab.v1.RunJobLogRequestKt.Dsl.() -> kotlin.Unit): easylab.v1.Easylab.RunJobLogRequest =
  easylab.v1.RunJobLogRequestKt.Dsl._create(easylab.v1.Easylab.RunJobLogRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easylab.v1.RunJobLogRequest`
 */
public object RunJobLogRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: easylab.v1.Easylab.RunJobLogRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: easylab.v1.Easylab.RunJobLogRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): easylab.v1.Easylab.RunJobLogRequest = _builder.build()

    /**
     * `string run_id = 1 [json_name = "runId"];`
     */
    public var runId: kotlin.String
      @kotlin.jvm.JvmName("getRunId")
        get() = _builder.runId
      @kotlin.jvm.JvmName("setRunId")
        set(value) {
        _builder.runId = value
      }
    /**
     * `string run_id = 1 [json_name = "runId"];`
     */
    public fun clearRunId() {
      _builder.clearRunId()
    }

    /**
     * `string job_id = 2 [json_name = "jobId"];`
     */
    public var jobId: kotlin.String
      @kotlin.jvm.JvmName("getJobId")
        get() = _builder.jobId
      @kotlin.jvm.JvmName("setJobId")
        set(value) {
        _builder.jobId = value
      }
    /**
     * `string job_id = 2 [json_name = "jobId"];`
     */
    public fun clearJobId() {
      _builder.clearJobId()
    }
  }
}
public inline fun easylab.v1.Easylab.RunJobLogRequest.copy(block: `easylab.v1`.RunJobLogRequestKt.Dsl.() -> kotlin.Unit): easylab.v1.Easylab.RunJobLogRequest =
  `easylab.v1`.RunJobLogRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

