// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easylab.v1;

@kotlin.jvm.JvmName("-initializerunner")
public inline fun runner(block: com.easylab.v1.RunnerKt.Dsl.() -> kotlin.Unit): com.easylab.v1.Runner =
  com.easylab.v1.RunnerKt.Dsl._create(com.easylab.v1.Runner.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easylab.v1.Runner`
 */
public object RunnerKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easylab.v1.Runner.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easylab.v1.Runner.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easylab.v1.Runner = _builder.build()

    /**
     * `string id = 1 [json_name = "id"];`
     */
    public var id: kotlin.String
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * `string id = 1 [json_name = "id"];`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class LabelsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * os=linux|windows|macos, arch=, is_container=, toolchain=
     * ```
     *
     * `repeated string labels = 2 [json_name = "labels"];`
     * @return A list containing the labels.
     */
    public val labels: com.google.protobuf.kotlin.DslList<kotlin.String, LabelsProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.labelsList
      )
    /**
     * ```
     * os=linux|windows|macos, arch=, is_container=, toolchain=
     * ```
     *
     * `repeated string labels = 2 [json_name = "labels"];`
     * @param value The labels to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addLabels")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, LabelsProxy>.add(value: kotlin.String) {
      _builder.addLabels(value)
    }
    /**
     * ```
     * os=linux|windows|macos, arch=, is_container=, toolchain=
     * ```
     *
     * `repeated string labels = 2 [json_name = "labels"];`
     * @param value The labels to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignLabels")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, LabelsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * ```
     * os=linux|windows|macos, arch=, is_container=, toolchain=
     * ```
     *
     * `repeated string labels = 2 [json_name = "labels"];`
     * @param values The labels to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllLabels")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, LabelsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllLabels(values)
    }
    /**
     * ```
     * os=linux|windows|macos, arch=, is_container=, toolchain=
     * ```
     *
     * `repeated string labels = 2 [json_name = "labels"];`
     * @param values The labels to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllLabels")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, LabelsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * ```
     * os=linux|windows|macos, arch=, is_container=, toolchain=
     * ```
     *
     * `repeated string labels = 2 [json_name = "labels"];`
     * @param index The index to set the value at.
     * @param value The labels to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setLabels")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, LabelsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setLabels(index, value)
    }/**
     * ```
     * os=linux|windows|macos, arch=, is_container=, toolchain=
     * ```
     *
     * `repeated string labels = 2 [json_name = "labels"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setLabels")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, LabelsProxy>.clear() {
      _builder.clearLabels()
    }
    /**
     * ```
     * podman | host
     * ```
     *
     * `string backend = 3 [json_name = "backend"];`
     */
    public var backend: kotlin.String
      @kotlin.jvm.JvmName("getBackend")
        get() = _builder.backend
      @kotlin.jvm.JvmName("setBackend")
        set(value) {
        _builder.backend = value
      }
    /**
     * ```
     * podman | host
     * ```
     *
     * `string backend = 3 [json_name = "backend"];`
     */
    public fun clearBackend() {
      _builder.clearBackend()
    }

    /**
     * ```
     * host runner dial address
     * ```
     *
     * `string addr = 4 [json_name = "addr"];`
     */
    public var addr: kotlin.String
      @kotlin.jvm.JvmName("getAddr")
        get() = _builder.addr
      @kotlin.jvm.JvmName("setAddr")
        set(value) {
        _builder.addr = value
      }
    /**
     * ```
     * host runner dial address
     * ```
     *
     * `string addr = 4 [json_name = "addr"];`
     */
    public fun clearAddr() {
      _builder.clearAddr()
    }

    /**
     * ```
     * heartbeat unix millis
     * ```
     *
     * `int64 last_seen = 5 [json_name = "lastSeen"];`
     */
    public var lastSeen: kotlin.Long
      @kotlin.jvm.JvmName("getLastSeen")
        get() = _builder.lastSeen
      @kotlin.jvm.JvmName("setLastSeen")
        set(value) {
        _builder.lastSeen = value
      }
    /**
     * ```
     * heartbeat unix millis
     * ```
     *
     * `int64 last_seen = 5 [json_name = "lastSeen"];`
     */
    public fun clearLastSeen() {
      _builder.clearLastSeen()
    }

    /**
     * ```
     * true = sandbox worker (not in CI pool)
     * ```
     *
     * `bool session_bound = 6 [json_name = "sessionBound"];`
     */
    public var sessionBound: kotlin.Boolean
      @kotlin.jvm.JvmName("getSessionBound")
        get() = _builder.sessionBound
      @kotlin.jvm.JvmName("setSessionBound")
        set(value) {
        _builder.sessionBound = value
      }
    /**
     * ```
     * true = sandbox worker (not in CI pool)
     * ```
     *
     * `bool session_bound = 6 [json_name = "sessionBound"];`
     */
    public fun clearSessionBound() {
      _builder.clearSessionBound()
    }
  }
}
public inline fun com.easylab.v1.Runner.copy(block: `com.easylab.v1`.RunnerKt.Dsl.() -> kotlin.Unit): com.easylab.v1.Runner =
  `com.easylab.v1`.RunnerKt.Dsl._create(this.toBuilder()).apply { block() }._build()

