// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto
// Protobuf Java Version: 4.36.1

package com.easylab.v1;

/**
 * Protobuf type {@code easylab.v1.Runner}
 */
@com.google.protobuf.Generated
public  final class Runner extends
    com.google.protobuf.GeneratedMessageLite<
        Runner, Runner.Builder> implements
    // @@protoc_insertion_point(message_implements:easylab.v1.Runner)
    RunnerOrBuilder {
  private Runner() {
    id_ = "";
    labels_ = emptyProtobufList();
    backend_ = "";
    addr_ = "";
  }
  public static final int ID_FIELD_NUMBER = 1;
  private java.lang.String id_;
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    return id_;
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(id_);
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @param value The id to set.
   */
  private void setId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    id_ = value;
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   */
  private void clearId() {

    id_ = getDefaultInstance().getId();
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @param value The bytes for id to set.
   */
  private void setIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    id_ = value.toStringUtf8();

  }

  public static final int LABELS_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> labels_;
  /**
   * <pre>
   * os=linux|windows|macos, arch=, is_container=, toolchain=
   * </pre>
   *
   * <code>repeated string labels = 2 [json_name = "labels"];</code>
   * @return A list containing the labels.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getLabelsList() {
    return labels_;
  }
  /**
   * <pre>
   * os=linux|windows|macos, arch=, is_container=, toolchain=
   * </pre>
   *
   * <code>repeated string labels = 2 [json_name = "labels"];</code>
   * @return The count of labels.
   */
  @java.lang.Override
  public int getLabelsCount() {
    return labels_.size();
  }
  /**
   * <pre>
   * os=linux|windows|macos, arch=, is_container=, toolchain=
   * </pre>
   *
   * <code>repeated string labels = 2 [json_name = "labels"];</code>
   * @param index The index of the element to return.
   * @return The labels at the given index.
   */
  @java.lang.Override
  public java.lang.String getLabels(int index) {
    return labels_.get(index);
  }
  /**
   * <pre>
   * os=linux|windows|macos, arch=, is_container=, toolchain=
   * </pre>
   *
   * <code>repeated string labels = 2 [json_name = "labels"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the labels at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLabelsBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        labels_.get(index));
  }
  private void ensureLabelsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        labels_;  if (!tmp.isModifiable()) {
      labels_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <pre>
   * os=linux|windows|macos, arch=, is_container=, toolchain=
   * </pre>
   *
   * <code>repeated string labels = 2 [json_name = "labels"];</code>
   * @param index The index to set the value at.
   * @param value The labels to set.
   */
  private void setLabels(
      int index, java.lang.String value) {
    java.util.Objects.requireNonNull(value);
    ensureLabelsIsMutable();
    labels_.set(index, value);
  }
  /**
   * <pre>
   * os=linux|windows|macos, arch=, is_container=, toolchain=
   * </pre>
   *
   * <code>repeated string labels = 2 [json_name = "labels"];</code>
   * @param value The labels to add.
   */
  private void addLabels(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);
    ensureLabelsIsMutable();
    labels_.add(value);
  }
  /**
   * <pre>
   * os=linux|windows|macos, arch=, is_container=, toolchain=
   * </pre>
   *
   * <code>repeated string labels = 2 [json_name = "labels"];</code>
   * @param values The labels to add.
   */
  private void addAllLabels(
      java.lang.Iterable<java.lang.String> values) {
    ensureLabelsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, labels_);
  }
  /**
   * <pre>
   * os=linux|windows|macos, arch=, is_container=, toolchain=
   * </pre>
   *
   * <code>repeated string labels = 2 [json_name = "labels"];</code>
   */
  private void clearLabels() {
    labels_ = emptyProtobufList();
  }
  /**
   * <pre>
   * os=linux|windows|macos, arch=, is_container=, toolchain=
   * </pre>
   *
   * <code>repeated string labels = 2 [json_name = "labels"];</code>
   * @param value The bytes of the labels to add.
   */
  private void addLabelsBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureLabelsIsMutable();
    labels_.add(value.toStringUtf8());
  }

  public static final int BACKEND_FIELD_NUMBER = 3;
  private java.lang.String backend_;
  /**
   * <pre>
   * podman | host
   * </pre>
   *
   * <code>string backend = 3 [json_name = "backend"];</code>
   * @return The backend.
   */
  @java.lang.Override
  public java.lang.String getBackend() {
    return backend_;
  }
  /**
   * <pre>
   * podman | host
   * </pre>
   *
   * <code>string backend = 3 [json_name = "backend"];</code>
   * @return The bytes for backend.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBackendBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(backend_);
  }
  /**
   * <pre>
   * podman | host
   * </pre>
   *
   * <code>string backend = 3 [json_name = "backend"];</code>
   * @param value The backend to set.
   */
  private void setBackend(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    backend_ = value;
  }
  /**
   * <pre>
   * podman | host
   * </pre>
   *
   * <code>string backend = 3 [json_name = "backend"];</code>
   */
  private void clearBackend() {

    backend_ = getDefaultInstance().getBackend();
  }
  /**
   * <pre>
   * podman | host
   * </pre>
   *
   * <code>string backend = 3 [json_name = "backend"];</code>
   * @param value The bytes for backend to set.
   */
  private void setBackendBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    backend_ = value.toStringUtf8();

  }

  public static final int ADDR_FIELD_NUMBER = 4;
  private java.lang.String addr_;
  /**
   * <pre>
   * host runner dial address
   * </pre>
   *
   * <code>string addr = 4 [json_name = "addr"];</code>
   * @return The addr.
   */
  @java.lang.Override
  public java.lang.String getAddr() {
    return addr_;
  }
  /**
   * <pre>
   * host runner dial address
   * </pre>
   *
   * <code>string addr = 4 [json_name = "addr"];</code>
   * @return The bytes for addr.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAddrBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(addr_);
  }
  /**
   * <pre>
   * host runner dial address
   * </pre>
   *
   * <code>string addr = 4 [json_name = "addr"];</code>
   * @param value The addr to set.
   */
  private void setAddr(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    addr_ = value;
  }
  /**
   * <pre>
   * host runner dial address
   * </pre>
   *
   * <code>string addr = 4 [json_name = "addr"];</code>
   */
  private void clearAddr() {

    addr_ = getDefaultInstance().getAddr();
  }
  /**
   * <pre>
   * host runner dial address
   * </pre>
   *
   * <code>string addr = 4 [json_name = "addr"];</code>
   * @param value The bytes for addr to set.
   */
  private void setAddrBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    addr_ = value.toStringUtf8();

  }

  public static final int LAST_SEEN_FIELD_NUMBER = 5;
  private long lastSeen_;
  /**
   * <pre>
   * heartbeat unix millis
   * </pre>
   *
   * <code>int64 last_seen = 5 [json_name = "lastSeen"];</code>
   * @return The lastSeen.
   */
  @java.lang.Override
  public long getLastSeen() {
    return lastSeen_;
  }
  /**
   * <pre>
   * heartbeat unix millis
   * </pre>
   *
   * <code>int64 last_seen = 5 [json_name = "lastSeen"];</code>
   * @param value The lastSeen to set.
   */
  private void setLastSeen(long value) {
    
    lastSeen_ = value;
  }
  /**
   * <pre>
   * heartbeat unix millis
   * </pre>
   *
   * <code>int64 last_seen = 5 [json_name = "lastSeen"];</code>
   */
  private void clearLastSeen() {

    lastSeen_ = 0L;
  }

  public static final int SESSION_BOUND_FIELD_NUMBER = 6;
  private boolean sessionBound_;
  /**
   * <pre>
   * true = sandbox worker (not in CI pool)
   * </pre>
   *
   * <code>bool session_bound = 6 [json_name = "sessionBound"];</code>
   * @return The sessionBound.
   */
  @java.lang.Override
  public boolean getSessionBound() {
    return sessionBound_;
  }
  /**
   * <pre>
   * true = sandbox worker (not in CI pool)
   * </pre>
   *
   * <code>bool session_bound = 6 [json_name = "sessionBound"];</code>
   * @param value The sessionBound to set.
   */
  private void setSessionBound(boolean value) {
    
    sessionBound_ = value;
  }
  /**
   * <pre>
   * true = sandbox worker (not in CI pool)
   * </pre>
   *
   * <code>bool session_bound = 6 [json_name = "sessionBound"];</code>
   */
  private void clearSessionBound() {

    sessionBound_ = false;
  }

  public static com.easylab.v1.Runner parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.Runner parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.Runner parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.Runner parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.Runner parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.easylab.v1.Runner parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.easylab.v1.Runner parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easylab.v1.Runner parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.easylab.v1.Runner parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.easylab.v1.Runner parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.easylab.v1.Runner parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.easylab.v1.Runner parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.easylab.v1.Runner prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code easylab.v1.Runner}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.easylab.v1.Runner, Builder> implements
      // @@protoc_insertion_point(builder_implements:easylab.v1.Runner)
      com.easylab.v1.RunnerOrBuilder {
    // Construct using com.easylab.v1.Runner.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      return instance.getId();
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return instance.getIdBytes();
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * os=linux|windows|macos, arch=, is_container=, toolchain=
     * </pre>
     *
     * <code>repeated string labels = 2 [json_name = "labels"];</code>
     * @return A list containing the labels.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getLabelsList() {
      return java.util.Collections.unmodifiableList(
          instance.getLabelsList());
    }
    /**
     * <pre>
     * os=linux|windows|macos, arch=, is_container=, toolchain=
     * </pre>
     *
     * <code>repeated string labels = 2 [json_name = "labels"];</code>
     * @return The count of labels.
     */
    @java.lang.Override
    public int getLabelsCount() {
      return instance.getLabelsCount();
    }
    /**
     * <pre>
     * os=linux|windows|macos, arch=, is_container=, toolchain=
     * </pre>
     *
     * <code>repeated string labels = 2 [json_name = "labels"];</code>
     * @param index The index of the element to return.
     * @return The labels at the given index.
     */
    @java.lang.Override
    public java.lang.String getLabels(int index) {
      return instance.getLabels(index);
    }
    /**
     * <pre>
     * os=linux|windows|macos, arch=, is_container=, toolchain=
     * </pre>
     *
     * <code>repeated string labels = 2 [json_name = "labels"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the labels at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLabelsBytes(int index) {
      return instance.getLabelsBytes(index);
    }
    /**
     * <pre>
     * os=linux|windows|macos, arch=, is_container=, toolchain=
     * </pre>
     *
     * <code>repeated string labels = 2 [json_name = "labels"];</code>
     * @param index The index to set the value at.
     * @param value The labels to set.
     * @return This builder for chaining.
     */
    public Builder setLabels(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setLabels(index, value);
      return this;
    }
    /**
     * <pre>
     * os=linux|windows|macos, arch=, is_container=, toolchain=
     * </pre>
     *
     * <code>repeated string labels = 2 [json_name = "labels"];</code>
     * @param value The labels to add.
     * @return This builder for chaining.
     */
    public Builder addLabels(
        java.lang.String value) {
      copyOnWrite();
      instance.addLabels(value);
      return this;
    }
    /**
     * <pre>
     * os=linux|windows|macos, arch=, is_container=, toolchain=
     * </pre>
     *
     * <code>repeated string labels = 2 [json_name = "labels"];</code>
     * @param values The labels to add.
     * @return This builder for chaining.
     */
    public Builder addAllLabels(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllLabels(values);
      return this;
    }
    /**
     * <pre>
     * os=linux|windows|macos, arch=, is_container=, toolchain=
     * </pre>
     *
     * <code>repeated string labels = 2 [json_name = "labels"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLabels() {
      copyOnWrite();
      instance.clearLabels();
      return this;
    }
    /**
     * <pre>
     * os=linux|windows|macos, arch=, is_container=, toolchain=
     * </pre>
     *
     * <code>repeated string labels = 2 [json_name = "labels"];</code>
     * @param value The bytes of the labels to add.
     * @return This builder for chaining.
     */
    public Builder addLabelsBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addLabelsBytes(value);
      return this;
    }

    /**
     * <pre>
     * podman | host
     * </pre>
     *
     * <code>string backend = 3 [json_name = "backend"];</code>
     * @return The backend.
     */
    @java.lang.Override
    public java.lang.String getBackend() {
      return instance.getBackend();
    }
    /**
     * <pre>
     * podman | host
     * </pre>
     *
     * <code>string backend = 3 [json_name = "backend"];</code>
     * @return The bytes for backend.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBackendBytes() {
      return instance.getBackendBytes();
    }
    /**
     * <pre>
     * podman | host
     * </pre>
     *
     * <code>string backend = 3 [json_name = "backend"];</code>
     * @param value The backend to set.
     * @return This builder for chaining.
     */
    public Builder setBackend(
        java.lang.String value) {
      copyOnWrite();
      instance.setBackend(value);
      return this;
    }
    /**
     * <pre>
     * podman | host
     * </pre>
     *
     * <code>string backend = 3 [json_name = "backend"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBackend() {
      copyOnWrite();
      instance.clearBackend();
      return this;
    }
    /**
     * <pre>
     * podman | host
     * </pre>
     *
     * <code>string backend = 3 [json_name = "backend"];</code>
     * @param value The bytes for backend to set.
     * @return This builder for chaining.
     */
    public Builder setBackendBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setBackendBytes(value);
      return this;
    }

    /**
     * <pre>
     * host runner dial address
     * </pre>
     *
     * <code>string addr = 4 [json_name = "addr"];</code>
     * @return The addr.
     */
    @java.lang.Override
    public java.lang.String getAddr() {
      return instance.getAddr();
    }
    /**
     * <pre>
     * host runner dial address
     * </pre>
     *
     * <code>string addr = 4 [json_name = "addr"];</code>
     * @return The bytes for addr.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddrBytes() {
      return instance.getAddrBytes();
    }
    /**
     * <pre>
     * host runner dial address
     * </pre>
     *
     * <code>string addr = 4 [json_name = "addr"];</code>
     * @param value The addr to set.
     * @return This builder for chaining.
     */
    public Builder setAddr(
        java.lang.String value) {
      copyOnWrite();
      instance.setAddr(value);
      return this;
    }
    /**
     * <pre>
     * host runner dial address
     * </pre>
     *
     * <code>string addr = 4 [json_name = "addr"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAddr() {
      copyOnWrite();
      instance.clearAddr();
      return this;
    }
    /**
     * <pre>
     * host runner dial address
     * </pre>
     *
     * <code>string addr = 4 [json_name = "addr"];</code>
     * @param value The bytes for addr to set.
     * @return This builder for chaining.
     */
    public Builder setAddrBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAddrBytes(value);
      return this;
    }

    /**
     * <pre>
     * heartbeat unix millis
     * </pre>
     *
     * <code>int64 last_seen = 5 [json_name = "lastSeen"];</code>
     * @return The lastSeen.
     */
    @java.lang.Override
    public long getLastSeen() {
      return instance.getLastSeen();
    }
    /**
     * <pre>
     * heartbeat unix millis
     * </pre>
     *
     * <code>int64 last_seen = 5 [json_name = "lastSeen"];</code>
     * @param value The lastSeen to set.
     * @return This builder for chaining.
     */
    public Builder setLastSeen(long value) {
      copyOnWrite();
      instance.setLastSeen(value);
      return this;
    }
    /**
     * <pre>
     * heartbeat unix millis
     * </pre>
     *
     * <code>int64 last_seen = 5 [json_name = "lastSeen"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLastSeen() {
      copyOnWrite();
      instance.clearLastSeen();
      return this;
    }

    /**
     * <pre>
     * true = sandbox worker (not in CI pool)
     * </pre>
     *
     * <code>bool session_bound = 6 [json_name = "sessionBound"];</code>
     * @return The sessionBound.
     */
    @java.lang.Override
    public boolean getSessionBound() {
      return instance.getSessionBound();
    }
    /**
     * <pre>
     * true = sandbox worker (not in CI pool)
     * </pre>
     *
     * <code>bool session_bound = 6 [json_name = "sessionBound"];</code>
     * @param value The sessionBound to set.
     * @return This builder for chaining.
     */
    public Builder setSessionBound(boolean value) {
      copyOnWrite();
      instance.setSessionBound(value);
      return this;
    }
    /**
     * <pre>
     * true = sandbox worker (not in CI pool)
     * </pre>
     *
     * <code>bool session_bound = 6 [json_name = "sessionBound"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionBound() {
      copyOnWrite();
      instance.clearSessionBound();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:easylab.v1.Runner)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.easylab.v1.Runner();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "id_",
            "labels_",
            "backend_",
            "addr_",
            "lastSeen_",
            "sessionBound_",
          };
          java.lang.String info =
              "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0001\u0000\u0001\u0208\u0002\u021a" +
              "\u0003\u0208\u0004\u0208\u0005\u0002\u0006\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.easylab.v1.Runner> parser = PARSER;
        if (parser == null) {
          synchronized (com.easylab.v1.Runner.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.easylab.v1.Runner>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:easylab.v1.Runner)
  private static final com.easylab.v1.Runner DEFAULT_INSTANCE;
  static {
    Runner defaultInstance = new Runner();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Runner.class, defaultInstance);
  }

  public static com.easylab.v1.Runner getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Runner> PARSER;

  public static com.google.protobuf.Parser<Runner> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

