// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easylab.v1;

@kotlin.jvm.JvmName("-initializescaleServiceRequest")
public inline fun scaleServiceRequest(block: com.easylab.v1.ScaleServiceRequestKt.Dsl.() -> kotlin.Unit): com.easylab.v1.ScaleServiceRequest =
  com.easylab.v1.ScaleServiceRequestKt.Dsl._create(com.easylab.v1.ScaleServiceRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easylab.v1.ScaleServiceRequest`
 */
public object ScaleServiceRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easylab.v1.ScaleServiceRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easylab.v1.ScaleServiceRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easylab.v1.ScaleServiceRequest = _builder.build()

    /**
     * `string name = 1 [json_name = "name"];`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 1 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `int32 replicas = 2 [json_name = "replicas"];`
     */
    public var replicas: kotlin.Int
      @kotlin.jvm.JvmName("getReplicas")
        get() = _builder.replicas
      @kotlin.jvm.JvmName("setReplicas")
        set(value) {
        _builder.replicas = value
      }
    /**
     * `int32 replicas = 2 [json_name = "replicas"];`
     */
    public fun clearReplicas() {
      _builder.clearReplicas()
    }
  }
}
public inline fun com.easylab.v1.ScaleServiceRequest.copy(block: `com.easylab.v1`.ScaleServiceRequestKt.Dsl.() -> kotlin.Unit): com.easylab.v1.ScaleServiceRequest =
  `com.easylab.v1`.ScaleServiceRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

