// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easylab.v1;

@kotlin.jvm.JvmName("-initializesearchRequest")
public inline fun searchRequest(block: com.easylab.v1.SearchRequestKt.Dsl.() -> kotlin.Unit): com.easylab.v1.SearchRequest =
  com.easylab.v1.SearchRequestKt.Dsl._create(com.easylab.v1.SearchRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easylab.v1.SearchRequest`
 */
public object SearchRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easylab.v1.SearchRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easylab.v1.SearchRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easylab.v1.SearchRequest = _builder.build()

    /**
     * `string org = 1 [json_name = "org"];`
     */
    public var org: kotlin.String
      @kotlin.jvm.JvmName("getOrg")
        get() = _builder.org
      @kotlin.jvm.JvmName("setOrg")
        set(value) {
        _builder.org = value
      }
    /**
     * `string org = 1 [json_name = "org"];`
     */
    public fun clearOrg() {
      _builder.clearOrg()
    }

    /**
     * `string repo = 2 [json_name = "repo"];`
     */
    public var repo: kotlin.String
      @kotlin.jvm.JvmName("getRepo")
        get() = _builder.repo
      @kotlin.jvm.JvmName("setRepo")
        set(value) {
        _builder.repo = value
      }
    /**
     * `string repo = 2 [json_name = "repo"];`
     */
    public fun clearRepo() {
      _builder.clearRepo()
    }

    /**
     * `string ref = 3 [json_name = "ref"];`
     */
    public var ref: kotlin.String
      @kotlin.jvm.JvmName("getRef")
        get() = _builder.ref
      @kotlin.jvm.JvmName("setRef")
        set(value) {
        _builder.ref = value
      }
    /**
     * `string ref = 3 [json_name = "ref"];`
     */
    public fun clearRef() {
      _builder.clearRef()
    }

    /**
     * `string q = 4 [json_name = "q"];`
     */
    public var q: kotlin.String
      @kotlin.jvm.JvmName("getQ")
        get() = _builder.q
      @kotlin.jvm.JvmName("setQ")
        set(value) {
        _builder.q = value
      }
    /**
     * `string q = 4 [json_name = "q"];`
     */
    public fun clearQ() {
      _builder.clearQ()
    }
  }
}
public inline fun com.easylab.v1.SearchRequest.copy(block: `com.easylab.v1`.SearchRequestKt.Dsl.() -> kotlin.Unit): com.easylab.v1.SearchRequest =
  `com.easylab.v1`.SearchRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

