// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto
// Protobuf Java Version: 4.36.1

package com.easylab.v1;

@com.google.protobuf.Generated
public interface SquashRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:easylab.v1.SquashRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string org = 1 [json_name = "org"];</code>
   * @return The org.
   */
  java.lang.String getOrg();
  /**
   * <code>string org = 1 [json_name = "org"];</code>
   * @return The bytes for org.
   */
  com.google.protobuf.ByteString
      getOrgBytes();

  /**
   * <code>string repo = 2 [json_name = "repo"];</code>
   * @return The repo.
   */
  java.lang.String getRepo();
  /**
   * <code>string repo = 2 [json_name = "repo"];</code>
   * @return The bytes for repo.
   */
  com.google.protobuf.ByteString
      getRepoBytes();

  /**
   * <code>string rev = 3 [json_name = "rev"];</code>
   * @return The rev.
   */
  java.lang.String getRev();
  /**
   * <code>string rev = 3 [json_name = "rev"];</code>
   * @return The bytes for rev.
   */
  com.google.protobuf.ByteString
      getRevBytes();

  /**
   * <code>string message = 4 [json_name = "message"];</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 4 [json_name = "message"];</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
