// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easylab.v1;

@kotlin.jvm.JvmName("-initializesquashResponse")
public inline fun squashResponse(block: com.easylab.v1.SquashResponseKt.Dsl.() -> kotlin.Unit): com.easylab.v1.SquashResponse =
  com.easylab.v1.SquashResponseKt.Dsl._create(com.easylab.v1.SquashResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easylab.v1.SquashResponse`
 */
public object SquashResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easylab.v1.SquashResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easylab.v1.SquashResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easylab.v1.SquashResponse = _builder.build()

    /**
     * `bool ok = 1 [json_name = "ok"];`
     */
    public var ok: kotlin.Boolean
      @kotlin.jvm.JvmName("getOk")
        get() = _builder.ok
      @kotlin.jvm.JvmName("setOk")
        set(value) {
        _builder.ok = value
      }
    /**
     * `bool ok = 1 [json_name = "ok"];`
     */
    public fun clearOk() {
      _builder.clearOk()
    }

    /**
     * `string error = 2 [json_name = "error"];`
     */
    public var error: kotlin.String
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `string error = 2 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }

    /**
     * `string revision_id = 3 [json_name = "revisionId"];`
     */
    public var revisionId: kotlin.String
      @kotlin.jvm.JvmName("getRevisionId")
        get() = _builder.revisionId
      @kotlin.jvm.JvmName("setRevisionId")
        set(value) {
        _builder.revisionId = value
      }
    /**
     * `string revision_id = 3 [json_name = "revisionId"];`
     */
    public fun clearRevisionId() {
      _builder.clearRevisionId()
    }

    /**
     * `string change_id = 4 [json_name = "changeId"];`
     */
    public var changeId: kotlin.String
      @kotlin.jvm.JvmName("getChangeId")
        get() = _builder.changeId
      @kotlin.jvm.JvmName("setChangeId")
        set(value) {
        _builder.changeId = value
      }
    /**
     * `string change_id = 4 [json_name = "changeId"];`
     */
    public fun clearChangeId() {
      _builder.clearChangeId()
    }
  }
}
public inline fun com.easylab.v1.SquashResponse.copy(block: `com.easylab.v1`.SquashResponseKt.Dsl.() -> kotlin.Unit): com.easylab.v1.SquashResponse =
  `com.easylab.v1`.SquashResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

