// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package easylab.v1;

@kotlin.jvm.JvmName("-initializesyncMirrorRequest")
public inline fun syncMirrorRequest(block: easylab.v1.SyncMirrorRequestKt.Dsl.() -> kotlin.Unit): easylab.v1.Easylab.SyncMirrorRequest =
  easylab.v1.SyncMirrorRequestKt.Dsl._create(easylab.v1.Easylab.SyncMirrorRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easylab.v1.SyncMirrorRequest`
 */
public object SyncMirrorRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: easylab.v1.Easylab.SyncMirrorRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: easylab.v1.Easylab.SyncMirrorRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): easylab.v1.Easylab.SyncMirrorRequest = _builder.build()

    /**
     * `string org = 1 [json_name = "org"];`
     */
    public var org: kotlin.String
      @kotlin.jvm.JvmName("getOrg")
        get() = _builder.org
      @kotlin.jvm.JvmName("setOrg")
        set(value) {
        _builder.org = value
      }
    /**
     * `string org = 1 [json_name = "org"];`
     */
    public fun clearOrg() {
      _builder.clearOrg()
    }

    /**
     * `string repo = 2 [json_name = "repo"];`
     */
    public var repo: kotlin.String
      @kotlin.jvm.JvmName("getRepo")
        get() = _builder.repo
      @kotlin.jvm.JvmName("setRepo")
        set(value) {
        _builder.repo = value
      }
    /**
     * `string repo = 2 [json_name = "repo"];`
     */
    public fun clearRepo() {
      _builder.clearRepo()
    }

    /**
     * ```
     * pull | push
     * ```
     *
     * `string kind = 3 [json_name = "kind"];`
     */
    public var kind: kotlin.String
      @kotlin.jvm.JvmName("getKind")
        get() = _builder.kind
      @kotlin.jvm.JvmName("setKind")
        set(value) {
        _builder.kind = value
      }
    /**
     * ```
     * pull | push
     * ```
     *
     * `string kind = 3 [json_name = "kind"];`
     */
    public fun clearKind() {
      _builder.clearKind()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class BodyProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `map<string, string> body = 4 [json_name = "body"];`
     */
     public val body: com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, BodyProxy>
      @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("getBodyMap")
      get() = com.google.protobuf.kotlin.DslMap(
        _builder.bodyMap
      )
    /**
     * `map<string, string> body = 4 [json_name = "body"];`
     */
    @kotlin.jvm.JvmName("putBody")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, BodyProxy>
      .put(key: kotlin.String, value: kotlin.String) {
         _builder.putBody(key, value)
       }
    /**
     * `map<string, string> body = 4 [json_name = "body"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setBody")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, BodyProxy>
      .set(key: kotlin.String, value: kotlin.String) {
         put(key, value)
       }
    /**
     * `map<string, string> body = 4 [json_name = "body"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("removeBody")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, BodyProxy>
      .remove(key: kotlin.String) {
         _builder.removeBody(key)
       }
    /**
     * `map<string, string> body = 4 [json_name = "body"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("putAllBody")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, BodyProxy>
      .putAll(map: kotlin.collections.Map<kotlin.String, kotlin.String>) {
         _builder.putAllBody(map)
       }
    /**
     * `map<string, string> body = 4 [json_name = "body"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearBody")
    public fun com.google.protobuf.kotlin.DslMap<kotlin.String, kotlin.String, BodyProxy>
      .clear() {
         _builder.clearBody()
       }
  }
}
public inline fun easylab.v1.Easylab.SyncMirrorRequest.copy(block: `easylab.v1`.SyncMirrorRequestKt.Dsl.() -> kotlin.Unit): easylab.v1.Easylab.SyncMirrorRequest =
  `easylab.v1`.SyncMirrorRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

