// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto
// Protobuf Java Version: 4.36.1

package com.easylab.v1;

@com.google.protobuf.Generated
public interface SyncMirrorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:easylab.v1.SyncMirrorResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bool ok = 1 [json_name = "ok"];</code>
   * @return The ok.
   */
  boolean getOk();

  /**
   * <code>string updated_branches = 2 [json_name = "updatedBranches"];</code>
   * @return The updatedBranches.
   */
  java.lang.String getUpdatedBranches();
  /**
   * <code>string updated_branches = 2 [json_name = "updatedBranches"];</code>
   * @return The bytes for updatedBranches.
   */
  com.google.protobuf.ByteString
      getUpdatedBranchesBytes();

  /**
   * <code>string error = 3 [json_name = "error"];</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <code>string error = 3 [json_name = "error"];</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();
}
