// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easylab.v1;

@kotlin.jvm.JvmName("-initializesyncResponse")
public inline fun syncResponse(block: com.easylab.v1.SyncResponseKt.Dsl.() -> kotlin.Unit): com.easylab.v1.SyncResponse =
  com.easylab.v1.SyncResponseKt.Dsl._create(com.easylab.v1.SyncResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easylab.v1.SyncResponse`
 */
public object SyncResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easylab.v1.SyncResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easylab.v1.SyncResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easylab.v1.SyncResponse = _builder.build()

    /**
     * `bool ok = 1 [json_name = "ok"];`
     */
    public var ok: kotlin.Boolean
      @kotlin.jvm.JvmName("getOk")
        get() = _builder.ok
      @kotlin.jvm.JvmName("setOk")
        set(value) {
        _builder.ok = value
      }
    /**
     * `bool ok = 1 [json_name = "ok"];`
     */
    public fun clearOk() {
      _builder.clearOk()
    }

    /**
     * `int32 files = 2 [json_name = "files"];`
     */
    public var files: kotlin.Int
      @kotlin.jvm.JvmName("getFiles")
        get() = _builder.files
      @kotlin.jvm.JvmName("setFiles")
        set(value) {
        _builder.files = value
      }
    /**
     * `int32 files = 2 [json_name = "files"];`
     */
    public fun clearFiles() {
      _builder.clearFiles()
    }
  }
}
public inline fun com.easylab.v1.SyncResponse.copy(block: `com.easylab.v1`.SyncResponseKt.Dsl.() -> kotlin.Unit): com.easylab.v1.SyncResponse =
  `com.easylab.v1`.SyncResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

