// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easylab.v1;

@kotlin.jvm.JvmName("-initializeuploadReleaseAssetRequest")
public inline fun uploadReleaseAssetRequest(block: com.easylab.v1.UploadReleaseAssetRequestKt.Dsl.() -> kotlin.Unit): com.easylab.v1.UploadReleaseAssetRequest =
  com.easylab.v1.UploadReleaseAssetRequestKt.Dsl._create(com.easylab.v1.UploadReleaseAssetRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easylab.v1.UploadReleaseAssetRequest`
 */
public object UploadReleaseAssetRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easylab.v1.UploadReleaseAssetRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easylab.v1.UploadReleaseAssetRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easylab.v1.UploadReleaseAssetRequest = _builder.build()

    /**
     * `string org = 1 [json_name = "org"];`
     */
    public var org: kotlin.String
      @kotlin.jvm.JvmName("getOrg")
        get() = _builder.org
      @kotlin.jvm.JvmName("setOrg")
        set(value) {
        _builder.org = value
      }
    /**
     * `string org = 1 [json_name = "org"];`
     */
    public fun clearOrg() {
      _builder.clearOrg()
    }

    /**
     * `string repo = 2 [json_name = "repo"];`
     */
    public var repo: kotlin.String
      @kotlin.jvm.JvmName("getRepo")
        get() = _builder.repo
      @kotlin.jvm.JvmName("setRepo")
        set(value) {
        _builder.repo = value
      }
    /**
     * `string repo = 2 [json_name = "repo"];`
     */
    public fun clearRepo() {
      _builder.clearRepo()
    }

    /**
     * `string tag = 3 [json_name = "tag"];`
     */
    public var tag: kotlin.String
      @kotlin.jvm.JvmName("getTag")
        get() = _builder.tag
      @kotlin.jvm.JvmName("setTag")
        set(value) {
        _builder.tag = value
      }
    /**
     * `string tag = 3 [json_name = "tag"];`
     */
    public fun clearTag() {
      _builder.clearTag()
    }

    /**
     * `string name = 4 [json_name = "name"];`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 4 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `bytes data = 5 [json_name = "data"];`
     */
    public var data: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getData")
        get() = _builder.data
      @kotlin.jvm.JvmName("setData")
        set(value) {
        _builder.data = value
      }
    /**
     * `bytes data = 5 [json_name = "data"];`
     */
    public fun clearData() {
      _builder.clearData()
    }

    /**
     * `string content_type = 6 [json_name = "contentType"];`
     */
    public var contentType: kotlin.String
      @kotlin.jvm.JvmName("getContentType")
        get() = _builder.contentType
      @kotlin.jvm.JvmName("setContentType")
        set(value) {
        _builder.contentType = value
      }
    /**
     * `string content_type = 6 [json_name = "contentType"];`
     */
    public fun clearContentType() {
      _builder.clearContentType()
    }
  }
}
public inline fun com.easylab.v1.UploadReleaseAssetRequest.copy(block: `com.easylab.v1`.UploadReleaseAssetRequestKt.Dsl.() -> kotlin.Unit): com.easylab.v1.UploadReleaseAssetRequest =
  `com.easylab.v1`.UploadReleaseAssetRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

