// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: easylab/v1/easylab.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.easylab.v1;

@kotlin.jvm.JvmName("-initializeuserToken")
public inline fun userToken(block: com.easylab.v1.UserTokenKt.Dsl.() -> kotlin.Unit): com.easylab.v1.UserToken =
  com.easylab.v1.UserTokenKt.Dsl._create(com.easylab.v1.UserToken.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `easylab.v1.UserToken`
 */
public object UserTokenKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.easylab.v1.UserToken.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.easylab.v1.UserToken.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.easylab.v1.UserToken = _builder.build()

    /**
     * `string id = 1 [json_name = "id"];`
     */
    public var id: kotlin.String
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * `string id = 1 [json_name = "id"];`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string username = 2 [json_name = "username"];`
     */
    public var username: kotlin.String
      @kotlin.jvm.JvmName("getUsername")
        get() = _builder.username
      @kotlin.jvm.JvmName("setUsername")
        set(value) {
        _builder.username = value
      }
    /**
     * `string username = 2 [json_name = "username"];`
     */
    public fun clearUsername() {
      _builder.clearUsername()
    }

    /**
     * `string created_at = 3 [json_name = "createdAt"];`
     */
    public var createdAt: kotlin.String
      @kotlin.jvm.JvmName("getCreatedAt")
        get() = _builder.createdAt
      @kotlin.jvm.JvmName("setCreatedAt")
        set(value) {
        _builder.createdAt = value
      }
    /**
     * `string created_at = 3 [json_name = "createdAt"];`
     */
    public fun clearCreatedAt() {
      _builder.clearCreatedAt()
    }
  }
}
public inline fun com.easylab.v1.UserToken.copy(block: `com.easylab.v1`.UserTokenKt.Dsl.() -> kotlin.Unit): com.easylab.v1.UserToken =
  `com.easylab.v1`.UserTokenKt.Dsl._create(this.toBuilder()).apply { block() }._build()

