// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: easylab/v1/easylab.proto
//
package easylab.v1

import com.connectrpc.Headers
import com.connectrpc.MethodSpec
import com.connectrpc.ProtocolClientInterface
import com.connectrpc.ResponseMessage
import com.connectrpc.ServerOnlyStreamInterface
import com.connectrpc.StreamType

public class WorkflowServiceClient(
  private val client: ProtocolClientInterface,
) : WorkflowServiceClientInterface {
  override suspend fun createWorkflow(request: Easylab.CreateWorkflowRequest, headers: Headers): ResponseMessage<Easylab.CreateWorkflowResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.WorkflowService/CreateWorkflow",
      easylab.v1.Easylab.CreateWorkflowRequest::class,
      easylab.v1.Easylab.CreateWorkflowResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun getWorkflow(request: Easylab.GetWorkflowRequest, headers: Headers): ResponseMessage<Easylab.GetWorkflowResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.WorkflowService/GetWorkflow",
      easylab.v1.Easylab.GetWorkflowRequest::class,
      easylab.v1.Easylab.GetWorkflowResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun listWorkflows(request: Easylab.ListWorkflowsRequest, headers: Headers): ResponseMessage<Easylab.ListWorkflowsResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.WorkflowService/ListWorkflows",
      easylab.v1.Easylab.ListWorkflowsRequest::class,
      easylab.v1.Easylab.ListWorkflowsResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun triggerRun(request: Easylab.TriggerRunRequest, headers: Headers): ResponseMessage<Easylab.TriggerRunResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.WorkflowService/TriggerRun",
      easylab.v1.Easylab.TriggerRunRequest::class,
      easylab.v1.Easylab.TriggerRunResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun getRun(request: Easylab.GetRunRequest, headers: Headers): ResponseMessage<Easylab.GetRunResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.WorkflowService/GetRun",
      easylab.v1.Easylab.GetRunRequest::class,
      easylab.v1.Easylab.GetRunResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun listRuns(request: Easylab.ListRunsRequest, headers: Headers): ResponseMessage<Easylab.ListRunsResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.WorkflowService/ListRuns",
      easylab.v1.Easylab.ListRunsRequest::class,
      easylab.v1.Easylab.ListRunsResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun runJobLog(headers: Headers): ServerOnlyStreamInterface<Easylab.RunJobLogRequest, Easylab.RunJobLogResponse> = client.serverStream(
    headers,
    MethodSpec(
    "easylab.v1.WorkflowService/RunJobLog",
      easylab.v1.Easylab.RunJobLogRequest::class,
      easylab.v1.Easylab.RunJobLogResponse::class,
      StreamType.SERVER,
    ),
  )


  override suspend fun cancelRun(request: Easylab.CancelRunRequest, headers: Headers): ResponseMessage<Easylab.CancelRunResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.WorkflowService/CancelRun",
      easylab.v1.Easylab.CancelRunRequest::class,
      easylab.v1.Easylab.CancelRunResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun registerRunner(request: Easylab.RegisterRunnerRequest, headers: Headers): ResponseMessage<Easylab.RegisterRunnerResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.WorkflowService/RegisterRunner",
      easylab.v1.Easylab.RegisterRunnerRequest::class,
      easylab.v1.Easylab.RegisterRunnerResponse::class,
      StreamType.UNARY,
    ),
  )


  override suspend fun listRunners(request: Easylab.ListRunnersRequest, headers: Headers): ResponseMessage<Easylab.ListRunnersResponse> = client.unary(
    request,
    headers,
    MethodSpec(
    "easylab.v1.WorkflowService/ListRunners",
      easylab.v1.Easylab.ListRunnersRequest::class,
      easylab.v1.Easylab.ListRunnersResponse::class,
      StreamType.UNARY,
    ),
  )

}
