// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: agent/v1/agent.proto
//
package com.agent.v1

import com.connectrpc.Headers
import com.connectrpc.ResponseMessage
import com.connectrpc.ServerOnlyStreamInterface

/**
 *  AgentService is the session-backend API.
 */
public interface AgentServiceClientInterface {
  public suspend fun health(request: HealthRequest, headers: Headers = emptyMap()): ResponseMessage<HealthResponse>

  public suspend fun listSessions(request: ListSessionsRequest, headers: Headers = emptyMap()): ResponseMessage<ListSessionsResponse>

  public suspend fun createSession(request: CreateSessionRequest, headers: Headers = emptyMap()): ResponseMessage<CreateSessionResponse>

  public suspend fun getSession(request: GetSessionRequest, headers: Headers = emptyMap()): ResponseMessage<GetSessionResponse>

  public suspend fun deleteSession(request: DeleteSessionRequest, headers: Headers = emptyMap()): ResponseMessage<DeleteSessionResponse>

  public suspend fun listMessages(request: ListMessagesRequest, headers: Headers = emptyMap()): ResponseMessage<ListMessagesResponse>

  public suspend fun prompt(headers: Headers = emptyMap()): ServerOnlyStreamInterface<PromptRequest, PromptResponse>

  public suspend fun watchSession(headers: Headers = emptyMap()): ServerOnlyStreamInterface<WatchSessionRequest, WatchSessionResponse>

  public suspend fun fork(request: ForkRequest, headers: Headers = emptyMap()): ResponseMessage<ForkResponse>

  public suspend fun rename(request: RenameRequest, headers: Headers = emptyMap()): ResponseMessage<RenameResponse>

  public suspend fun setModel(request: SetModelRequest, headers: Headers = emptyMap()): ResponseMessage<SetModelResponse>

  public suspend fun undo(request: UndoRequest, headers: Headers = emptyMap()): ResponseMessage<UndoResponse>

  public suspend fun state(request: StateRequest, headers: Headers = emptyMap()): ResponseMessage<StateResponse>

  public suspend fun mailbox(request: MailboxRequest, headers: Headers = emptyMap()): ResponseMessage<MailboxResponse>

  public suspend fun updateSettings(request: UpdateSettingsRequest, headers: Headers = emptyMap()): ResponseMessage<UpdateSettingsResponse>

  public suspend fun interrupt(request: InterruptRequest, headers: Headers = emptyMap()): ResponseMessage<InterruptResponse>

  public suspend fun compact(request: CompactRequest, headers: Headers = emptyMap()): ResponseMessage<CompactResponse>

  public suspend fun listProviders(request: ListProvidersRequest, headers: Headers = emptyMap()): ResponseMessage<ListProvidersResponse>

  public suspend fun listProvidersCatalog(request: ListProvidersCatalogRequest, headers: Headers = emptyMap()): ResponseMessage<ListProvidersCatalogResponse>

  public suspend fun registerProvider(request: RegisterProviderRequest, headers: Headers = emptyMap()): ResponseMessage<RegisterProviderResponse>

  public suspend fun deleteProvider(request: DeleteProviderRequest, headers: Headers = emptyMap()): ResponseMessage<DeleteProviderResponse>

  public suspend fun testProvider(request: TestProviderRequest, headers: Headers = emptyMap()): ResponseMessage<TestProviderResponse>

  public suspend fun listModels(request: ListModelsRequest, headers: Headers = emptyMap()): ResponseMessage<ListModelsResponse>

  public suspend fun listPresets(request: ListPresetsRequest, headers: Headers = emptyMap()): ResponseMessage<ListPresetsResponse>

  public suspend fun upsertPreset(request: UpsertPresetRequest, headers: Headers = emptyMap()): ResponseMessage<UpsertPresetResponse>

  public suspend fun deletePreset(request: DeletePresetRequest, headers: Headers = emptyMap()): ResponseMessage<DeletePresetResponse>

  public suspend fun previewPreset(request: PreviewPresetRequest, headers: Headers = emptyMap()): ResponseMessage<PreviewPresetResponse>

  public suspend fun getConfig(request: GetConfigRequest, headers: Headers = emptyMap()): ResponseMessage<GetConfigResponse>

  public suspend fun setConfig(request: SetConfigRequest, headers: Headers = emptyMap()): ResponseMessage<SetConfigResponse>

  public suspend fun listTools(request: ListToolsRequest, headers: Headers = emptyMap()): ResponseMessage<ListToolsResponse>

  public suspend fun getToolConfig(request: GetToolConfigRequest, headers: Headers = emptyMap()): ResponseMessage<GetToolConfigResponse>

  public suspend fun setToolConfig(request: SetToolConfigRequest, headers: Headers = emptyMap()): ResponseMessage<SetToolConfigResponse>

  public suspend fun setExtensionConfig(request: SetExtensionConfigRequest, headers: Headers = emptyMap()): ResponseMessage<SetExtensionConfigResponse>

  public suspend fun uploadFile(request: UploadFileRequest, headers: Headers = emptyMap()): ResponseMessage<UploadFileResponse>

  public suspend fun ingestFile(request: IngestFileRequest, headers: Headers = emptyMap()): ResponseMessage<IngestFileResponse>

  public suspend fun getFile(request: GetFileRequest, headers: Headers = emptyMap()): ResponseMessage<GetFileResponse>

  public suspend fun getFileMeta(request: GetFileMetaRequest, headers: Headers = emptyMap()): ResponseMessage<GetFileMetaResponse>

  public suspend fun listWorksheets(request: ListWorksheetsRequest, headers: Headers = emptyMap()): ResponseMessage<ListWorksheetsResponse>

  public suspend fun decideWorksheet(request: DecideWorksheetRequest, headers: Headers = emptyMap()): ResponseMessage<DecideWorksheetResponse>

  public suspend fun getAgentConfig(request: GetAgentConfigRequest, headers: Headers = emptyMap()): ResponseMessage<GetAgentConfigResponse>
}
