// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto
// Protobuf Java Version: 4.36.1

package com.agent.v1;

@com.google.protobuf.Generated
public interface CreateTenantResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.v1.CreateTenantResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.agent.v1.Tenant tenant = 1 [json_name = "tenant"];</code>
   * @return Whether the tenant field is set.
   */
  boolean hasTenant();
  /**
   * <code>.agent.v1.Tenant tenant = 1 [json_name = "tenant"];</code>
   * @return The tenant.
   */
  com.agent.v1.Tenant getTenant();

  /**
   * <pre>
   * The bootstrap token minted for the new tenant (plaintext, shown once).
   * </pre>
   *
   * <code>string token = 2 [json_name = "token"];</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <pre>
   * The bootstrap token minted for the new tenant (plaintext, shown once).
   * </pre>
   *
   * <code>string token = 2 [json_name = "token"];</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
