// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.agent.v1;

@kotlin.jvm.JvmName("-initializedeleteProviderRequest")
public inline fun deleteProviderRequest(block: com.agent.v1.DeleteProviderRequestKt.Dsl.() -> kotlin.Unit): com.agent.v1.DeleteProviderRequest =
  com.agent.v1.DeleteProviderRequestKt.Dsl._create(com.agent.v1.DeleteProviderRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.DeleteProviderRequest`
 */
public object DeleteProviderRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.agent.v1.DeleteProviderRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.agent.v1.DeleteProviderRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.agent.v1.DeleteProviderRequest = _builder.build()

    /**
     * `string provider_id = 1 [json_name = "providerId"];`
     */
    public var providerId: kotlin.String
      @kotlin.jvm.JvmName("getProviderId")
        get() = _builder.providerId
      @kotlin.jvm.JvmName("setProviderId")
        set(value) {
        _builder.providerId = value
      }
    /**
     * `string provider_id = 1 [json_name = "providerId"];`
     */
    public fun clearProviderId() {
      _builder.clearProviderId()
    }
  }
}
public inline fun com.agent.v1.DeleteProviderRequest.copy(block: `com.agent.v1`.DeleteProviderRequestKt.Dsl.() -> kotlin.Unit): com.agent.v1.DeleteProviderRequest =
  `com.agent.v1`.DeleteProviderRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

