// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package agent.v1;

@kotlin.jvm.JvmName("-initializediscoverGatewayModelsResponse")
public inline fun discoverGatewayModelsResponse(block: agent.v1.DiscoverGatewayModelsResponseKt.Dsl.() -> kotlin.Unit): agent.v1.Agent.DiscoverGatewayModelsResponse =
  agent.v1.DiscoverGatewayModelsResponseKt.Dsl._create(agent.v1.Agent.DiscoverGatewayModelsResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.DiscoverGatewayModelsResponse`
 */
public object DiscoverGatewayModelsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: agent.v1.Agent.DiscoverGatewayModelsResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: agent.v1.Agent.DiscoverGatewayModelsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): agent.v1.Agent.DiscoverGatewayModelsResponse = _builder.build()

    /**
     * `bool ok = 1 [json_name = "ok"];`
     */
    public var ok: kotlin.Boolean
      @kotlin.jvm.JvmName("getOk")
        get() = _builder.ok
      @kotlin.jvm.JvmName("setOk")
        set(value) {
        _builder.ok = value
      }
    /**
     * `bool ok = 1 [json_name = "ok"];`
     */
    public fun clearOk() {
      _builder.clearOk()
    }

    /**
     * `string error = 2 [json_name = "error"];`
     */
    public var error: kotlin.String
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `string error = 2 [json_name = "error"];`
     */
    public fun clearError() {
      _builder.clearError()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ModelsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .agent.v1.ProviderModel models = 3 [json_name = "models"];`
     */
     public val models: com.google.protobuf.kotlin.DslList<agent.v1.Agent.ProviderModel, ModelsProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.modelsList
      )
    /**
     * `repeated .agent.v1.ProviderModel models = 3 [json_name = "models"];`
     * @param value The models to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addModels")
    public fun com.google.protobuf.kotlin.DslList<agent.v1.Agent.ProviderModel, ModelsProxy>.add(value: agent.v1.Agent.ProviderModel) {
      _builder.addModels(value)
    }
    /**
     * `repeated .agent.v1.ProviderModel models = 3 [json_name = "models"];`
     * @param value The models to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignModels")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<agent.v1.Agent.ProviderModel, ModelsProxy>.plusAssign(value: agent.v1.Agent.ProviderModel) {
      add(value)
    }
    /**
     * `repeated .agent.v1.ProviderModel models = 3 [json_name = "models"];`
     * @param values The models to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllModels")
    public fun com.google.protobuf.kotlin.DslList<agent.v1.Agent.ProviderModel, ModelsProxy>.addAll(values: kotlin.collections.Iterable<agent.v1.Agent.ProviderModel>) {
      _builder.addAllModels(values)
    }
    /**
     * `repeated .agent.v1.ProviderModel models = 3 [json_name = "models"];`
     * @param values The models to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllModels")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<agent.v1.Agent.ProviderModel, ModelsProxy>.plusAssign(values: kotlin.collections.Iterable<agent.v1.Agent.ProviderModel>) {
      addAll(values)
    }
    /**
     * `repeated .agent.v1.ProviderModel models = 3 [json_name = "models"];`
     * @param index The index to set the value at.
     * @param value The models to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setModels")
    public operator fun com.google.protobuf.kotlin.DslList<agent.v1.Agent.ProviderModel, ModelsProxy>.set(index: kotlin.Int, value: agent.v1.Agent.ProviderModel) {
      _builder.setModels(index, value)
    }
    /**
     * `repeated .agent.v1.ProviderModel models = 3 [json_name = "models"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearModels")
    public fun com.google.protobuf.kotlin.DslList<agent.v1.Agent.ProviderModel, ModelsProxy>.clear() {
      _builder.clearModels()
    }
  }
}
public inline fun agent.v1.Agent.DiscoverGatewayModelsResponse.copy(block: `agent.v1`.DiscoverGatewayModelsResponseKt.Dsl.() -> kotlin.Unit): agent.v1.Agent.DiscoverGatewayModelsResponse =
  `agent.v1`.DiscoverGatewayModelsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

