// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto
// Protobuf Java Version: 4.36.1

package com.agent.v1;

@com.google.protobuf.Generated
public interface DiscoverGatewayModelsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.v1.DiscoverGatewayModelsResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>bool ok = 1 [json_name = "ok"];</code>
   * @return The ok.
   */
  boolean getOk();

  /**
   * <code>string error = 2 [json_name = "error"];</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <code>string error = 2 [json_name = "error"];</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();

  /**
   * <code>repeated .agent.v1.ProviderModel models = 3 [json_name = "models"];</code>
   */
  java.util.List<com.agent.v1.ProviderModel> 
      getModelsList();
  /**
   * <code>repeated .agent.v1.ProviderModel models = 3 [json_name = "models"];</code>
   */
  com.agent.v1.ProviderModel getModels(int index);
  /**
   * <code>repeated .agent.v1.ProviderModel models = 3 [json_name = "models"];</code>
   */
  int getModelsCount();
}
