// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package agent.v1;

@kotlin.jvm.JvmName("-initializegetFileResponse")
public inline fun getFileResponse(block: agent.v1.GetFileResponseKt.Dsl.() -> kotlin.Unit): agent.v1.Agent.GetFileResponse =
  agent.v1.GetFileResponseKt.Dsl._create(agent.v1.Agent.GetFileResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.GetFileResponse`
 */
public object GetFileResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: agent.v1.Agent.GetFileResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: agent.v1.Agent.GetFileResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): agent.v1.Agent.GetFileResponse = _builder.build()

    /**
     * `string data = 1 [json_name = "data"];`
     */
    public var data: kotlin.String
      @kotlin.jvm.JvmName("getData")
        get() = _builder.data
      @kotlin.jvm.JvmName("setData")
        set(value) {
        _builder.data = value
      }
    /**
     * `string data = 1 [json_name = "data"];`
     */
    public fun clearData() {
      _builder.clearData()
    }

    /**
     * `string name = 2 [json_name = "name"];`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 2 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `string mime = 3 [json_name = "mime"];`
     */
    public var mime: kotlin.String
      @kotlin.jvm.JvmName("getMime")
        get() = _builder.mime
      @kotlin.jvm.JvmName("setMime")
        set(value) {
        _builder.mime = value
      }
    /**
     * `string mime = 3 [json_name = "mime"];`
     */
    public fun clearMime() {
      _builder.clearMime()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun agent.v1.Agent.GetFileResponse.copy(block: `agent.v1`.GetFileResponseKt.Dsl.() -> kotlin.Unit): agent.v1.Agent.GetFileResponse =
  `agent.v1`.GetFileResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

