// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto
// Protobuf Java Version: 4.36.1

package com.agent.v1;

/**
 * Protobuf type {@code agent.v1.ListMessagesResponse}
 */
@com.google.protobuf.Generated
public  final class ListMessagesResponse extends
    com.google.protobuf.GeneratedMessageLite<
        ListMessagesResponse, ListMessagesResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:agent.v1.ListMessagesResponse)
    ListMessagesResponseOrBuilder {
  private ListMessagesResponse() {
    messages_ = emptyProtobufList();
  }
  public static final int OK_FIELD_NUMBER = 1;
  private boolean ok_;
  /**
   * <code>bool ok = 1 [json_name = "ok"];</code>
   * @return The ok.
   */
  @java.lang.Override
  public boolean getOk() {
    return ok_;
  }
  /**
   * <code>bool ok = 1 [json_name = "ok"];</code>
   * @param value The ok to set.
   */
  private void setOk(boolean value) {
    
    ok_ = value;
  }
  /**
   * <code>bool ok = 1 [json_name = "ok"];</code>
   */
  private void clearOk() {

    ok_ = false;
  }

  public static final int MESSAGES_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<com.agent.v1.Message> messages_;
  /**
   * <code>repeated .agent.v1.Message messages = 2 [json_name = "messages"];</code>
   */
  @java.lang.Override
  public java.util.List<com.agent.v1.Message> getMessagesList() {
    return messages_;
  }
  /**
   * <code>repeated .agent.v1.Message messages = 2 [json_name = "messages"];</code>
   */
  public java.util.List<? extends com.agent.v1.MessageOrBuilder> 
      getMessagesOrBuilderList() {
    return messages_;
  }
  /**
   * <code>repeated .agent.v1.Message messages = 2 [json_name = "messages"];</code>
   */
  @java.lang.Override
  public int getMessagesCount() {
    return messages_.size();
  }
  /**
   * <code>repeated .agent.v1.Message messages = 2 [json_name = "messages"];</code>
   */
  @java.lang.Override
  public com.agent.v1.Message getMessages(int index) {
    return messages_.get(index);
  }
  /**
   * <code>repeated .agent.v1.Message messages = 2 [json_name = "messages"];</code>
   */
  public com.agent.v1.MessageOrBuilder getMessagesOrBuilder(
      int index) {
    return messages_.get(index);
  }
  private void ensureMessagesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.agent.v1.Message> tmp = messages_;
    if (!tmp.isModifiable()) {
      messages_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .agent.v1.Message messages = 2 [json_name = "messages"];</code>
   */
  private void setMessages(
      int index, com.agent.v1.Message value) {
    java.util.Objects.requireNonNull(value);
    ensureMessagesIsMutable();
    messages_.set(index, value);
  }
  /**
   * <code>repeated .agent.v1.Message messages = 2 [json_name = "messages"];</code>
   */
  private void addMessages(com.agent.v1.Message value) {
    java.util.Objects.requireNonNull(value);
    ensureMessagesIsMutable();
    messages_.add(value);
  }
  /**
   * <code>repeated .agent.v1.Message messages = 2 [json_name = "messages"];</code>
   */
  private void addMessages(
      int index, com.agent.v1.Message value) {
    java.util.Objects.requireNonNull(value);
    ensureMessagesIsMutable();
    messages_.add(index, value);
  }
  /**
   * <code>repeated .agent.v1.Message messages = 2 [json_name = "messages"];</code>
   */
  private void addAllMessages(
      java.lang.Iterable<? extends com.agent.v1.Message> values) {
    ensureMessagesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, messages_);
  }
  /**
   * <code>repeated .agent.v1.Message messages = 2 [json_name = "messages"];</code>
   */
  private void clearMessages() {
    messages_ = emptyProtobufList();
  }
  /**
   * <code>repeated .agent.v1.Message messages = 2 [json_name = "messages"];</code>
   */
  private void removeMessages(int index) {
    ensureMessagesIsMutable();
    messages_.remove(index);
  }

  public static com.agent.v1.ListMessagesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.agent.v1.ListMessagesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.agent.v1.ListMessagesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.agent.v1.ListMessagesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.agent.v1.ListMessagesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.agent.v1.ListMessagesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.agent.v1.ListMessagesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.agent.v1.ListMessagesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.agent.v1.ListMessagesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.agent.v1.ListMessagesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.agent.v1.ListMessagesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.agent.v1.ListMessagesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.agent.v1.ListMessagesResponse prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code agent.v1.ListMessagesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.agent.v1.ListMessagesResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:agent.v1.ListMessagesResponse)
      com.agent.v1.ListMessagesResponseOrBuilder {
    // Construct using com.agent.v1.ListMessagesResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>bool ok = 1 [json_name = "ok"];</code>
     * @return The ok.
     */
    @java.lang.Override
    public boolean getOk() {
      return instance.getOk();
    }
    /**
     * <code>bool ok = 1 [json_name = "ok"];</code>
     * @param value The ok to set.
     * @return This builder for chaining.
     */
    public Builder setOk(boolean value) {
      copyOnWrite();
      instance.setOk(value);
      return this;
    }
    /**
     * <code>bool ok = 1 [json_name = "ok"];</code>
     * @return This builder for chaining.
     */
    public Builder clearOk() {
      copyOnWrite();
      instance.clearOk();
      return this;
    }

    /**
     * <code>repeated .agent.v1.Message messages = 2 [json_name = "messages"];</code>
     */
    @java.lang.Override
    public java.util.List<com.agent.v1.Message> getMessagesList() {
      return java.util.Collections.unmodifiableList(
          instance.getMessagesList());
    }
    /**
     * <code>repeated .agent.v1.Message messages = 2 [json_name = "messages"];</code>
     */
    @java.lang.Override
    public int getMessagesCount() {
      return instance.getMessagesCount();
    }/**
     * <code>repeated .agent.v1.Message messages = 2 [json_name = "messages"];</code>
     */
    @java.lang.Override
    public com.agent.v1.Message getMessages(int index) {
      return instance.getMessages(index);
    }
    /**
     * <code>repeated .agent.v1.Message messages = 2 [json_name = "messages"];</code>
     */
    public Builder setMessages(
        int index, com.agent.v1.Message value) {
      copyOnWrite();
      instance.setMessages(index, value);
      return this;
    }
    /**
     * <code>repeated .agent.v1.Message messages = 2 [json_name = "messages"];</code>
     */
    public Builder setMessages(
        int index, com.agent.v1.Message.Builder builderForValue) {
      copyOnWrite();
      instance.setMessages(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .agent.v1.Message messages = 2 [json_name = "messages"];</code>
     */
    public Builder addMessages(com.agent.v1.Message value) {
      copyOnWrite();
      instance.addMessages(value);
      return this;
    }
    /**
     * <code>repeated .agent.v1.Message messages = 2 [json_name = "messages"];</code>
     */
    public Builder addMessages(
        int index, com.agent.v1.Message value) {
      copyOnWrite();
      instance.addMessages(index, value);
      return this;
    }
    /**
     * <code>repeated .agent.v1.Message messages = 2 [json_name = "messages"];</code>
     */
    public Builder addMessages(
        com.agent.v1.Message.Builder builderForValue) {
      copyOnWrite();
      instance.addMessages(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .agent.v1.Message messages = 2 [json_name = "messages"];</code>
     */
    public Builder addMessages(
        int index, com.agent.v1.Message.Builder builderForValue) {
      copyOnWrite();
      instance.addMessages(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .agent.v1.Message messages = 2 [json_name = "messages"];</code>
     */
    public Builder addAllMessages(
        java.lang.Iterable<? extends com.agent.v1.Message> values) {
      copyOnWrite();
      instance.addAllMessages(values);
      return this;
    }
    /**
     * <code>repeated .agent.v1.Message messages = 2 [json_name = "messages"];</code>
     */
    public Builder clearMessages() {
      copyOnWrite();
      instance.clearMessages();
      return this;
    }
    /**
     * <code>repeated .agent.v1.Message messages = 2 [json_name = "messages"];</code>
     */
    public Builder removeMessages(int index) {
      copyOnWrite();
      instance.removeMessages(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:agent.v1.ListMessagesResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.agent.v1.ListMessagesResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "ok_",
            "messages_",
            com.agent.v1.Message.class,
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u0007\u0002\u001b" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.agent.v1.ListMessagesResponse> parser = PARSER;
        if (parser == null) {
          synchronized (com.agent.v1.ListMessagesResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.agent.v1.ListMessagesResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:agent.v1.ListMessagesResponse)
  private static final com.agent.v1.ListMessagesResponse DEFAULT_INSTANCE;
  static {
    ListMessagesResponse defaultInstance = new ListMessagesResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ListMessagesResponse.class, defaultInstance);
  }

  public static com.agent.v1.ListMessagesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ListMessagesResponse> PARSER;

  public static com.google.protobuf.Parser<ListMessagesResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

