// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package agent.v1;

@kotlin.jvm.JvmName("-initializelistToolsRequest")
public inline fun listToolsRequest(block: agent.v1.ListToolsRequestKt.Dsl.() -> kotlin.Unit): agent.v1.Agent.ListToolsRequest =
  agent.v1.ListToolsRequestKt.Dsl._create(agent.v1.Agent.ListToolsRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.ListToolsRequest`
 */
public object ListToolsRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: agent.v1.Agent.ListToolsRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: agent.v1.Agent.ListToolsRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): agent.v1.Agent.ListToolsRequest = _builder.build()

    /**
     * `string locale = 1 [json_name = "locale"];`
     */
    public var locale: kotlin.String
      @kotlin.jvm.JvmName("getLocale")
        get() = _builder.locale
      @kotlin.jvm.JvmName("setLocale")
        set(value) {
        _builder.locale = value
      }
    /**
     * `string locale = 1 [json_name = "locale"];`
     */
    public fun clearLocale() {
      _builder.clearLocale()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun agent.v1.Agent.ListToolsRequest.copy(block: `agent.v1`.ListToolsRequestKt.Dsl.() -> kotlin.Unit): agent.v1.Agent.ListToolsRequest =
  `agent.v1`.ListToolsRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

