// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto
// Protobuf Java Version: 4.36.1

package com.agent.v1;

@com.google.protobuf.Generated
public interface ListModelsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.v1.ListModelsResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .agent.v1.ModelInfo models = 1 [json_name = "models"];</code>
   */
  java.util.List<com.agent.v1.ModelInfo> 
      getModelsList();
  /**
   * <code>repeated .agent.v1.ModelInfo models = 1 [json_name = "models"];</code>
   */
  com.agent.v1.ModelInfo getModels(int index);
  /**
   * <code>repeated .agent.v1.ModelInfo models = 1 [json_name = "models"];</code>
   */
  int getModelsCount();
}
