// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto
// Protobuf Java Version: 4.36.1

package com.agent.v1;

@com.google.protobuf.Generated
public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:agent.v1.Message)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string role = 2 [json_name = "role"];</code>
   * @return The role.
   */
  java.lang.String getRole();
  /**
   * <code>string role = 2 [json_name = "role"];</code>
   * @return The bytes for role.
   */
  com.google.protobuf.ByteString
      getRoleBytes();

  /**
   * <code>string prev_id = 3 [json_name = "prevId"];</code>
   * @return The prevId.
   */
  java.lang.String getPrevId();
  /**
   * <code>string prev_id = 3 [json_name = "prevId"];</code>
   * @return The bytes for prevId.
   */
  com.google.protobuf.ByteString
      getPrevIdBytes();

  /**
   * <code>string created_at = 4 [json_name = "createdAt"];</code>
   * @return The createdAt.
   */
  java.lang.String getCreatedAt();
  /**
   * <code>string created_at = 4 [json_name = "createdAt"];</code>
   * @return The bytes for createdAt.
   */
  com.google.protobuf.ByteString
      getCreatedAtBytes();

  /**
   * <code>repeated .agent.v1.Part parts = 5 [json_name = "parts"];</code>
   */
  java.util.List<com.agent.v1.Part> 
      getPartsList();
  /**
   * <code>repeated .agent.v1.Part parts = 5 [json_name = "parts"];</code>
   */
  com.agent.v1.Part getParts(int index);
  /**
   * <code>repeated .agent.v1.Part parts = 5 [json_name = "parts"];</code>
   */
  int getPartsCount();
}
