// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto
// Protobuf Java Version: 4.36.1

package com.agent.v1;

/**
 * Protobuf type {@code agent.v1.PromptRequest}
 */
@com.google.protobuf.Generated
public  final class PromptRequest extends
    com.google.protobuf.GeneratedMessageLite<
        PromptRequest, PromptRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:agent.v1.PromptRequest)
    PromptRequestOrBuilder {
  private PromptRequest() {
    id_ = "";
    prompt_ = "";
    attachments_ = emptyProtobufList();
  }
  public static final int ID_FIELD_NUMBER = 1;
  private java.lang.String id_;
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    return id_;
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(id_);
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @param value The id to set.
   */
  private void setId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    id_ = value;
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   */
  private void clearId() {

    id_ = getDefaultInstance().getId();
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @param value The bytes for id to set.
   */
  private void setIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    id_ = value.toStringUtf8();

  }

  public static final int PROMPT_FIELD_NUMBER = 2;
  private java.lang.String prompt_;
  /**
   * <code>string prompt = 2 [json_name = "prompt"];</code>
   * @return The prompt.
   */
  @java.lang.Override
  public java.lang.String getPrompt() {
    return prompt_;
  }
  /**
   * <code>string prompt = 2 [json_name = "prompt"];</code>
   * @return The bytes for prompt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPromptBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(prompt_);
  }
  /**
   * <code>string prompt = 2 [json_name = "prompt"];</code>
   * @param value The prompt to set.
   */
  private void setPrompt(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    prompt_ = value;
  }
  /**
   * <code>string prompt = 2 [json_name = "prompt"];</code>
   */
  private void clearPrompt() {

    prompt_ = getDefaultInstance().getPrompt();
  }
  /**
   * <code>string prompt = 2 [json_name = "prompt"];</code>
   * @param value The bytes for prompt to set.
   */
  private void setPromptBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    prompt_ = value.toStringUtf8();

  }

  public static final int ATTACHMENTS_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<com.agent.v1.FileRef> attachments_;
  /**
   * <code>repeated .agent.v1.FileRef attachments = 3 [json_name = "attachments"];</code>
   */
  @java.lang.Override
  public java.util.List<com.agent.v1.FileRef> getAttachmentsList() {
    return attachments_;
  }
  /**
   * <code>repeated .agent.v1.FileRef attachments = 3 [json_name = "attachments"];</code>
   */
  public java.util.List<? extends com.agent.v1.FileRefOrBuilder> 
      getAttachmentsOrBuilderList() {
    return attachments_;
  }
  /**
   * <code>repeated .agent.v1.FileRef attachments = 3 [json_name = "attachments"];</code>
   */
  @java.lang.Override
  public int getAttachmentsCount() {
    return attachments_.size();
  }
  /**
   * <code>repeated .agent.v1.FileRef attachments = 3 [json_name = "attachments"];</code>
   */
  @java.lang.Override
  public com.agent.v1.FileRef getAttachments(int index) {
    return attachments_.get(index);
  }
  /**
   * <code>repeated .agent.v1.FileRef attachments = 3 [json_name = "attachments"];</code>
   */
  public com.agent.v1.FileRefOrBuilder getAttachmentsOrBuilder(
      int index) {
    return attachments_.get(index);
  }
  private void ensureAttachmentsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.agent.v1.FileRef> tmp = attachments_;
    if (!tmp.isModifiable()) {
      attachments_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .agent.v1.FileRef attachments = 3 [json_name = "attachments"];</code>
   */
  private void setAttachments(
      int index, com.agent.v1.FileRef value) {
    java.util.Objects.requireNonNull(value);
    ensureAttachmentsIsMutable();
    attachments_.set(index, value);
  }
  /**
   * <code>repeated .agent.v1.FileRef attachments = 3 [json_name = "attachments"];</code>
   */
  private void addAttachments(com.agent.v1.FileRef value) {
    java.util.Objects.requireNonNull(value);
    ensureAttachmentsIsMutable();
    attachments_.add(value);
  }
  /**
   * <code>repeated .agent.v1.FileRef attachments = 3 [json_name = "attachments"];</code>
   */
  private void addAttachments(
      int index, com.agent.v1.FileRef value) {
    java.util.Objects.requireNonNull(value);
    ensureAttachmentsIsMutable();
    attachments_.add(index, value);
  }
  /**
   * <code>repeated .agent.v1.FileRef attachments = 3 [json_name = "attachments"];</code>
   */
  private void addAllAttachments(
      java.lang.Iterable<? extends com.agent.v1.FileRef> values) {
    ensureAttachmentsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, attachments_);
  }
  /**
   * <code>repeated .agent.v1.FileRef attachments = 3 [json_name = "attachments"];</code>
   */
  private void clearAttachments() {
    attachments_ = emptyProtobufList();
  }
  /**
   * <code>repeated .agent.v1.FileRef attachments = 3 [json_name = "attachments"];</code>
   */
  private void removeAttachments(int index) {
    ensureAttachmentsIsMutable();
    attachments_.remove(index);
  }

  public static com.agent.v1.PromptRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.agent.v1.PromptRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.agent.v1.PromptRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.agent.v1.PromptRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.agent.v1.PromptRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.agent.v1.PromptRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.agent.v1.PromptRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.agent.v1.PromptRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.agent.v1.PromptRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.agent.v1.PromptRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.agent.v1.PromptRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.agent.v1.PromptRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.agent.v1.PromptRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code agent.v1.PromptRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.agent.v1.PromptRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:agent.v1.PromptRequest)
      com.agent.v1.PromptRequestOrBuilder {
    // Construct using com.agent.v1.PromptRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      return instance.getId();
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return instance.getIdBytes();
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdBytes(value);
      return this;
    }

    /**
     * <code>string prompt = 2 [json_name = "prompt"];</code>
     * @return The prompt.
     */
    @java.lang.Override
    public java.lang.String getPrompt() {
      return instance.getPrompt();
    }
    /**
     * <code>string prompt = 2 [json_name = "prompt"];</code>
     * @return The bytes for prompt.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPromptBytes() {
      return instance.getPromptBytes();
    }
    /**
     * <code>string prompt = 2 [json_name = "prompt"];</code>
     * @param value The prompt to set.
     * @return This builder for chaining.
     */
    public Builder setPrompt(
        java.lang.String value) {
      copyOnWrite();
      instance.setPrompt(value);
      return this;
    }
    /**
     * <code>string prompt = 2 [json_name = "prompt"];</code>
     * @return This builder for chaining.
     */
    public Builder clearPrompt() {
      copyOnWrite();
      instance.clearPrompt();
      return this;
    }
    /**
     * <code>string prompt = 2 [json_name = "prompt"];</code>
     * @param value The bytes for prompt to set.
     * @return This builder for chaining.
     */
    public Builder setPromptBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPromptBytes(value);
      return this;
    }

    /**
     * <code>repeated .agent.v1.FileRef attachments = 3 [json_name = "attachments"];</code>
     */
    @java.lang.Override
    public java.util.List<com.agent.v1.FileRef> getAttachmentsList() {
      return java.util.Collections.unmodifiableList(
          instance.getAttachmentsList());
    }
    /**
     * <code>repeated .agent.v1.FileRef attachments = 3 [json_name = "attachments"];</code>
     */
    @java.lang.Override
    public int getAttachmentsCount() {
      return instance.getAttachmentsCount();
    }/**
     * <code>repeated .agent.v1.FileRef attachments = 3 [json_name = "attachments"];</code>
     */
    @java.lang.Override
    public com.agent.v1.FileRef getAttachments(int index) {
      return instance.getAttachments(index);
    }
    /**
     * <code>repeated .agent.v1.FileRef attachments = 3 [json_name = "attachments"];</code>
     */
    public Builder setAttachments(
        int index, com.agent.v1.FileRef value) {
      copyOnWrite();
      instance.setAttachments(index, value);
      return this;
    }
    /**
     * <code>repeated .agent.v1.FileRef attachments = 3 [json_name = "attachments"];</code>
     */
    public Builder setAttachments(
        int index, com.agent.v1.FileRef.Builder builderForValue) {
      copyOnWrite();
      instance.setAttachments(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .agent.v1.FileRef attachments = 3 [json_name = "attachments"];</code>
     */
    public Builder addAttachments(com.agent.v1.FileRef value) {
      copyOnWrite();
      instance.addAttachments(value);
      return this;
    }
    /**
     * <code>repeated .agent.v1.FileRef attachments = 3 [json_name = "attachments"];</code>
     */
    public Builder addAttachments(
        int index, com.agent.v1.FileRef value) {
      copyOnWrite();
      instance.addAttachments(index, value);
      return this;
    }
    /**
     * <code>repeated .agent.v1.FileRef attachments = 3 [json_name = "attachments"];</code>
     */
    public Builder addAttachments(
        com.agent.v1.FileRef.Builder builderForValue) {
      copyOnWrite();
      instance.addAttachments(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .agent.v1.FileRef attachments = 3 [json_name = "attachments"];</code>
     */
    public Builder addAttachments(
        int index, com.agent.v1.FileRef.Builder builderForValue) {
      copyOnWrite();
      instance.addAttachments(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .agent.v1.FileRef attachments = 3 [json_name = "attachments"];</code>
     */
    public Builder addAllAttachments(
        java.lang.Iterable<? extends com.agent.v1.FileRef> values) {
      copyOnWrite();
      instance.addAllAttachments(values);
      return this;
    }
    /**
     * <code>repeated .agent.v1.FileRef attachments = 3 [json_name = "attachments"];</code>
     */
    public Builder clearAttachments() {
      copyOnWrite();
      instance.clearAttachments();
      return this;
    }
    /**
     * <code>repeated .agent.v1.FileRef attachments = 3 [json_name = "attachments"];</code>
     */
    public Builder removeAttachments(int index) {
      copyOnWrite();
      instance.removeAttachments(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:agent.v1.PromptRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.agent.v1.PromptRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "id_",
            "prompt_",
            "attachments_",
            com.agent.v1.FileRef.class,
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0001\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.agent.v1.PromptRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.agent.v1.PromptRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.agent.v1.PromptRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:agent.v1.PromptRequest)
  private static final com.agent.v1.PromptRequest DEFAULT_INSTANCE;
  static {
    PromptRequest defaultInstance = new PromptRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PromptRequest.class, defaultInstance);
  }

  public static com.agent.v1.PromptRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PromptRequest> PARSER;

  public static com.google.protobuf.Parser<PromptRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

