// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto
// Protobuf Java Version: 4.36.1

package com.agent.v1;

/**
 * Protobuf type {@code agent.v1.SetExtensionConfigRequest}
 */
@com.google.protobuf.Generated
public  final class SetExtensionConfigRequest extends
    com.google.protobuf.GeneratedMessageLite<
        SetExtensionConfigRequest, SetExtensionConfigRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:agent.v1.SetExtensionConfigRequest)
    SetExtensionConfigRequestOrBuilder {
  private SetExtensionConfigRequest() {
    extId_ = "";
    name_ = "";
  }
  private int bitField0_;
  public static final int EXT_ID_FIELD_NUMBER = 1;
  private java.lang.String extId_;
  /**
   * <code>string ext_id = 1 [json_name = "extId"];</code>
   * @return The extId.
   */
  @java.lang.Override
  public java.lang.String getExtId() {
    return extId_;
  }
  /**
   * <code>string ext_id = 1 [json_name = "extId"];</code>
   * @return The bytes for extId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExtIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(extId_);
  }
  /**
   * <code>string ext_id = 1 [json_name = "extId"];</code>
   * @param value The extId to set.
   */
  private void setExtId(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    extId_ = value;
  }
  /**
   * <code>string ext_id = 1 [json_name = "extId"];</code>
   */
  private void clearExtId() {

    extId_ = getDefaultInstance().getExtId();
  }
  /**
   * <code>string ext_id = 1 [json_name = "extId"];</code>
   * @param value The bytes for extId to set.
   */
  private void setExtIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    extId_ = value.toStringUtf8();

  }

  public static final int NAME_FIELD_NUMBER = 2;
  private java.lang.String name_;
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @param value The name to set.
   */
  private void setName(
      java.lang.String value) {
    java.util.Objects.requireNonNull(value);

    name_ = value;
  }
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   */
  private void clearName() {

    name_ = getDefaultInstance().getName();
  }
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @param value The bytes for name to set.
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    name_ = value.toStringUtf8();

  }

  public static final int VALUE_FIELD_NUMBER = 3;
  private com.google.protobuf.Value value_;
  /**
   * <code>.google.protobuf.Value value = 3 [json_name = "value"];</code>
   */
  @java.lang.Override
  public boolean hasValue() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Value value = 3 [json_name = "value"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.Value getValue() {
    return value_ == null ? com.google.protobuf.Value.getDefaultInstance() : value_;
  }
  /**
   * <code>.google.protobuf.Value value = 3 [json_name = "value"];</code>
   */
  private void setValue(com.google.protobuf.Value value) {
    java.util.Objects.requireNonNull(value);
    value_ = value;
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.google.protobuf.Value value = 3 [json_name = "value"];</code>
   */
  @java.lang.SuppressWarnings("ReferenceEquality")
  private void mergeValue(com.google.protobuf.Value value) {
    java.util.Objects.requireNonNull(value);
    if (value_ != null &&
        value_ != com.google.protobuf.Value.getDefaultInstance()) {
      value_ =
        com.google.protobuf.Value.newBuilder(value_).mergeFrom(value).buildPartial();
    } else {
      value_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.google.protobuf.Value value = 3 [json_name = "value"];</code>
   */
  private void clearValue() {
    value_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static com.agent.v1.SetExtensionConfigRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.agent.v1.SetExtensionConfigRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.agent.v1.SetExtensionConfigRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.agent.v1.SetExtensionConfigRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.agent.v1.SetExtensionConfigRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.agent.v1.SetExtensionConfigRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.agent.v1.SetExtensionConfigRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.agent.v1.SetExtensionConfigRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.agent.v1.SetExtensionConfigRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.agent.v1.SetExtensionConfigRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.agent.v1.SetExtensionConfigRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.agent.v1.SetExtensionConfigRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.agent.v1.SetExtensionConfigRequest prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code agent.v1.SetExtensionConfigRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.agent.v1.SetExtensionConfigRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:agent.v1.SetExtensionConfigRequest)
      com.agent.v1.SetExtensionConfigRequestOrBuilder {
    // Construct using com.agent.v1.SetExtensionConfigRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string ext_id = 1 [json_name = "extId"];</code>
     * @return The extId.
     */
    @java.lang.Override
    public java.lang.String getExtId() {
      return instance.getExtId();
    }
    /**
     * <code>string ext_id = 1 [json_name = "extId"];</code>
     * @return The bytes for extId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExtIdBytes() {
      return instance.getExtIdBytes();
    }
    /**
     * <code>string ext_id = 1 [json_name = "extId"];</code>
     * @param value The extId to set.
     * @return This builder for chaining.
     */
    public Builder setExtId(
        java.lang.String value) {
      copyOnWrite();
      instance.setExtId(value);
      return this;
    }
    /**
     * <code>string ext_id = 1 [json_name = "extId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearExtId() {
      copyOnWrite();
      instance.clearExtId();
      return this;
    }
    /**
     * <code>string ext_id = 1 [json_name = "extId"];</code>
     * @param value The bytes for extId to set.
     * @return This builder for chaining.
     */
    public Builder setExtIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setExtIdBytes(value);
      return this;
    }

    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <code>.google.protobuf.Value value = 3 [json_name = "value"];</code>
     */
    @java.lang.Override
    public boolean hasValue() {
      return instance.hasValue();
    }
    /**
     * <code>.google.protobuf.Value value = 3 [json_name = "value"];</code>
     */
    @java.lang.Override
    public com.google.protobuf.Value getValue() {
      return instance.getValue();
    }
    /**
     * <code>.google.protobuf.Value value = 3 [json_name = "value"];</code>
     */
    public Builder setValue(com.google.protobuf.Value value) {
      copyOnWrite();
      instance.setValue(value);
      return this;
      }
    /**
     * <code>.google.protobuf.Value value = 3 [json_name = "value"];</code>
     */
    public Builder setValue(
        com.google.protobuf.Value.Builder builderForValue) {
      copyOnWrite();
      instance.setValue(builderForValue.build());
      return this;
    }
    /**
     * <code>.google.protobuf.Value value = 3 [json_name = "value"];</code>
     */
    public Builder mergeValue(com.google.protobuf.Value value) {
      copyOnWrite();
      instance.mergeValue(value);
      return this;
    }
    /**
     * <code>.google.protobuf.Value value = 3 [json_name = "value"];</code>
     */
    public Builder clearValue() {  copyOnWrite();
      instance.clearValue();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:agent.v1.SetExtensionConfigRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"ThrowNull"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.agent.v1.SetExtensionConfigRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "extId_",
            "name_",
            "value_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0001\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u1009\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.agent.v1.SetExtensionConfigRequest> parser = PARSER;
        if (parser == null) {
          synchronized (com.agent.v1.SetExtensionConfigRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.agent.v1.SetExtensionConfigRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
      // So it can do anything. Combine with default case for smaller codegen.
      case SET_MEMOIZED_IS_INITIALIZED:
    }
    // Should never happen. Generates tight code to throw an exception.
    throw null;
  }


  // @@protoc_insertion_point(class_scope:agent.v1.SetExtensionConfigRequest)
  private static final com.agent.v1.SetExtensionConfigRequest DEFAULT_INSTANCE;
  static {
    SetExtensionConfigRequest defaultInstance = new SetExtensionConfigRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SetExtensionConfigRequest.class, defaultInstance);
  }

  public static com.agent.v1.SetExtensionConfigRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SetExtensionConfigRequest> PARSER;

  public static com.google.protobuf.Parser<SetExtensionConfigRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

