// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package agent.v1;

@kotlin.jvm.JvmName("-initializesetExtensionConfigRequest")
public inline fun setExtensionConfigRequest(block: agent.v1.SetExtensionConfigRequestKt.Dsl.() -> kotlin.Unit): agent.v1.Agent.SetExtensionConfigRequest =
  agent.v1.SetExtensionConfigRequestKt.Dsl._create(agent.v1.Agent.SetExtensionConfigRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.SetExtensionConfigRequest`
 */
public object SetExtensionConfigRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: agent.v1.Agent.SetExtensionConfigRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: agent.v1.Agent.SetExtensionConfigRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): agent.v1.Agent.SetExtensionConfigRequest = _builder.build()

    /**
     * `string ext_id = 1 [json_name = "extId"];`
     */
    public var extId: kotlin.String
      @kotlin.jvm.JvmName("getExtId")
        get() = _builder.extId
      @kotlin.jvm.JvmName("setExtId")
        set(value) {
        _builder.extId = value
      }
    /**
     * `string ext_id = 1 [json_name = "extId"];`
     */
    public fun clearExtId() {
      _builder.clearExtId()
    }

    /**
     * `string name = 2 [json_name = "name"];`
     */
    public var name: kotlin.String
      @kotlin.jvm.JvmName("getName")
        get() = _builder.name
      @kotlin.jvm.JvmName("setName")
        set(value) {
        _builder.name = value
      }
    /**
     * `string name = 2 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * `.google.protobuf.Value value = 3 [json_name = "value"];`
     */
    public var value: com.google.protobuf.Value
      @kotlin.jvm.JvmName("getValue")
        get() = _builder.value
      @kotlin.jvm.JvmName("setValue")
        set(value) {
        _builder.value = value
      }
    /**
     * `.google.protobuf.Value value = 3 [json_name = "value"];`
     */
    public fun clearValue() {
      _builder.clearValue()
    }
    /**
     * `.google.protobuf.Value value = 3 [json_name = "value"];`
     * @return Whether the value field is set.
     */
    public fun hasValue(): kotlin.Boolean {
      return _builder.hasValue()
    }

    public val SetExtensionConfigRequestKt.Dsl.valueOrNull: com.google.protobuf.Value?
      get() = _builder.valueOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun agent.v1.Agent.SetExtensionConfigRequest.copy(block: `agent.v1`.SetExtensionConfigRequestKt.Dsl.() -> kotlin.Unit): agent.v1.Agent.SetExtensionConfigRequest =
  `agent.v1`.SetExtensionConfigRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val agent.v1.Agent.SetExtensionConfigRequestOrBuilder.valueOrNull: com.google.protobuf.Value?
  get() = if (hasValue()) getValue() else null

