// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.agent.v1;

@kotlin.jvm.JvmName("-initializeupdateSettingsResponse")
public inline fun updateSettingsResponse(block: com.agent.v1.UpdateSettingsResponseKt.Dsl.() -> kotlin.Unit): com.agent.v1.UpdateSettingsResponse =
  com.agent.v1.UpdateSettingsResponseKt.Dsl._create(com.agent.v1.UpdateSettingsResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.UpdateSettingsResponse`
 */
public object UpdateSettingsResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.agent.v1.UpdateSettingsResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.agent.v1.UpdateSettingsResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.agent.v1.UpdateSettingsResponse = _builder.build()

    /**
     * `.agent.v1.Session session = 1 [json_name = "session"];`
     */
    public var session: com.agent.v1.Session
      @kotlin.jvm.JvmName("getSession")
        get() = _builder.session
      @kotlin.jvm.JvmName("setSession")
        set(value) {
        _builder.session = value
      }
    /**
     * `.agent.v1.Session session = 1 [json_name = "session"];`
     */
    public fun clearSession() {
      _builder.clearSession()
    }
    /**
     * `.agent.v1.Session session = 1 [json_name = "session"];`
     * @return Whether the session field is set.
     */
    public fun hasSession(): kotlin.Boolean {
      return _builder.hasSession()
    }

    public val UpdateSettingsResponseKt.Dsl.sessionOrNull: com.agent.v1.Session?
      get() = _builder.sessionOrNull
  }
}
public inline fun com.agent.v1.UpdateSettingsResponse.copy(block: `com.agent.v1`.UpdateSettingsResponseKt.Dsl.() -> kotlin.Unit): com.agent.v1.UpdateSettingsResponse =
  `com.agent.v1`.UpdateSettingsResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.agent.v1.UpdateSettingsResponseOrBuilder.sessionOrNull: com.agent.v1.Session?
  get() = if (hasSession()) getSession() else null

