// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package agent.v1;

@kotlin.jvm.JvmName("-initializeuploadFileResponse")
public inline fun uploadFileResponse(block: agent.v1.UploadFileResponseKt.Dsl.() -> kotlin.Unit): agent.v1.Agent.UploadFileResponse =
  agent.v1.UploadFileResponseKt.Dsl._create(agent.v1.Agent.UploadFileResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `agent.v1.UploadFileResponse`
 */
public object UploadFileResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: agent.v1.Agent.UploadFileResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: agent.v1.Agent.UploadFileResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): agent.v1.Agent.UploadFileResponse = _builder.build()

    /**
     * `bool ok = 1 [json_name = "ok"];`
     */
    public var ok: kotlin.Boolean
      @kotlin.jvm.JvmName("getOk")
        get() = _builder.ok
      @kotlin.jvm.JvmName("setOk")
        set(value) {
        _builder.ok = value
      }
    /**
     * `bool ok = 1 [json_name = "ok"];`
     */
    public fun clearOk() {
      _builder.clearOk()
    }

    /**
     * `string code = 2 [json_name = "code"];`
     */
    public var code: kotlin.String
      @kotlin.jvm.JvmName("getCode")
        get() = _builder.code
      @kotlin.jvm.JvmName("setCode")
        set(value) {
        _builder.code = value
      }
    /**
     * `string code = 2 [json_name = "code"];`
     */
    public fun clearCode() {
      _builder.clearCode()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun agent.v1.Agent.UploadFileResponse.copy(block: `agent.v1`.UploadFileResponseKt.Dsl.() -> kotlin.Unit): agent.v1.Agent.UploadFileResponse =
  `agent.v1`.UploadFileResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

