// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: agent/v1/agent.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.agent.v1;

@kotlin.jvm.JvmName("-initializeworksheet")
public inline fun worksheet(block: com.agent.v1.WorksheetKt.Dsl.() -> kotlin.Unit): com.agent.v1.Worksheet =
  com.agent.v1.WorksheetKt.Dsl._create(com.agent.v1.Worksheet.newBuilder()).apply { block() }._build()
/**
 * ```
 * Worksheet row.
 * ```
 *
 * Protobuf type `agent.v1.Worksheet`
 */
public object WorksheetKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.agent.v1.Worksheet.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.agent.v1.Worksheet.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.agent.v1.Worksheet = _builder.build()

    /**
     * `string id = 1 [json_name = "id"];`
     */
    public var id: kotlin.String
      @kotlin.jvm.JvmName("getId")
        get() = _builder.id
      @kotlin.jvm.JvmName("setId")
        set(value) {
        _builder.id = value
      }
    /**
     * `string id = 1 [json_name = "id"];`
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * `string session_name = 2 [json_name = "sessionName"];`
     */
    public var sessionName: kotlin.String
      @kotlin.jvm.JvmName("getSessionName")
        get() = _builder.sessionName
      @kotlin.jvm.JvmName("setSessionName")
        set(value) {
        _builder.sessionName = value
      }
    /**
     * `string session_name = 2 [json_name = "sessionName"];`
     */
    public fun clearSessionName() {
      _builder.clearSessionName()
    }

    /**
     * `string ext_id = 3 [json_name = "extId"];`
     */
    public var extId: kotlin.String
      @kotlin.jvm.JvmName("getExtId")
        get() = _builder.extId
      @kotlin.jvm.JvmName("setExtId")
        set(value) {
        _builder.extId = value
      }
    /**
     * `string ext_id = 3 [json_name = "extId"];`
     */
    public fun clearExtId() {
      _builder.clearExtId()
    }

    /**
     * `string action = 4 [json_name = "action"];`
     */
    public var action: kotlin.String
      @kotlin.jvm.JvmName("getAction")
        get() = _builder.action
      @kotlin.jvm.JvmName("setAction")
        set(value) {
        _builder.action = value
      }
    /**
     * `string action = 4 [json_name = "action"];`
     */
    public fun clearAction() {
      _builder.clearAction()
    }

    /**
     * `string args = 5 [json_name = "args"];`
     */
    public var args: kotlin.String
      @kotlin.jvm.JvmName("getArgs")
        get() = _builder.args
      @kotlin.jvm.JvmName("setArgs")
        set(value) {
        _builder.args = value
      }
    /**
     * `string args = 5 [json_name = "args"];`
     */
    public fun clearArgs() {
      _builder.clearArgs()
    }

    /**
     * `string title = 6 [json_name = "title"];`
     */
    public var title: kotlin.String
      @kotlin.jvm.JvmName("getTitle")
        get() = _builder.title
      @kotlin.jvm.JvmName("setTitle")
        set(value) {
        _builder.title = value
      }
    /**
     * `string title = 6 [json_name = "title"];`
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * `string origin_call_id = 7 [json_name = "originCallId"];`
     */
    public var originCallId: kotlin.String
      @kotlin.jvm.JvmName("getOriginCallId")
        get() = _builder.originCallId
      @kotlin.jvm.JvmName("setOriginCallId")
        set(value) {
        _builder.originCallId = value
      }
    /**
     * `string origin_call_id = 7 [json_name = "originCallId"];`
     */
    public fun clearOriginCallId() {
      _builder.clearOriginCallId()
    }

    /**
     * `string status = 8 [json_name = "status"];`
     */
    public var status: kotlin.String
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    /**
     * `string status = 8 [json_name = "status"];`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `string created_at = 9 [json_name = "createdAt"];`
     */
    public var createdAt: kotlin.String
      @kotlin.jvm.JvmName("getCreatedAt")
        get() = _builder.createdAt
      @kotlin.jvm.JvmName("setCreatedAt")
        set(value) {
        _builder.createdAt = value
      }
    /**
     * `string created_at = 9 [json_name = "createdAt"];`
     */
    public fun clearCreatedAt() {
      _builder.clearCreatedAt()
    }

    /**
     * `string decided_at = 10 [json_name = "decidedAt"];`
     */
    public var decidedAt: kotlin.String
      @kotlin.jvm.JvmName("getDecidedAt")
        get() = _builder.decidedAt
      @kotlin.jvm.JvmName("setDecidedAt")
        set(value) {
        _builder.decidedAt = value
      }
    /**
     * `string decided_at = 10 [json_name = "decidedAt"];`
     */
    public fun clearDecidedAt() {
      _builder.clearDecidedAt()
    }
  }
}
public inline fun com.agent.v1.Worksheet.copy(block: `com.agent.v1`.WorksheetKt.Dsl.() -> kotlin.Unit): com.agent.v1.Worksheet =
  `com.agent.v1`.WorksheetKt.Dsl._create(this.toBuilder()).apply { block() }._build()

